### ISSUE TITLE
Right Arrows in search menu.

### ISSUE THREAD

**Issue by Dave-Parry** [Tikipeter/tikipeter.github.io#1]
as a long time user of fen, it is my go-to kodi app. However recently I have a issue. why have I got right arrows (>>) when searching down the menu tree, instead number of unwatched Videos?
Can I get this back? I now have to go all the way down the menu tree to see if there are any new video’s.
Please>>>
![20231228_184359](https://github.com/Tikipeter/tikipeter.github.io/assets/9755612/8b1cebbf-6c22-4b8e-a6c5-
![20231228_185701](https://github.com/Tikipeter/tikipeter.github.io/assets/9755612/fb9bf52c-b232-4342-8488-c410ff0a38a6)

**Comment by Tikipeter** [comment]
I have no idea what you're talking about, and the image that would likely clear it up for me is not working. Could you re-format your post so that the image appears correctly? It looks like you didn't wait for the image to upload fully before finalizing the post.

**Comment by Dave-Parry** [comment]
Regards
David Parry
***@***.***

￼

**Comment by Tikipeter** [comment]
I'll need Kodi version.

But that's a skin issue. If you're running a Kodi 21 install, it could be related to that.

**Comment by Dave-Parry** [comment]
Thanks for reply,
I’m running Kodi 20.2 on a osmc vero 4k and on a vero 5
The skin is a silvio aeon nox
Have had a look at its settings and cant find anything that gets rid of them.
Looking at the logs it did do a skin update a little while ago and that may have been the start of it.
Sorry for the trouble and thanks for your help.

Regards
David Parry
***@***.***

**Comment by Tikipeter** [comment]
I tried a couple of other widely used Kodi addons, including one from the official repository, and they also do not show episode counts in the TV Show menu.

All addons still show episode counts at the season level menu, including Fen.

I'm sorry I can't really help more with this. Nothing in this area of Fen has changed for a long time.

**Comment by Dave-Parry** [comment]
Thanks for reply.
Do they also show the arrows?

Regards
David Parry
***@***.***

**Comment by Tikipeter** [comment]
Yes. All other addons also show the arrows at TV Show level.

**Comment by Dave-Parry** [comment]
Thanks

Regards
David Parry
***@***.***
