### ISSUE TITLE
"Fen playback failed" on Kodi Omega beta 2

### ISSUE THREAD

**Issue by cg00001** [Tikipeter/tikipeter.github.io#10]
I'm getting "Fen playback failed" on everything I play on Fen after it stops.
This started in Kodi Omega beta 1 after a kodi-git update on my Arch Linux.
Still goes on on latest beta, works fine on Nexus.
![Fen playback failed](https://github.com/Tikipeter/tikipeter.github.io/assets/38960370/58c38e66-28d5-43a8-899c-f8b1923056ae)

**Comment by Tikipeter** [comment]
Use Nexus.

**Comment by cg00001** [comment]
I told a friend with windows to try it on Omega, and he has no problem, so it seems this is a Linux only issue.

**Comment by Tikipeter** [comment]
follow this issue...

https://github.com/Tikipeter/tikipeter.github.io/issues/7
