### ISSUE TITLE
Trakt Watched TV Show history?

### ISSUE THREAD

**Issue by Shredder5262** [Tikipeter/tikipeter.github.io#102]
I don't find a menu item for recently watched TV show history from trakt? I looked under "My Lists" and i see some menu items for trakt, but none of the trakt menu items are reflective of what I've been recently watching ... Is it called something else? Does it even exist as a menu item? As It is now, I have to do a search for any tv show that i already know I've been watching and then recall it from the search history.

**Comment by rizreflects** [comment]
It's under the TV shows section. Fen light > TV Shows > Recently watched episodes. Although for what you want, it sounds like you're better off going for the 'next episodes' option, so you can pick up exactly where you left off.

**Comment by Shredder5262** [comment]
> It's under the TV shows section. Fen light > TV Shows > Recently watched episodes. Although for what you want, it sounds like you're better off going for the 'next episodes' option, so you can pick up exactly where you left off.

Thanks for the response, this is close to what I'm looking for, but not exactly, I am wanting to view them as recently watched TV shows, then be able to select the season, then the episode from there....is this possible?

Lets say for example the last 3 episodes i watched was Fire country S2E1, Teen mom S2E12 and Peaky Blinders S3E12

I could nav from the menu to view>Fire country, Teen mom, and peaky blinders...then select the season and episode from there.
This was a possibility in Seren and was pretty handy so I was hoping to find something close to it in fen light.

**Comment by Tikipeter** [comment]
In Progress.

**Comment by Shredder5262** [comment]
> In Progress.

Maybe closer yet, I'll have to check with the wife, there's a bunch of TV Shows that i don't recognize....possible to sort chronologically by last watched? My view is showing them alphabetically sorted

**Comment by Tikipeter** [comment]
Yes, you can sort by last watched.

You need to at least open the settings and attempt to familiarize yourself with what's available.

This area is more for "issues" rather than personally answering multiple support questions.

**Comment by Shredder5262** [comment]
So where do i go for questions?
