### ISSUE TITLE
[Feature Request] Separate 'Minimum Size' filter for movies and episodes

### ISSUE THREAD

**Issue by OfficerKD637** [Tikipeter/tikipeter.github.io#103]
Hi Peter,

Hope you've been doing well!

I was wondering if you could bifurcate the 'Minimum Size' filter into movies and episodes? I am currently trying to create a sweet spot for autoplay with the maximum and minimum size filters, but a minimum size for a movie (eg. 30 GB) won't make sense for an episode (which tends to be in the 5 - 8 GB range on average).

Let me know what you think.

**Comment by OfficerKD637** [comment]
Thank you so much Peter, I really appreciate it!

I just read the new rules about submitting Feature Requests.

Apart from this current feature request (status: pending update), I also have 2 other open requests.
One of which you have already self-assigned and said you'd look into (since it's quite tedious to implement). Do I need to delete the other one? I posted those about a week ago but I'm happy to comply with the new rules.

And I'll make sure to follow these going forward.

Thank you!

**Comment by Tikipeter** [comment]
No need. The rules are just for moving forward. There's a couple of you with multiple requests currently which are fine.

I just need to limit them a little, as lots of open issues tickles my anxiety for some reason.

**Comment by OfficerKD637** [comment]
Haha I get it! The last thing I'd want is to tickle you the wrong way lol. 
If I may... the [ostrich algorithm](https://en.wikipedia.org/wiki/Ostrich_algorithm) is something worth looking into when you're trying to resolve future bugs/issues.

**Comment by Tikipeter** [comment]
Done for next update.
