### ISSUE TITLE
[Feature Request] allow a skinner to control the colour of unaired title (from default red)

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#106]
Hey Tikipeter, unaired episodes have red font in their titles, like

![Screenshot (479)](https://github.com/user-attachments/assets/6a646a9f-4aa8-49ee-8f2c-40ba399a96de)

I was wondering if you could leave that as default but also allow a skinner to change that colour if they so choose to. I like the dynamic colour changing inside Nimbus, and to keep it consistent and aesthetic, was hoping we could have something like this.

<img width="1280" alt="new screenshot" src="https://github.com/user-attachments/assets/26c04e0f-311a-4161-87e9-f85ba4ede614">

so the colour of text will be the same as the little scrollbar for each show.

If it's too much trouble then it's fine. Thanks for your consideration.

**Comment by Tikipeter** [comment]
Would need to support all skins unfortunately. Not really possible.

**Comment by hcgiub001** [comment]
It's fine thanks anyway
