### ISSUE TITLE
Bug (skip links)

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/tikipeter.github.io#107]
Good day Peter,

I think I have a bug.

If I play an episode and it's finished and I want to watch another episode/movie, he gets the links but then he can't play 1, he skips them himself.

Can you please take a look at that?

Thanks in advance.

[https://paste.kodi.tv/segitaqibe](url)

**Comment by Tikipeter** [comment]
Kodi is reporting your hardware is unable to start new threads. Has this issue resolved itself, as your hardware NEEDS to start new threads for Kodi addons to work correctly. There are plenty of things we use threading for.

**Comment by djdirty60** [comment]
Yes it resolves when I restart Kodi, but that's annoying. Is there a solution to this problem?

Thanks in advance
