### ISSUE TITLE
Fen Light dependency err on OSMC 2024-08-1 \ Kodi 21.1

### ISSUE THREAD

**Issue by MehBlorg** [Tikipeter/tikipeter.github.io#108]
https://www.reddit.com/r/Addons4Kodi/comments/1f56tm5/fen_light_dependency_err_on_osmc_2024081_kodi_211/

**Comment by Tikipeter** [comment]
Nothing to do with me or Fen Light.

**Comment by MehBlorg** [comment]
Oh. OK. Sorry to bug you.
