### ISSUE TITLE
Skip Intro Button Using Chapters 

### ISSUE THREAD

**Issue by IG2022** [Tikipeter/tikipeter.github.io#112]
Hey there!

Would it be possible to include a setting to allow a skip intro button using the chapter information from a file? I know this has already implemented with the credits chapter and was wondering if it could be done with the intro aswell if a file has that information. I've seen the intro chapter included from shows from major networks and it would be great to get quickly skip over especially long intros. 

Thanks!

**Comment by Tikipeter** [comment]
I can't add buttons to a skin's display.

I could look into a window appearing, like when using autoplay next episode, but maybe that would be more intrusive than helpful?

**Comment by Tikipeter** [comment]
Unfortunately, this is not going to be possible. The only information I have at the start of the video are percentage markers of where each chapter starts within the video.

For example, Kodi returns this for an episode of The Rings OF Power:
```
0.00000,0.16363,0.16363,4.06341,4.06341,6.62690,6.62690,7.03596,7.03596,8.04500,8.04500,8.29044,8.29044,15.32640,15.32640,15.46276,15.46276,16.00818,16.00818,17.67172,17.67172,25.08948,25.08948,25.33492,25.33492,28.19840,28.19840,28.49838,28.49838,29.80740,29.80740,30.24374,30.24374,32.26180,32.26180,32.42543,32.42543,33.10721,33.10721,33.27084,33.27084,34.44350,34.44350,37.57968,37.57968,37.96148,37.96148,38.50690,38.50690,38.61599,38.61599,38.80688,38.80688,39.48867,39.48867,40.11590,40.11590,40.30680,40.30680,40.66133,40.66133,40.79768,40.79768,42.02488,42.02488,42.18851,42.18851,43.57934,43.57934,46.38828,46.38828,46.60644,46.60644,48.89722,48.89722,49.38810,49.38810,51.10619,51.10619,52.30612,52.30612,53.36969,53.36969,53.94239,53.94239,59.06937,59.06937,59.99659,59.99659,61.55105,61.55105,61.87830,61.87830,64.74178,64.74178,65.09630,65.09630,66.54167,66.54167,67.65979,67.65979,68.85973,68.85973,69.97784,69.97784,74.75030,74.75030,74.88666,74.88666,75.07755,75.07755,78.67735,78.67735,80.55906,80.55906,80.88631,80.88631,82.63167,82.63167,85.57696,85.57696,86.14965,86.14965,86.61326,86.61326,86.94051,86.94051,87.43140,87.43140,87.64957,87.64957,88.16772,88.16772,88.33134,88.33134,89.44946,89.44946,91.08573,91.08573,91.74024,91.74024,92.01295
```

That mash of digits is OK for establishing the last chapter, but is way more problematic when establishing the correct chapter to jump to to skip the intro credits.

Since I can't get the name of a chapter until the player is actually within that chapter, I can't use naming to ascertain which chapter to jump to.

**Comment by IG2022** [comment]
> Unfortunately, this is not going to be possible. The only information I have at the start of the video are percentage markers of where each chapter starts within the video.
> 
> For example, Kodi returns this for an episode of The Rings OF Power:
> 
> ```
> 0.00000,0.16363,0.16363,4.06341,4.06341,6.62690,6.62690,7.03596,7.03596,8.04500,8.04500,8.29044,8.29044,15.32640,15.32640,15.46276,15.46276,16.00818,16.00818,17.67172,17.67172,25.08948,25.08948,25.33492,25.33492,28.19840,28.19840,28.49838,28.49838,29.80740,29.80740,30.24374,30.24374,32.26180,32.26180,32.42543,32.42543,33.10721,33.10721,33.27084,33.27084,34.44350,34.44350,37.57968,37.57968,37.96148,37.96148,38.50690,38.50690,38.61599,38.61599,38.80688,38.80688,39.48867,39.48867,40.11590,40.11590,40.30680,40.30680,40.66133,40.66133,40.79768,40.79768,42.02488,42.02488,42.18851,42.18851,43.57934,43.57934,46.38828,46.38828,46.60644,46.60644,48.89722,48.89722,49.38810,49.38810,51.10619,51.10619,52.30612,52.30612,53.36969,53.36969,53.94239,53.94239,59.06937,59.06937,59.99659,59.99659,61.55105,61.55105,61.87830,61.87830,64.74178,64.74178,65.09630,65.09630,66.54167,66.54167,67.65979,67.65979,68.85973,68.85973,69.97784,69.97784,74.75030,74.75030,74.88666,74.88666,75.07755,75.07755,78.67735,78.67735,80.55906,80.55906,80.88631,80.88631,82.63167,82.63167,85.57696,85.57696,86.14965,86.14965,86.61326,86.61326,86.94051,86.94051,87.43140,87.43140,87.64957,87.64957,88.16772,88.16772,88.33134,88.33134,89.44946,89.44946,91.08573,91.08573,91.74024,91.74024,92.01295
> ```
> 
> That mash of digits is OK for establishing the last chapter, but is way more problematic when establishing the correct chapter to jump to to skip the intro credits.
> 
> Since I can't get the name of a chapter until the player is actually within that chapter, I can't use naming to ascertain which chapter to jump to.

No worries! Thanks for checking if it was feasiblle. I appreciate it.
