### ISSUE TITLE
NOTIFICATION: Widget Refresh Ability

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#116]
Apologies all.

The recent update has this new feature, but I messed up and deleted some code in the service that is needed just before releasing the updates.

Might be best to set to OFF the setting to refresh widgets on a timer until I can get home to fix it, which won't be for many hours.

**Comment by hcgiub001** [comment]
I relayed the message in addons4kodi subreddit

**Comment by Tikipeter** [comment]
> I relayed the message in addons4kodi subreddit

Will give me a chance to try out my new "ignore the baiting trolls and don't engage" reddit strategy.

**Comment by hcgiub001** [comment]
> > I relayed the message in addons4kodi subreddit
> 
> Will give me a chance to try out my new "ignore the baiting trolls and don't engage" reddit strategy.

I didn't realise I give them a chance to hurt others. Let me know if you'd like the post to go down. I have no idea why you carry on with Fenlight. As much as I'd be torn you might stop Fenlight development, I urge you to think of what you want to get out of this. The community will not change. If I was you Peter I would not be doing this. If you wanted to move on, those that have a heart will understand

**Comment by hcgiub001** [comment]
I deleted the post. If they have any issues or complaints, they know where to look.

**Comment by Tikipeter** [comment]
It's fine, you can leave it up. No worries :). People like that will always be around, and there's no way to argue with them without eventually turning horrible yourself I've learned. And I've often been my own worst enemy attracting them with plenty of material to use against me. :)

**Comment by Tikipeter** [comment]
Oop, just read your last comment. Sorry you felt you had to take it down, the replies truly weren't bothering me. I decided that needed to be the way if coming back to reddit. Just ignore them if possible.

**Comment by hcgiub001** [comment]
sorry you have to read and battle constantly with hate.

**Comment by Tikipeter** [comment]
It's cool.

I appreciate you sticking up for me. You're a good person.

But they're set in their beliefs so it's a losing battle.
