### ISSUE TITLE
Can Fen auto update?

### ISSUE THREAD

**Issue by Maxxx233** [Tikipeter/tikipeter.github.io#12]
Every time an update comes out i have to download it manually

**Comment by Tikipeter** [comment]
Why?

**Comment by Maxxx233** [comment]
What why I like it better when it auto updates and i dont have to worry about that

**Comment by Tikipeter** [comment]
Then set it to auto update.

Fen updates itself now. Has for about the last month.

Give me some more (any) information i.e. what version you are currently on, and I'd likely be able to offer some sensical  advice.

Otherwise, the answer to your question is yes, Fen can auto update.
