### ISSUE TITLE
[BUG] shows and episodes not showing in trakt lists

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#122]
so someone asked this question
https://www.reddit.com/r/Addons4Kodi/comments/1fiav4v/shuffle_play_specific_seasons_from_a_show/

I've seen twice people who are interested in a season but want the episodes shuffled, so I remembered Fenlite has random feature. I realised I had to add individual episodes as single items. Got excited that this would be a great addition that people might want to have (and make a video)

but Fenlite wasn't showing up the episodes and I left it thinking their is no chance
but looking back at the question the person asked, they used POV which made me think does POV show the episodes
![image](https://github.com/user-attachments/assets/382d6dce-0b9f-4546-9027-14866ddbb6c1)

It does, I also used Trakt random order feature but once it's cached it won't randomise the list again, so Fenlite would be pretty awesome at this (and let me make my video) 

is this a bug that it's not showing the episodes? I went into random list
trakt lists , shuffle contents trakt lists,
it sees that their are items but when I click inside the folder nothing shows.
Thanks

**Comment by Tikipeter** [comment]
Not a bug.

Only movies and tvshows are supported for trakt lists. No seasons or episodes. In Fen Light of course. They could be supported like kodifitzwell did.

But then you've got movies, tvshows, seasons and episodes possibly all in one list. What view do you set for that?

Skins have different views for different media. So supporting movies and tvshows mainly works, as the views for those 2 are usually the same. But when you get into seasons and episodes it will quickly not work well.

I've never come up with a way to deal with that, and for many (most) skins it would be a bit of a disaster I assume.

**Comment by hcgiub001** [comment]
I understand.
I added movies/shows/seasons and episodes and tested in POV
https://streamable.com/b2yor1

It seemed pleasant to look at, especially in poster view, so those that enter these mixed lists can change the view.
it's a feature I've seen asked a few times, people wanting to put on background noise and want random episodes of Simpsons or something.

I didn't even know you could add single episodes and single seasons. 
It's fine if you feel it won't work well.
