### ISSUE TITLE
[Feature Request] Filter to exclude "AI Upscaled" sources

### ISSUE THREAD

**Issue by rich333000** [Tikipeter/tikipeter.github.io#124]
Hey, was wondering if an option to filter out sources containing "AI Upscaled" in the file name could be implemented, similar to how 3D or CAM sources can be excluded from results. I keep seeing more and more of these lately and I really think they ruin the content to the point of being unwatchable, details like are blurry (watch Hard Rain lol) or usually frames are added for a smooth soap opera effect which can't be disabled.

**Comment by Tikipeter** [comment]
Can you point me directly to an example. I searched the movie "Hard Rain", ran a scrape on the 1998 Thriller, and didn't get any links containing "AI Upscaled"

Maybe post a screen image of that result, or quote the result with more info.

**Comment by rich333000** [comment]
Hard Rain actually just had "Upscaled" in the filename. Othere I've seen usually have "AI Upscaled". Both are bad to watch. I've attached 2 images for example 
![Uploading PXL_20240920_022818108.MP~2.jpg…]()

**Comment by rich333000** [comment]
![PXL_20240920_022924765 MP~2](https://github.com/user-attachments/assets/97ce8fe6-b40c-4ae9-9598-6e0423895d6b)

**Comment by rich333000** [comment]
![PXL_20240920_022818108 MP~2](https://github.com/user-attachments/assets/c970d994-576a-4663-96f4-12df7eea4581)

**Comment by Tikipeter** [comment]
`Upscaled` would be fine to identify with. Parsing the name of the file is the only way to identify characteristics. So I need a string that's common, or a list of strings that are common for this type of video. Only then can it be filtered out.

If you notice any other taggings for this type of file other than `upscaled` let me know.

Maybe that will be enough to idenify these file types.

**Comment by OfficerKD637** [comment]
I've also seen **AI Enhanced** pop up as one of the tags. The example below is 'Man Of Steel'

![image](https://github.com/user-attachments/assets/a7748797-b42b-4aea-8086-f8f44a9da941)

**Comment by Tikipeter** [comment]
If I use `upscaled` and `enhanced` (without the `ai` suffix) do you know of any false positives that may arise? Are those 2 strings used in situations other than this AI tomfoolery?

**Comment by rich333000** [comment]
I've googled around a bit the only other thing I could find of interest is
some are either Enhance or Enhanced and Upscale or Upscaled.

I couldn't think of any false positives.

**Comment by Tikipeter** [comment]
I appreciate you taking the time. That was good of you.

I will include enhance and upscale in the next update. I've done enough damage today to touch anything now.

**Comment by OfficerKD637** [comment]
I'm really sorry to comment on a closed issue, but I _think_ 'IMAX ENHANCED' could be one of the false positives that could pop up here.
I will try to find some examples and post here later.

**Comment by Tikipeter** [comment]
Thanks OfficerKD637.

I'll check if the file is tagged as IMAX before dealing with the enhanced tags.

**Comment by OfficerKD637** [comment]
Thank you so much Peter! You're the best!
