### ISSUE TITLE
Repo empty

### ISSUE THREAD

**Issue by DaleAlan** [Tikipeter/tikipeter.github.io#125]
Howdo Peter hope you’re keeping well and taking time to chill and enjoy life. Just a quick heads up as I don’t use the repo for downloading as I just nab the zip file direct but it looks like there might be a bit of a blip if you try to instal zip from the repo from the source select way. https://www.reddit.com/r/Addons4Kodi/s/IEt9uDiFmQ

Works perfect through the downloaded zip though.

**Comment by Tikipeter** [comment]
Thanks mate.

**Comment by DaleAlan** [comment]
More than welcome big fella. Thanks for sorting it before everyone had a breakdown hah Have a good ‘un.
