### ISSUE TITLE
Trakt lists not updated

### ISSUE THREAD

**Issue by naudski** [Tikipeter/tikipeter.github.io#126]
Hi Tikipeter,

Lately or maybe longer the Trakt lists I liked are not being updated anymore in Fen Light. I need to clear the cache everytime to get those lists updated.
Could this be a bug?

Kodilog: https://paste.kodi.tv/kolusocica

**Comment by Tikipeter** [comment]
Kinda a bug. I'll post a version with a change needed momentarily.

**Comment by naudski** [comment]
Thanks!!

**Comment by Tikipeter** [comment]
Apologies. Something else with different code has come up. I may not post a fix for this until tomorrow.

I'll see how I go.

**Comment by naudski** [comment]
Thanks Tikipeter!!
