### ISSUE TITLE
Extras command not activating on key press

### ISSUE THREAD

**Issue by TheSymm** [Tikipeter/tikipeter.github.io#128]
I recently reinstalled my whole Kodi application and now can't get the extras menu to be activated on a keymap press.

Kodi log: https://paste.kodi.tv/obegalojox

Here is my keymap edit gen.xml, just in case I have something wrong.

https://paste.kodi.tv/iwapipenuy.kodi

Thanks for the addon bro, keep up the good work.

**Comment by hcgiub001** [comment]
Tikipeter changed the command a while back but it's not been documented in update log
https://github.com/Tikipeter/tikipeter.github.io/issues/67#issuecomment-2266302801




> OK. Done for next update.
> 
> The commands for custom keys will change from next update though. So I can keep an eye on what's going on with them I made a new module for them.
> 
> EXTRAS DIALOG: `RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key.extras_menu)`
> 
> OPTIONS DIALOG: `RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key.options_menu)`
> 
> MORE LIKE THIS: `RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key.more_like_this)`
> 
> I don't think you use the Options command, but you'll need to change the Extras command after this next update.

The extras menu works if you use the latest path

**Comment by TheSymm** [comment]
Thanks heaps mate.

**Comment by hcgiub001** [comment]
> Thanks heaps mate.

no need to thank me, Tikipeter is the one who deserves the praise
