### ISSUE TITLE
[Request] Thumbnail Cache Cleaner for Android 14

### ISSUE THREAD

**Issue by Cloudman999** [Tikipeter/tikipeter.github.io#132]
Hi @Tikipeter 
You were kind enough to update the old Thumbnail Cache Cleaner add-on to work with Kodi 20 a while ago.

I have just bought the new Google 4K Streamer, that has Android 14 installed.

I can't get your Thumbnail Cache Cleaner to work with this version.

Is it possible to look into updating it to work with Kodi 21 and Android 14, please?

If possible, can you add it to this repository, so I may install it?

With kind regards
@Cloudman

**Comment by Tikipeter** [comment]
I wouldn't know where to start.

It works on Kodi 21 just fine, so it must be an issue with permissions.

Kodi would deal with permissions when running a Kodi addon like this. Check if you can navigate to the Thumbnail folder from within Kodi's File Manager.

**Comment by Cloudman999** [comment]
Thank you for your quick reply @Tikipeter 

I may not be using the latest version of your Thumbnail Cache Cleaner.

Can you tell me where I can download the latest version of your Thumbnail Cache Cleaner that works with Kodi 21, please?

If that doesn't work on the Google TV Streamer, I will need to see if I can navigate to the Thumbnail folder from within Kodi's File Manager.

Once again, thank you so much for your help. It is very much appreciated!

@Cloudman999

**Comment by Cloudman999** [comment]
Hi @Tikipeter
I tried, but cannot navigate to the Thumbnail folder from within Kodi's File Manager.

Any other ideas?

**Comment by Tikipeter** [comment]
Only an idea, because I don't use an Android box.

I think you need to set correct access permissions in the Android settings.

Once you can access that folder,  you should be able to use the image cache cleaner.

**Comment by Cloudman999** [comment]
Could you tell me where I can download the latest version of your Thumbnail Cache Cleaner, @Tikipeter?

Thank you
@Cloudman999

**Comment by adamosborne83** [comment]
Android 14 has VERY different permissions and is an absolute nightmare for kodi and addons. Cannot even access it via ADBLINK. There are ways around it, but Google is your friend here.

**Comment by Tikipeter** [comment]
[plugin.program.thumbcache.cleaner-1.0.04.zip](https://github.com/user-attachments/files/17178367/plugin.program.thumbcache.cleaner-1.0.04.zip)

That's the latest. 

Thanks Adam for the advice. I'm not up on Android as you know.   :)

**Comment by Cloudman999** [comment]
Thank you very much @Tikipeter and @adamosborne83 for trying to help me.

I do appreciate all you guys do ( and for the wonderful Fen Lite addon) @Tikipeter .

I'm hoping the download you provided (thank you) may be a later version than the one I tried earlier.

I will try installing it when I have access to my Google 4K Streamer.

I'm not familiar with android 14, but already hate it, as it seems to restrict access the android sub folders where Kodi is installed.

So, unless I can get your thumbnail cache cleaner working, I'm going to fill up any extra storage I thought I had gained with this new device.

The wife goes through lots of years looking for  suitable movies in Fen Lite, and that builds up those thumbnails 😩

All the best
@Cloudman999

**Comment by Cloudman999** [comment]
> Android 14 has VERY different permissions and is an absolute nightmare for kodi and addons. Cannot even access it via ADBLINK. There are ways around it, but Google is your friend here.

Hi @adamosborne83 
I installed your Open Wizard add-on for Kodi.
Does this support the cleaning of the thumbnails cache on Android 14?

**Comment by Cloudman999** [comment]
Hi @Tikipeter @adamosborne83 

With some fiddling I was able to delete the thumbnails from within Kodi.

You will need to perform the following for a clean start with respect to the artwork texture cache.

Exit Kodi
Delete texturesxx.db located in the \userdata\database\ folder.
Delete the Thumbnails directory located at \userdata\ which stores all the cached images,
Once the above steps are performed

Restart Kodi
Kodi will automatically rebuild the Textures database and repopulate the Thumbnails cache as the images are displayed in the GUI or other Kodi interface.

**Comment by Cloudman999** [comment]
Hi @Tikipeter & @adamosborne83 

I am not an experienced programmer, but I will try and create a simple Kodi standalone add-on written in Python 3.

This add-on will delete the Thumbnails folder and the associated Textures13.db file from my Kodi userdata folder.

When I've got it working, I'll post it on my Github page, so you guys can get a copy.

Thank you both for the assistance.

Kind regards
@Cloudman999

**Comment by Tikipeter** [comment]
Hang on. Are you saying Kodi has access to the Thumbnails folder (meaning you can navigate to it from within Kodi's File Manager) and that the cache cleaner still doesn't work? Meaning you have to make an addon yourself?

**Comment by Cloudman999** [comment]
Hi @Tikipeter @adamosborne83 
I have discovered that the Open Wizard Program for Kodi has two maintenance options:

The first one can be used to clear the thumbnail cache and its associated Textures13.db file

The second can be used to clear package files.

So, I now have a solution that works on my Google TV 4K Streamer with Android 14.

I have abandoned trying to write my own Python 3 add-on.

So, unless you are planning to update your plugin.program.thumbcache.cleaner-1.0.04 add-on for Kodi to work with Android 14 on Kodi, I think you can close this Request @Tikipeter .

All the best
@Cloudman999

**Comment by Cloudman999** [comment]
> Hang on. Are you saying Kodi has access to the Thumbnails folder (meaning you can navigate to it from within Kodi's File Manager) and that the cache cleaner still doesn't work? Meaning you have to make an addon yourself?

Hi @Tikipeter 
Yes, I can navigate to the Thumbnails folder from within Kodi's File Manager but your cache cleaner did not work in Android 14 on my Google 4K Streamer.

I am using Open Wizard thumbnail cleaner now, as I couldn't write my own in python.

It would be great if you could fix it to work though!

Let me know if you decide to for that.

Cheers
@Cloudman999
