### ISSUE TITLE
Thankyou for adding anime, I love using it!

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#133]
Hey Tikipeter thanks so much for adding anime. This is something I've hoped for so long and was pleasantly surprised and shocked you added it! so far so many are enjoying it and it's been a great addition. So thankyou.
You know I like tech and am curious, how did you manage to add it? the selection is so good!

**Comment by Tikipeter** [comment]
Once I discovered that the `anime` keyword in TMDb has over 3500 titles assigned, then I was able to make the lists easily. What was always stopping me was the fact I couldn't use "anime" as a genre filter.

**Comment by hcgiub001** [comment]
lol I actually was meaning to talk to you about how TMDB has a filter for anime tag. I experimented with that filter tag. I basically wanted to get airing today to come up. It was pretty bad if I'm honest with you, I couldn't get the exact movies for today. but still the ones it shows has got lots happy so thank you so much! and great job figuring it out :)

**Comment by Tikipeter** [comment]
There's some good and bad news on the episode groups front.

The bad news is I really can't implement episode groups in a similar way to TMDbHelper. It's just not really feasible for an addon like Fen Light. There are too many moving pieces with relation to metadata.

The good news is I can utilize the episode group information to change which season/episode values are used when scraping. Which is really where their value lies for Fen Light.

For the next update, there will be a new option within Playback Options: "Scrape with Custom Episodes Group Value". If you choose this, you will be presented with the various episode groups that are available for that tvshow. If you select one of them, then Fen Light will attempt to match the current episode with the info, and return new season/episode values if possible.

For example, `Bleach` `S01E121` within Fen Light will return no results, but if we use "Scrape with Custom Episodes Group Value", choose "TVDb Order" from the available groups, then the scrapers will instead search using `S06E12` and we do then get results.

I will only include this implementation in the next update. If you'd like to test it a bit and let me know if it has value, then I'll implement a way to assign a certain group to a certain tvshow permanently.

**Comment by hcgiub001** [comment]
this sounds awesome, of course I would love to test it! my goal was to just get right episode so we can get links, doesn't matter about how it's presented! what can I do?

**Comment by Tikipeter** [comment]
Compare a normal scrape with using the episode group info would be good info.

Step 1 - Choose this:
![screenshot00006](https://github.com/user-attachments/assets/40df1af2-f925-4cda-ac86-778dcc95f5a9)

Step 2 - Choose this:
![screenshot00001](https://github.com/user-attachments/assets/7f369903-0781-4141-bff6-96faf8aa5d2f)

Step 3 - Select 1 of these to use for the scrape values:
![screenshot00002](https://github.com/user-attachments/assets/4fa895aa-5792-4e66-9627-e02a4b2f9fc3)

Just a general check to see if it works well enough to implement a more automatic approach to using the group info. The info for the groups are `GROUP NAME | GROUP TYPE | NUMBER OF EPISODES IN THE GROUP`.

**Comment by Tikipeter** [comment]
There are 7 different types of groups you can get from TMDb, if someone has added them:
![Capture](https://github.com/user-attachments/assets/753b1151-32ce-4937-ae03-0c2c99ac97f0)

**Comment by hcgiub001** [comment]
okay so you'll send the build here? or it's already updated?

I've seen a few examples where it wasn't getting the right data so I will start with them too
like that vampire one

**Comment by hcgiub001** [comment]
their are much more than them, this isn't only an anime issue, you have netflix group also

**Comment by hcgiub001** [comment]
![image](https://github.com/user-attachments/assets/9bee0a40-4e2c-47b5-96f3-fe2c8aa32838)

**Comment by Tikipeter** [comment]
I forgot you had an open issue for this very thing, but remembered the request.

I'll move those screenshots over to your open issue on the topic.
https://github.com/Tikipeter/tikipeter.github.io/issues/114
