### ISSUE TITLE
Can't seem to find any ovas/specials for animes

### ISSUE THREAD

**Issue by Ilikecofe** [Tikipeter/tikipeter.github.io#135]
Hi, I'm using latest version of fen light 1.0.83 and I can't find these episodes/ovas anywhere.
- Attack on titan - The Final Chapters 1 and 2.
- Attack on titan - any ovas

"The Final Chapters" show up on TMDB website as part of the final season but not on any fen list.

![1](https://github.com/user-attachments/assets/f61ca8b4-e5d9-4418-8d55-51326e70e622)

![2](https://github.com/user-attachments/assets/11438190-9089-45f2-a76d-d97e9ed61822)

I also did a quick check with the Konosuba ovas and they don't show up either.

Additionaly, for anime I always get like 1 or 2 sources at best from nyaa, is that an issue with fen or cocoscraper?

Thanks in advance, this addon is awesome.

**Comment by Tikipeter** [comment]
Probably have to turn on "show specials when available".

Anime results come as is. It's not meant to replace a dedicated anime addon.

**Comment by hcgiub001** [comment]
turning on "show specials when available" gives me results thanks
