### ISSUE TITLE
[BUG] Easynews causes Kodi to freeze

### ISSUE THREAD

**Issue by Navios92** [Tikipeter/tikipeter.github.io#137]
Hello,

I have a problem with Easynews links. "Uncached" links, the ones that you still need to wait for to download and unpack on EN server, cause Kodi to completely freeze at the end of the first scraping try.

Here is a log:
https://pastebin.com/fR2TzmDB

I'm using Nvidia Shield Pro 2019. Running the latest Kodinerds nightly. But this also happens on the latest official stable Omega build.

Please let me know if you need more logs or info.
And thank you for the excellent addon!

**Comment by Tikipeter** [comment]
Not really something I can do anything about.

**Comment by Navios92** [comment]
I see.
Can you tell if this is only on my end or a common problem?

Thank you!
