### ISSUE TITLE
[Request] Indicate whether season packs contain chapter info

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/tikipeter.github.io#138]
Hey Peter, I have a small request. When on the source selection page, particularly for TV shows, I think it would be very useful to have some sort of indication as to whether a file/ season pack contains chapters.

I'm currently rewatching breaking bad. Every time I start a new season, I like to source select and pick a season pack containing chapters so that the up next popup functions more accurately. The problem is, I have to check this manually by opening different packs until I find one that contains chapters. I then add that season pack to my debrid cloud and I'm good to go.

If there was an indication of chapters on the infoline of the source selection screen, this would somewhat automate the selection process for me as I wouldn't need to manually open each file, seeing as the info on chapters will be right there on the source selection page. It's a small quality of life improvement that just makes things a little easier. Would you consider adding something like this?

Thanks a lot

**Comment by rizreflects** [comment]
Just to add to this, if we could set files containing chapter info as 'preferred' in the results section of Fen settings, that would be even more ideal. For movies it makes no difference, and would probably be better without checking chapter info at all. For TV shows this could could improve the experience quite a lot I'd say.

**Comment by Tikipeter** [comment]
The only information I can rely on when looking for info like that is the filename of the result.

If the filename were to have any info about whether the file has chapters, then it would be an easy job.

If the filename doesn't have that info, then I'm afraid it is an impossible job.

**Comment by rizreflects** [comment]
Ah that's understandable. Fair enough I didn't realise that was the case.
