### ISSUE TITLE
Shuffled content trakt lists not shuffling in random set shortcut folder

### ISSUE THREAD

**Issue by TheSymm** [Tikipeter/tikipeter.github.io#139]
As the title says, it will just pull up the normal ordered trakt list. It will also only display the original trakt list name and not the user set name that is in the folder.
I am using the Nimbus skin
Thanks for the add-on bro, Keep up the good work.
And may God bless him 🙏

**Comment by Tikipeter** [comment]
Interesting. It is working fine for me (the shuffling aspect) when added to a Shortcut folder when it's set to random.

If the placement of the shuffled list in the shortcut folder is quite old, there may have been a change or two in the last few updates that has stopped it working. If that's the case, remove it and then add it freshly to the shortcut folder and see if that fixes things.

Apart from that I'm drawing a bit of a blank. I'll look over the code in the coming days, but I need to push an update to Fen Light straight away now as it needs compatibility with new scrapers.

**Comment by Tikipeter** [comment]
I forgot to mention the list name being used instead of the folder name.

I'll look into that for next update as well.

**Comment by Tikipeter** [comment]
It all seems to be working now for me.

I'll close this. Open a new issue if it is still not working correctly.
