### ISSUE TITLE
Inaccurate sorting for watched movies

### ISSUE THREAD

**Issue by Omarscomin** [Tikipeter/tikipeter.github.io#14]
Hey Tikipeter! I hope this message finds you well!

I think I may have stumbled across a small bug in the most recent version of FEN Light. Despite my watched content being sorted by "recently watched" in settings, my watched movies are displaying in a completely random order. They were displaying correctly prior to this most recent update to version 1.0.35.

Here's a log, but I'm not sure that it will contain any info that is relevant to this issue:

https://paste.kodi.tv/fulojobido

Kodi version: 20.5
OS: Android

Please let me know if there is anything else that you need from me. Thank you for your time!

**Comment by Tikipeter** [comment]
Thanks for letting me know.

I sure have ballsed something up.

**Comment by Tikipeter** [comment]
Half fixed. I'll have to fix the rest when I get home from work...

**Comment by Omarscomin** [comment]
> Half fixed. I'll have to fix the rest when I get home from work...

Thanks, Tiki! Have a good day!
