### ISSUE TITLE
Offer MDbList Ratings in Extras Window

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/tikipeter.github.io#140]
Hey Peter, as the title suggests, could you possibly bring back the imdb rating to the top of extras? I remember you had this feature in OG Fen. With extras, it seems you've created an interface that grants us direct access to IMDB, and I absolutely love it. The rating on the top would be icing on the cake.

Previously we used to use omdb for this, but this time around I think it would be worth looking into mdblist for api keys instead of omdb. Mdblist updates every 24 hours as opposed to OMDB, which I believe updates monthly.

If you could add this feature back in it would be greatly appreciated. Thanks a lot and keep up all the great work.

**Comment by rizreflects** [comment]
Just to follow up on this, mdblist actually offers ratings that omdb does not e.g. Letterboxd and Roger Ebert. You could add much more than just imdb if you chose to.

**Comment by hcgiub001** [comment]
![image](https://github.com/user-attachments/assets/9939e340-32cd-4b04-a0b0-9227ce89718b)

I get imdb ratings
in accounts put in your omdb key

**Comment by rizreflects** [comment]
> ![image](https://github.com/user-attachments/assets/9939e340-32cd-4b04-a0b0-9227ce89718b)
> 
> I get imdb ratings
> in accounts put in your omdb key

You're right I completely missed that. Thanks for letting me know. I do think it would still be great to have mdblist integration though, whilst maybe still using omdb as a fallback like tmdbhelper does. For newer releases omdb isn't really reliable at all. For example, do you have any ratings for 'Salems Lot' on your end? Omdb doesn't display the ratings for this movie on my side but mdblist does. There's many other examples once you start comparing the 2.

**Comment by hcgiub001** [comment]
I don't only rely on Extra Menu
I'm using Nimbus/FENtastic , these are integrated with mdblist
OMDB doesn't have ratings for Salems lot
https://www.omdb.org/en/gb/movie/267475-salems-lot

**Comment by Tikipeter** [comment]
I've been loath to use any mdblist service, as they are the primary reason trakt had to limit user lists and list sizes.

But fuck it. Nobody seems to care about that. And they do offer better ratings data.

I'll put it on the list.

**Comment by hcgiub001** [comment]
had no idea that was a contributing factor to trakt limiting their service but I see why now. People were tying their mdblist to trakt list
still I'm happy you're adding it. Thank you

**Comment by Tikipeter** [comment]
Yeah, from the horses mouth (when realising he was conversing with the mdblist dev)...

>I just realized you're the dev at mdblist.com 🤦 This is one of the sites allowing users to create massive lists and one of the main reasons we are implementing these limits. I appreciate your project for helping people be creative. Mblist itself has list and item limits, so I think you understand where we are coming from.

https://github.com/trakt/api-help/discussions/350

**Comment by rizreflects** [comment]
Cheers Peter. It's really great what you've managed to do with extras. You've kinda created your own mini skin.

**Comment by ivarbrandt** [comment]
> I've been loath to use any mdblist service, as they are the primary reason trakt had to limit user lists and list sizes. But fuck it. Nobody seems to care about that. And they do offer better ratings data.

I feel you man. To avoid excessive API calls, I set a hard limit on my skins to only pull ratings from the API if they are older than 7 days. That and a solid caching mechanism goes a long way.
