### ISSUE TITLE
[Feature Request] Backport Comet support to Fen

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/tikipeter.github.io#141]
Hello Tikipeter,

I wanted to say really great job on working together with Joe and umbrella dev to bring Comet addon to CocoScrapers, DMM torrents (through Zilean hashlist scraper) is really good.

I know of course that Fen is no longer maintained/developed, and I also know that new CocoScrapers update doesn't "break" anything in Fen when enabling Comet - it simply doesn't provide sources because debrid token is required for Comet request.

Although, I wanted to ask if you'll consider backporting the necessary changes for Comet support to Fen, to make it compatible for rest of original Fen users (me among them, 0 issues with the addon).

From what I saw by comparing the changes, they are in ```sources.py``` and ```external.py``` (that also updates ```correct_pack_sizes``` sources names post Coco update), and they are pretty minimal changes.

Tell me what you think : )

Thank you,
Twilight

**Comment by Tikipeter** [comment]
Cue all the smartass "kodi community" members: "Her Durr I thought Tikipeter wasn't gonna update Fen no more. He just said that for attention. What a loser".

Knowing that's what's coming, I suppose I could update it for the changes.

The thing is, Parental Guidance list in Extras is going to need fixing soon enough, as IMDb are in the process of revamping that page. So really I'd be better fixing that in Fen as well. 

I'd rather wait until I can do both, but maybe will need to do 2 updates if IMDb take too long to implement the change.

**Comment by TwilightMercy** [comment]
Ignore the reddit haters and boomers!

And Thank you very much friend.

**Comment by Tikipeter** [comment]
Done. I'll update it soon.

Parental Guide info fixes will have to wait.

**Comment by TwilightMercy** [comment]
Thank you very much appreciated!

![image](https://github.com/user-attachments/assets/1ec3c886-7a79-4cc1-b8eb-4892699a10fc)
