### ISSUE TITLE
IMPORTANT: Bug with latest Fen Light (v.1.0.85) UPDATE: Fen Light 1.0.86 Now Live

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#143]
Hi all.

Addons ship with bugs all the time. It's what keeps us addon devs in a job. Normally that wouldn't matter; push an update to fix the bug and whistle along your merry way.

Unfortunately, there is a tiny little bug in Fen Light 1.0.85. No worries, you say. Except it's in the updater code.

This means when I next push an update, Fen Light will not be able to complete the update because of the bug. I'm stuck with bugged code installed on everyone's setups.

It's easy enough to get around this.... when I next push a Fen Light release, and it fails to update because of the bug, go into Tools->Update Utilities->Rollback to a Previous Version and install any previous version of Fen Light (v.1.0.84 will be fine). Then, after that has succeeded, select "Check for Updates" and manually update to the new version.

Chalk it up as another "oopsies" on my part. These are going to be more frequent as I age. :)

**Comment by hcgiub001** [comment]
maybe I can learn to forgive you

**Comment by rizreflects** [comment]
No worries, old man.

**Comment by Tikipeter** [comment]
I've uploaded Fen Light `1.0.86` just now.

If you are on version `1.0.85`, then the update will fail. You will need to rollback to version `1.0.84` or earlier, and then update to the new version. Instructions to rollback are in original post above.

Everything will run smoothly after that. I promise. :)

**Comment by hcgiub001** [comment]
I was on version 1.0.85 an was about to rollback to 1.0.84 but on the screen I get this

![image](https://github.com/user-attachments/assets/b1aa5923-bc40-430e-9c88-9723cdb201f4)

So rollback can also go roll forward and no need to go to a previous version.
Thankyou for working so hard and getting this in everyones hands

**Comment by Tikipeter** [comment]
Never even thought about that!

Yeah, that will work fine for sure.
Thanks hcgiub001

**Comment by matthius7** [comment]
> I've uploaded Fen Light `1.0.86` just now.
> 
> If you are on version `1.0.85`, then the update will fail. You will need to rollback to version `1.0.84` or earlier, and then update to the new version. Instructions to rollback are in original post above.
> 
> Everything will run smoothly after that. I promise. :)

Mine just updated automatically from 1.0.85 to 1.0.86 when I booted up Kodi after work. I didn't even notice there were any bugs. Do I need to rollback and skip 1.0.85?

**Comment by Tikipeter** [comment]
No need to roll-back or anything.

Be amazed that you just witnessed a miracle if 85 updated to 86.

Anoint that Firestick.

**Comment by matthius7** [comment]
> No need to roll-back or anything.
> 
> Be amazed that you just witnessed a miracle if 85 updated to 86.
> 
> Anoint that Firestick.

G-streamer

**Comment by xyzfre** [comment]
> > No need to roll-back or anything.
> 
> > 
> 
> > Be amazed that you just witnessed a miracle if 85 updated to 86.
> 
> > 
> 
> > Anoint that Firestick.
> 
> 
> 
> G-streamer

Been seeing good reviews on this device,,32GB of storage.

**Comment by matthius7** [comment]
> > > No need to roll-back or anything.
> > 
> > 
> > > 
> > 
> > 
> > > Be amazed that you just witnessed a miracle if 85 updated to 86.
> > 
> > 
> > > 
> > 
> > 
> > > Anoint that Firestick.
> > 
> > 
> > G-streamer
> 
> Been seeing good reviews on this device,,32GB of storage.

Ethernet gigabit connection. I love it.

**Comment by Tikipeter** [comment]
See. My brain is turning to mush in front of my eyes.

If you had the update set to "Automatic" then this little bug wouldn't matter. It will go through normally.

How long have you had the G-Streamer @matthius7 ?

**Comment by matthius7** [comment]
> See. My brain is turning to mush in front of my eyes.
> 
> If you had the update set to "Automatic" then this little bug wouldn't matter. It will go through normally.
> 
> How long have you had the G-Streamer @matthius7 ?

A couple months and yes I have it set to update at start-up automatically. That's why when I read this after  it just had updated to .86 I was confused AF. But it indeed did.
