### ISSUE TITLE
[Bug] Missing UK MPAA Ratings

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/tikipeter.github.io#144]
I just spotted this and I think it may be a bug. I'm missing the MPAA ratings (set to UK) for quite a few movies. In particular, Rebel Ridge (2024) and Wolfs (2024) both do not show any MPAA ratings when viewed through Fen Light. I checked to see if the ratings are available on TMDB, which they are. I then checked to see if Tmdbhelper is displaying this correctly, which it is. So I feel this may be a bug worth bringing to your attention.

Thanks a lot.

**Comment by Tikipeter** [comment]
OK. I'll look into it.

**Comment by Tikipeter** [comment]
Should be fixed.

I was being a bit too restrictive in a filter I was using, and I don't remember why I was using it.

I'll need to wait and see if anything funny starts happening with it gone.

**Comment by rizreflects** [comment]
I appreciate you looking into this and glad you found the fix. I'll be sure  keep my eye out for any potential problems aswell. If I find any, I'll report back here. Thanks again.
