### ISSUE TITLE
Error Log when streaming real debrid cloud

### ISSUE THREAD

**Issue by natetad** [Tikipeter/tikipeter.github.io#145]
https://paste.kodi.tv/vodakigula

**Comment by Tikipeter** [comment]
Only on one file or multiple?

**Comment by natetad** [comment]
I tried another magnet link of similar size (900 gb) and it didn't play as well. And yeah, it's 900 gb almost 1 tb. It's a magnet link for all episodes of dragon ball Z with active seeders. However, other smaller magnet links do work normally.

**Comment by natetad** [comment]
To add on to this, whenever I click the DBZ magnet link folder in the Real Debrid Cloud Storage in the Fen Light App, it leads to an error message. When I click other magnet links they open the folder and I can see all the episodes in that folder and I can continue to watch.

**Comment by Tikipeter** [comment]
Has real debrid separated the 900gig folder into individual files? It needs to.
