### ISSUE TITLE
ignore filters isn't working when no links found

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#146]
This is more of a cocoscraper issue but I don't think I can reach him so I thought reporting here could help
I'm searching for this anime
"my life is inukai sans dog"
have torrentio bypass filter off
have
![image](https://github.com/user-attachments/assets/429c0eb1-8cbb-4e86-9c42-a9b1019bee67)
search for episode 1 of that anime, you'll get no results then it will scrape with all external scrapers but still no results

now have torrentio bypass filter on
deleted cache and search episode 1
you'll get results. which means it didn't turn of bypass filters?

**Comment by donutmiddles** [comment]
"Ignore All Filters..." refers to the section right below in your screenshot, "Sorting and Filtering" within Fen Light. Nothing to do with CocoScrapers; meaning having that "Auto" won't automatically toggle the bypass title filter in Coco. Comprehension, man...

**Comment by hcgiub001** [comment]
> "Ignore All Filters..." refers to the section right below in your screenshot, "Sorting and Filtering" within Fen Light. Nothing to do with CocoScrapers; meaning having that "Auto" won't automatically toggle the bypass title filter in Coco. Comprehension, man...

I don't appreciate your tone, this is none of your concern and I'll appreciate you stay out of it. I don't think I fully understand how this works, which is why I'm here trying to inform the developer. Also "Retry with all scrapers when no results", what exactly do you think that is relating too? let me use my comprehension since you lack it, it's using referring to coco scrapers, what else do you think is in coco scrapers, have you got it or do I need to do it for you again? you have fitters used in coco scrapers, so maybe it's referring to what I think it's referring to and that's to do with coco scrapers. 
Again stay out of my business, this is second time you've come here to try to belittle me and go educate yourself

**Comment by hcgiub001** [comment]
> "Ignore All Filters..." refers to the section right below in your screenshot, "Sorting and Filtering" within Fen Light. Nothing to do with CocoScrapers; meaning having that "Auto" won't automatically toggle the bypass title filter in Coco. Comprehension, man...

![image](https://github.com/user-attachments/assets/e4240827-cbeb-4633-a1c3-14e64bc9c9b7)

you don't want to see my posts yet you come here only writing on my posts here? this is the filth you are. btw I have good relationships with all devs. It wasn't because of me and kodifitzwell just pm'ed me an hour ago, so you not only lack comprehension but manners and social skills.

**Comment by hcgiub001** [comment]
![image](https://github.com/user-attachments/assets/e36d8c21-37f2-4def-b5c4-3bc82c8e8fc3)
stop harassing me

**Comment by donutmiddles** [comment]
> ![image](https://private-user-images.githubusercontent.com/171574389/375915489-e36d8c21-37f2-4def-b5c4-3bc82c8e8fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTgyNDMsIm5iZiI6MTcyODY5Nzk0MywicGF0aCI6Ii8xNzE1NzQzODkvMzc1OTE1NDg5LWUzNmQ4YzIxLTM3ZjItNGRlZi1iNWM0LTNiYzgyYzhlOGZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMTUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDhmYTA0MWVlMTRiN2E3Mzc0NzU0MmY1OTA2NDA5ZThkZjZlNWE2NjA1OTM4OThmOWYzY2Y1MjBkYTdiNTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3acqLN46fxguPOR1j9qPuYMYecyy9ihHoxgb1shiOGg) stop harassing me

Stop being a jackass and harassing developers.

**Comment by donutmiddles** [comment]
> > "Ignore All Filters..." refers to the section right below in your screenshot, "Sorting and Filtering" within Fen Light. Nothing to do with CocoScrapers; meaning having that "Auto" won't automatically toggle the bypass title filter in Coco. Comprehension, man...
> 
> I don't appreciate your tone, this is none of your concern and I'll appreciate you stay out of it. I don't think I fully understand how this works, which is why I'm here trying to inform the developer. Also "Retry with all scrapers when no results", what exactly do you think that is relating too? let me use my comprehension since you lack it, it's using referring to coco scrapers, what else do you think is in coco scrapers, have you got it or do I need to do it for you again? you have fitters used in coco scrapers, so maybe it's referring to what I think it's referring to and that's to do with coco scrapers. Again stay out of my business, this is second time you've come here to try to belittle me and go educate yourself

You're wrong. End of story.

**Comment by hcgiub001** [comment]
> > ![image](https://private-user-images.githubusercontent.com/171574389/375915489-e36d8c21-37f2-4def-b5c4-3bc82c8e8fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTgyNDMsIm5iZiI6MTcyODY5Nzk0MywicGF0aCI6Ii8xNzE1NzQzODkvMzc1OTE1NDg5LWUzNmQ4YzIxLTM3ZjItNGRlZi1iNWM0LTNiYzgyYzhlOGZjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMTUyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDhmYTA0MWVlMTRiN2E3Mzc0NzU0MmY1OTA2NDA5ZThkZjZlNWE2NjA1OTM4OThmOWYzY2Y1MjBkYTdiNTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3acqLN46fxguPOR1j9qPuYMYecyy9ihHoxgb1shiOGg) stop harassing me
> 
> Stop being a jackass and harassing developers.

lol what is your issue? your the jackass and you look like one too. Do you even realise how much Input and help I do? have you requested a feature that helps others? or done testing? again if you have an issue with me that's fine, but you can leave that outside, this is for creating an issue, if you actually understand anything you'll realise something isn't right, you're not in the position to say what is right or wrong, the developer is. Now go away and kodifitzwell and I are in very good terms and he's just messaged me in PM. You think I harass developers? This issue is trying to find why it's not behaving as you want. 

you're really getting on my nerves, if you harass me again I'll ask mod of reddit to intervene, yeah I'm on good terms with him too

**Comment by rizreflects** [comment]
It would be best if the two of you had no contact going forward.

@donutmiddles It's not upto you to decide who opens issues on github. Peter is more than capable of moderating without your input. You commented on another open issue here aswell. And again I repeat, no one needs you to act as a moderator. I had a read of your reddit response to @hcgiub001 and all I can say is wow. So much toxicity and hate in that comment. I'm surprised it got upvoted like it did, but I guess that shows the sad state of that subreddit currently. Also him showing respect for Peter does not make him a dick-rider. These devs work for free and respect is the least we can give them.

@hcgiub001 Forget about this guy. I for one appreciate your reddit posts. Especially the one about the best remotes! In the future, if this guy contacts you, the best thing to do is ignore and move on. Don't give him fuel for toxicity.

**Comment by donutmiddles** [comment]
> It would be best if the two of you had no contact going forward.
> 
> @donutmiddles It's not upto you to decide who opens issues on github. Peter is more than capable of moderating without your input. You commented on another open issue here aswell. And again I repeat, no one needs you to act as a moderator. I had a read of your reddit response to @hcgiub001 and all I can say is wow. So much toxicity and hate in that comment. I'm surprised it got upvoted like it did, but I guess that shows the sad state of that subreddit currently. Also him showing respect for Peter does not make him a dick-rider. These devs work for free and respect is the least we can give them.
>
No worries, I don't intend to ever interact with him again. Funny enough, my reply here was actually trying to help, believe it or not. People reporting things as "bugs" when they simply don't understand the functionality is a waste of everyone's time. He did the same thing to Ivar Brandt with his latest Nimbus update including add-on version numbers saying that was a bug, when really it was an intended addition by the dev and clearly has a purpose.

In this case, when one is talking about why "disable filters" isn't working when a relevant section called filtering is staring them in the face and thus clearly meaning in the add-on/screen one is looking at, it seems logical thinking is no longer a taught skill these days.

**Comment by hcgiub001** [comment]
> > It would be best if the two of you had no contact going forward.
> > @donutmiddles It's not upto you to decide who opens issues on github. Peter is more than capable of moderating without your input. You commented on another open issue here aswell. And again I repeat, no one needs you to act as a moderator. I had a read of your reddit response to @hcgiub001 and all I can say is wow. So much toxicity and hate in that comment. I'm surprised it got upvoted like it did, but I guess that shows the sad state of that subreddit currently. Also him showing respect for Peter does not make him a dick-rider. These devs work for free and respect is the least we can give them.
> 
> No worries, I don't intend to ever interact with him again. Funny enough, my reply here was actually trying to help, believe it or not. People reporting things as "bugs" when they simply don't understand the functionality is a waste of everyone's time. He did the same thing to Ivar Brandt with his latest Nimbus update including add-on version numbers saying that was a bug, when really it was an intended addition by the dev and clearly has a purpose.
> 
> In this case, when one is talking about why "disable filters" isn't working when a relevant section called filtering is staring them in the face and thus clearly meaning in the add-on/screen one is looking at, it seems logical thinking is no longer a taught skill these days.

I understand I have pushed it with Dev's and constantly ask them request. I've calmed down and was trying to report an issue. on reflection it does seem you are right. I just thought maybe their could be something done if I bought it here. I apologise if  I've spammed in the reddit and even this issue I could have handled it differently. I have no intention to spam dev's or the addon no more so lets just start from a clean slate? :)

**Comment by Tikipeter** [comment]
I'll let Joe know and see what he can do about it. It would be nice to have this filter ignored if rescrape ignoring filters was selected.
