### ISSUE TITLE
[Feature Request] Multiple languages to metadata (plot) just like on Fen but for FenLight

### ISSUE THREAD

**Issue by Phisicz** [Tikipeter/tikipeter.github.io#147]
Just like the title says, i'm requesting to add the ability to change the language of the content plot wether it is a movie, tv show, anime to match the language we have in the settings.

**Comment by donutmiddles** [comment]
This will absolutely never happen as he already said on Reddit.

**Comment by Phisicz** [comment]
> This will absolutely never happen as he already said on Reddit.

![image](https://github.com/user-attachments/assets/716dda44-4ffd-454a-ab1e-e719a5c6dc2c)

**Comment by Phisicz** [comment]
He's the reason why I opened this issue lol

**Comment by donutmiddles** [comment]
> He's the reason why I opened this issue lol

Ah my bad, I thought what you were asking for was the exact thing he says he won't add in what you quoted, but I guess that's not the case.
