### ISSUE TITLE
Bug, Search user list not working

### ISSUE THREAD

**Issue by chrisnikol** [Tikipeter/tikipeter.github.io#148]
Version of Fen Light 1.0.85
OS: Windows 11 v 21H2
Kodi: 21.1

Description of the bug:

The Search user list is not working.

More details:

When a user use the function search user list is not shown any results, not throwing any error message but not shown any results. I first notice that behavion i think 1 or version priur to 1.0.85 but i was too busy to file a bug report.

I checked at a tv box that i also having installation of kodi with Fen Light. There i had the Fen Light 1.0.82 version installed. The search user lists was working as it should. When i updated at 1.0.85 and tried again the search user list not fetching any results. So propably between 1.0.83 and 1.0.85 something broked the function.

Action taken:

I tried to clean all the cache, but this is not changing anything.

-----------------------------------------------------------------------

Here is a small video shown the behavior: https://youtu.be/1P8o0O2BImQ

Log file with the debug option on: https://1drv.ms/u/s!Akob19GUPpoBldczWsOUgFojJl8zmQ?e=ltK0zc

**Comment by Tikipeter** [comment]
Fixed next update.

**Comment by hcgiub001** [comment]
Working on 1.0.86. Awesome work!
