### ISSUE TITLE
[BUG] Trakt userlists search returns no results

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#149]
Hey :)
I'd like to report a bug If I may
Searching for Trakt (Search User Lists) returns no result for any enquiry and returns to page 2 (no results)
not a big priority but thought to report unless others are having same issue
TYIA for looking into this

**Comment by Tikipeter** [comment]
>I'd like to report a bug If I may

You may not.

(Already reported one issue below.)

:) :) :)

**Comment by hcgiub001** [comment]
lol oopsie I should have checked, thanks
