### ISSUE TITLE
[Feature Request]  Additions to anime section 

### ISSUE THREAD

**Issue by wackydan** [Tikipeter/tikipeter.github.io#150]
Hi Peter,

Hope you're doing well. I've been absolutely loving the anime section in fenlight.

I think the only things missing at the moment are the 'in-progress' section and an anime section in 'watchlist'. At the moment we still have to go through in-progress tv shows and tv shows watchlist respectfully to access our anime that would fall under those sections.

These aren't really necessary, so I understand if they aren't priority or not implemented at all, but they would certainly be more convenient.

Once again, I wanna let you know thay I am really enjoying the anime section! Keep up the good work and many thanks!!

**Comment by Tikipeter** [comment]
You can add any menu you like to any of the movie, tvshow and anime sections.

Meaning this is something you can do yourself. Add the in progress and watch list sections, or any other menu or list, anywhere you want.

Take a look in Tools->Tips for Use->Edit Main Menus to read up on how.

**Comment by CocoJoe2411** [comment]
You can add any item from one section to another section.

i.e. You can add the In Progress and Watchlist menus into the Anime section.
