### ISSUE TITLE
Create a path so skins can make use of Anime Search 

### ISSUE THREAD

**Issue by Better-Red** [Tikipeter/tikipeter.github.io#152]
Hi Peter,

Thanks for what you do with FEN Lite (and FEN). This request comes via a request I made on ivarbrandt's GitHub for Nimbus and hopefully FENtastic. Can you create a path so skins can make use of Anime Search?

Thanks again.

**Comment by Tikipeter** [comment]
This should work fine. No need to create any path.
```
plugin://plugin.video.fenlight/?mode=build_tvshow_list&amp;action=tmdb_anime_search&amp;query=$INFO[Skin.String(SearchInputEncoded)]
```

**Comment by Better-Red** [comment]
Thanks, I'll let him know.

**Comment by Better-Red** [comment]
Ivarbrandt has incorporated it into Nimbus and it will be part of the next release. Thank you again.
