### ISSUE TITLE
[Q&A / Feature Request] A custom property for dynamically changing titles for 'Recommended' widgets

### ISSUE THREAD

**Issue by OfficerKD637** [Tikipeter/tikipeter.github.io#153]
Hi Tiki!

Hope you're doing well!

The recommendation system in Fen Light is truly best in class! The new 'Because you watched' random list is sooo awesome!! With both IMDb and TMDb being available (and just a click away), it is a game changer!

Currently, when you add the 'Random Because You Watched Movies/TV Shows' as a widget path it shows a static title.
Would it please be possible to make it a dynamic title? Like 'Because You Watched "NAME OF THE MOVIE/TV SHOW"'? 
And can that property be passed into an $INFO label?
I got this idea from $INFO(Window.Property(umbrella.moviesimilarlibrary)

Thank you so much!!

**Comment by Tikipeter** [comment]
`$INFO[Window.Property(fenlight.Random Because You Watched Movies)]`

Same idea for TV Shows.

The idea here is that any random list where the source of the list will change I.e. Random Genres, Random Trakt Liked Lists etc there will be a window property made for it that you can use.

It will always follow the same principal:
```
$INFO[Window.Property(fenlight.[**FULL NAME OF LIST**])]

The list name used must honor capitals and spaces. It needs to be exactly the same as the list's name.

**Comment by OfficerKD637** [comment]
Thank you so much! That worked perfectly!

One last question/request: Why does Fen Light default to the static list name (i.e. only ' Random Because You Watched Movies' without the name of the movie) when adding the path to a widget? Wouldn't the dynamic title be cooler?

I understand that some people might rename their widgets to 'Recommendations' or something else.
But wouldn't it be nice to have the dynamic title as default?
I am not aware of all the technical intricacies behind this so I apologize in advance if this is a silly question.

Thank you once again!

**Comment by Tikipeter** [comment]
That wouldn't leave you guys much to do.

**Comment by OfficerKD637** [comment]
Hahaha thanks Tiki!

**Comment by Tikipeter** [comment]
In all seriousness, I had a look when I got home from work and it's not really possible. It wold need to be set as the listitem label, and that doesn't show when not making a widget.

I'll have another look when I get more time.

**Comment by OfficerKD637** [comment]
Thank you! You're the best! I'm just glad to know that custom properties for Random lists already exist! This was like an easter egg to me since I couldn't find this info anywhere else. Thank you so much!
