### ISSUE TITLE
Any support requests will need to come through this Issues page.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#154]
Hi guys.

I'll be taking a break from the addons4kodi subreddit, as it seems lately that it's becoming a Fen/Light support sub.

Way too many issues being dumped there with no follow up or logs etc.

It must be annoying to users of that subreddit always seeing Fen/Light support threads.

As such, for a while I won't be spending any time there dealing with support requests. Hopefully it will die down and get back to normal soon enough.

**Comment by hcgiub001** [comment]
I don't even hard to work on fixes and I realised I'm getting sick of that thread and the people. I started doing other things and to hell with everything else. I just don't have the time Tazoz to get a real forum where all devs can have their own space so you don't have to constantly regurgitate the same advice and pin your own threads you feel are needed. I also think you're close to enjoyment burnout so a rest will do you good. like 6 months rest while you fix issues and what's left of feature requests. then close issue section for 3 months.
