### ISSUE TITLE
(Bug) collection 

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/tikipeter.github.io#158]
Good day Peter,

I'm noticed when you click on a movie that belongs in a collection, and it opens the collection that it stays lay. It's with all the movies in a collection.

Came after the update.

You might be able to take a look at this if you have time.

Thanks in advance

**Comment by Tikipeter** [comment]
Good day to you too.

What do you mean by " it stays lay"?

Check your settings for Settings->Features->Special Open Actions. Make sure the Movies setting is set the way you wish it to be.

**Comment by hcgiub001** [comment]
Can confirm after the update, I'm getting same bug

When I set the option to "Open Both" (Extras and movie set) I get a blank

![Screenshot (663)](https://github.com/user-attachments/assets/ccab4385-ad99-4110-a560-9653eaef4de5)

![Screenshot (664)](https://github.com/user-attachments/assets/dbd6b831-f225-4a77-ac11-8ac37086e0f4)

setting to "Open Set", I get same result result

Setting to "open Etras", I get Extras menu to popup as expected

**Comment by Tikipeter** [comment]
Really strange.

This is fixed in my latest test zip, but I didn't knowingly do anything to fix it.

If you want to use that,  I'll put a zip off it here in a minute.

**Comment by Tikipeter** [comment]
[plugin.video.fenlight-1.0.91b.zip](https://github.com/user-attachments/files/17577408/plugin.video.fenlight-1.0.91b.zip)

**Comment by djdirty60** [comment]
For me it's solved, it works again.

Thanks for the quick fix and super addon

**Comment by hcgiub001** [comment]
Working for me too using 1.0.91b . Thank you for quick response
