### ISSUE TITLE
Possible improvement to the Trailer function in Fen Light to load 'Official Trailer' like Fen did instead of short clips or teasers

### ISSUE THREAD

**Issue by jeromedevine** [Tikipeter/tikipeter.github.io#162]
Hello, I use the Trailer function quite a lot and I noticed that in Fen Light most often when I press 'Trailer' it loads up a random short or a teaser rather than the 'Official Trailer'. For example the movie 'Wolfs' happens like that when I press Trailer - it loads a 30 second portrait shorts clip. I saw that in the 'old' Fen it loads up the 'Official Trailer' at the top of the extras Trailer videos and it was convenient to press on it directly. Please, could the Fen Light Trailer function be programmed to load up the 'Official Trailer' or videos with the 'Official Trailer' words in their title? I think it would be more relevant to show it for Trailer.

Thank-you for what you are contributing. It makes me happy to go through the movies and TV shows through the addons you created. :)

**Comment by Tikipeter** [comment]
Should be sorted out next update. You will need to clear the meta cache.
