### ISSUE TITLE
Open movie set is showing up blank white box. Can't select the movie.

### ISSUE THREAD

**Issue by octavioromo1** [Tikipeter/tikipeter.github.io#163]
Hey there! Everything's had been working great through all the updates, I've had my setup dialed in for a while. But in this latest update when I go to select a movie, for example Scream. It wants to pull up the Scream movie collection but it then only shows a white box after a few seconds. 

Selecting a movie that is not in a collection will work just fine. 

I've got the nimbus skin. 
When I click the white box it takes me directly to Fen.

When in Fen, if I do search>> movies>> Scream>> Same white box. 

I have to turn off the option for open movie set in order to play the movie. 

I'm on the latest version of all my installed apps. Only YouTube, Fen and Nimbus.

Just to test I rolled back to I think .88 version and it started working again, I updated to the latest and it went back to broken.

Let me know if there is any more info I could provide to assist in tracking this down.

Thanks for all your hard work have a great night!

**Comment by hcgiub001** [comment]
hey, this is a known issue and an update is coming meanwhile you can use the latest test zip provided by Tikipeter 
> [plugin.video.fenlight-1.0.91b.zip](https://github.com/user-attachments/files/17577408/plugin.video.fenlight-1.0.91b.zip)

(the issue was raised yesterday here
https://github.com/Tikipeter/tikipeter.github.io/issues/158)

**Comment by Tikipeter** [comment]
Still have absolutely no idea why this happened, and why it fixed itself. I'll have a look tonight when I wake up. :)

**Comment by hcgiub001** [comment]
update is working good, no problem, thanks for the update.
