### ISSUE TITLE
Inconsistant scraping

### ISSUE THREAD

**Issue by naudski** [Tikipeter/tikipeter.github.io#164]
Hi Tikipeter,

Hope you are doing well.
I noticed some inconsistancy when scraping sources. Sometimes Fen Light doesn't return any RD links, only Easynews links. It is not the Coco addon that is causing this.
When I clear the scraper cache it works for a short while. I think this issue started with version 1.0.90.
Thanks for your hard work!!

**Comment by Tikipeter** [comment]
RD issues. Not addon related.

**Comment by naudski** [comment]
Check!

**Comment by hcgiub001** [comment]
> Check!

are you giving an order to Tikipeter? 
I was about to ask questions about what inconsistencies you are talking about so we can "check" , but I don't like the tone you used

**Comment by naudski** [comment]
It was just a check to confirm his answer. Seams plausible that it is a RD issue. I didn't consider it.

**Comment by Tikipeter** [comment]
Temporary fix for this in next update.

Hopefully RD fixes their API soon.

**Comment by naudski** [comment]
Thanks very much Tikipeter!
