### ISSUE TITLE
[COLLABORATION] making Zilean instance public

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#166]
Hey Tikipeter I spoke with funkypenguin

> Hey :) good to connect - yes, happy to work together!
> 
> Thinking that a kodi addon scraping Zilean directly would be more resource-efficient than doing it via Comet too :)"
> 
> Where’s the best place to discuss with devs? Is there a discord?
> 
> "ElfHosted discord  - we could setup a channel to collaborate if that works…"

Would you have the time and interest? I'd like to see the three of you with Umbrella_dev and kodfitzwell get on good terms so having a project you 3 can work on would be good :)

**Comment by Tikipeter** [comment]
I think UD has reached out to Cocojoe.

We have nought to do with the scrapers, apart from providing some guidance when asked for. CocoJoe is likely not too keen to work with anyone else.

**Comment by hcgiub001** [comment]
I understand, you did mention before you don't deal with scrapers, I'm still not sure what funky penguin wanted , maybe I think it's more than what needs to be done. Thanks for responding , I'm happy for the issue to close for now. I'm still keen to get zilian open so will try to see where we are at and report back so you guys can do your magic again like before :)

**Comment by TwilightMercy** [comment]
Public Zilean host:

```
self.base_link = "https://zilean.elfhosted.com"
self.movieSearch_link = '/dmm/filtered?ImdbId=%s'
self.tvSearch_link = '/dmm/filtered?ImdbId=%s&Season=%s&Episode=%s'
```

**Comment by hcgiub001** [comment]
> Public Zilean host:
> 
> https://zilean.elfhosted.com/swagger/index.html
> 
> ```
> self.base_link = "https://zilean.elfhosted.com"
> self.movieSearch_link = '/dmm/filtered?ImdbId=%s'
> self.tvSearch_link = '/dmm/filtered?ImdbId=%s&Season=%s&Episode=%s'
> ```

no way, this is now public? I get 404 if I access the site, is that supposed to happen? great news that you guys been working on this, would love more information :D

**Comment by TwilightMercy** [comment]
Elfhosted Kodi devs dedicated discord channel:

https://discord.gg/funky-penguin-396055506072109067

**Comment by TwilightMercy** [comment]
@hcgiub001 
Can you please delete the link to my GitHub profile in your reddit post? Many thanks
