### ISSUE TITLE
Flatten TV Shows with Multiple Episodes Airing on The Same Day

### ISSUE THREAD

**Issue by rowel07** [Tikipeter/tikipeter.github.io#167]
I really like Fen Light Trakt Calendar but I hope that there is an option to flatten TV shows with multiple episodes airing on the same day.  Instead of showing the whole season's episodes, it will show only the first episode. Thank you 
![IMG_20241105_095517](https://github.com/user-attachments/assets/896f52de-c817-43e2-a785-efcb9e78e844)

**Comment by rowel07** [comment]
When 'Sort Airing Today to Top' is enabled, I wish it would only apply to Next Episodes and not to the Trakt Calendar.

**Comment by Tikipeter** [comment]
>When 'Sort Airing Today to Top' is enabled, I wish it would only apply to Next Episodes and not to the Trakt Calendar.

It does only apply to Next Episodes. The Calendar list will always have the shows airing today at the top because they are the latest in the calendar.

**Comment by Tikipeter** [comment]
Settings->Single Episode Lists->Trakt Calendar->"Flatten TV Shows Airing on Same Day" added for next update.
