### ISSUE TITLE
An observation about EasyNews.

### ISSUE THREAD

**Issue by Guguloi** [Tikipeter/tikipeter.github.io#169]
Hello Peter,

First thank you for your work, I really enjoy it.
Second about playing sources from EasyNews. As you know there are 2 situations:
- it plays right of the bat 
- it fill that progress bar to the red zone and KODI freeze.

What I saw for a while now. If I force close KODI, then launch it again and Clear all cache Excluding Favorites before I play the same EN source it starts right of the bat this time. It happens 100%.

Dunno if it's a coincidence or it has something to do with some particular cache but for me it works.
Usually EN is a backup for RD but sometimes it finds shows which aren't on RD. Now I'm watching King & Maxwell show and I have only 3 EN sources so after each episode I must force close KODI, clear cache and then I can watch next episode.

PS. I did those settings (http2, ipv6 and curl) in advancedsettings.xml but no help.

**Comment by Tikipeter** [comment]
For me, if it doesn't play first time, it tries again and succeeds the second time. So there aren't 2 situations. There are 3. I don't suffer from the freeze on retry. It works great.

Look, this is how Easy news has always been, and likely how they will always be when it comes to http streaming. They don't have every file on Usenet immediately ready to stream.

Your choices are to put up with it, stop using Easynews, or stop using Fen.

I can't keep having the same conversation for 7+ years about the same thing. 

If it doesn't work for you; stop using it.
