### ISSUE TITLE
Individual season ratings not showing

### ISSUE THREAD

**Issue by Rinicko100** [Tikipeter/tikipeter.github.io#170]
Hello,

I was wondering if you could take a look at this issue.. The season ratings for individual seasons are not showing on Arctic Fuse 2. It only shows the ratings for the tvshow
![Kodi_20241107_165033.png](https://github.com/user-attachments/assets/b7233d9b-fef8-4adf-82e7-0fa2fe0a9771)

It looks like this on tmdb helper
![Kodi_20241107_165121.png](https://github.com/user-attachments/assets/1c1d5ad9-3b09-40ce-a73a-39e9ee8c74e2)

It works normally on Fenlight episodes
![Kodi_20241107_170050.png](https://github.com/user-attachments/assets/c91f7b24-7bfb-4685-b4f0-d28e05c4d559)

I think it might be a similar situation to the previous episode count issue that was fixed, but I'm not sure, though. Could you please have a look at this? Many thanks.

**Comment by Tikipeter** [comment]
I don't have access to that unless I specifically make an extra call to TMDb, which I don't need to do to get the majority of season data.
