### ISSUE TITLE
Skinning - static list content

### ISSUE THREAD

**Issue by loggio** [Tikipeter/tikipeter.github.io#174]
Hi there, 

I've modified the default skin to display properly in PAL 4:3 resolution so I can use the addon when working on my old crt TVs.

One thing I would like to request is a workaround for your static list content in the settings windows to point to a separate file or separate includes.xml

This is so that any changes or content that you make to these windows does not need to be added/maintained across all skins. Is this possible?

Also, there is currently no way to select a skin on your addon, do you plan to add this option?

**Comment by Tikipeter** [comment]
Addons don't have access to many skin engine features. Unfortunately using includes is one of them.

**Comment by Tikipeter** [comment]
I'll include an alternative way of achieving what you want in the next update. I'll have to make the content each time the settings window is opened.

That should allow you to edit the xml and not worry about inserting any new settings when they're added.

**Comment by loggio** [comment]
> I'll include an alternative way of achieving what you want in the next update. I'll have to make the content each time the settings window is opened.
> 
> 
> 
> That should allow you to edit the xml and not worry about inserting any new settings when they're added.

Perfect. Thank you!

**Comment by loggio** [comment]
Hi, thanks for integrating this. Although it kind of broke my skin. might be an easy fix on your end though? 
structure of my skin:
Skins/Default/PAL/settings_manager.xml

is there any way you can have your code generate settings list content for the following folders ? 
that should cover all potential resolutions for skinning? 
Skins/Default/1080i/settings_manager.xml
Skins/Default/720p/settings_manager.xml
Skins/Default/PAL/settings_manager.xml
Skins/Default/NTSC/settings_manager.xml
Skins/Default/xml/settings_manager.xml

**Comment by Tikipeter** [comment]
Do you have skin files for all the xmls Fen Light provides?

Do the other skin files work from this PAL folder? I don't see how they could have.
