### ISSUE TITLE
Enhancement - Unwatched Count in Next Episodes List

### ISSUE THREAD

**Issue by Jcloak** [Tikipeter/tikipeter.github.io#175]
Hello, thanks for all the great work on this add-on. I just wanted to suggest one feature that I think would be useful for many people.

Many skins have implemented functionality to display the unwatched episode count in mixed content lists such as "Next Episodes" as long as the add-on includes the "UnwatchedEpisodes" property.

It is a useful indicator to quickly see how many new episodes are available to watch when viewing the "Next Episodes" list.

Thanks for your consideration.

**Comment by Tikipeter** [comment]
>Many skins

Could you provide an example of such a skin. Non Jurial made if possible.

**Comment by Tikipeter** [comment]
Doesn't matter. I enabled AF2 and saw what was going on.

FYI, you do also need to set a value (arbitrary) for `watchdepisodes` as well as `unwatchedepisodes` (in case you want to request this from any other devs).

I'll include this in the next update. I'll make a note here if it ends up being a setting to enable this.
