### ISSUE TITLE
Set views by manual input.

### ISSUE THREAD

**Issue by loggio** [Tikipeter/tikipeter.github.io#176]
As per title, is there a way you can add the option for the user to manually input the view id number?

Reason, I use a skin that has fixed views and doesn't allow me to cycle view types, it's all set via expressions and visibility conditions in the skin. However this is problematic as your app after a fresh install forces the wrong view type for season and episode views for my skin and I'm unable to cycle to the correct view type when setting views. 

In Fen I was able to edit the skin settings file manually to overcome this but for fenlight I've had to temporarily create a keyboard shortcut in kodi to force select  next viewtype to set the correct view in fenlight settings. 

Not a major issue for me as I know what I'm doing, but Would be nice if I could just type view 58 instead of default 50 for arguments sake.

**Comment by Tikipeter** [comment]
What skin??

You can turn off Fen Light setting views. So as to allow the skin to control it instead.

Somewhere in the Content tab of the settings.

If you do that before entering a container for media it should allow the skin to do what it wants.

**Comment by Tikipeter** [comment]
Done for next update. Toggle "Manually Enter Viewtype Values" in Settings->Content->General. Appears so long as you have "Control Viewtypes Within Addon" enabled.
