### ISSUE TITLE
Upcoming Fen Light Updates...

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#178]
Hi all.

I am planning on pushing an update tomorrow for Fen Light.

I feel it would be beneficial for users to DOWNLOAD AND STORE the zip of that update when it is pushed. 

I also feel it would be beneficial for users to download and store any subsequent updates moving forward.

Also download and store a zip of any latest external scraper updates that you may be using.

Be prepared, in other words

**Comment by TwilightMercy** [comment]
Holy Moly

**Comment by TimboZero** [comment]
Would you care to clarify this for us please TP ?

**Comment by Tikipeter** [comment]
Keep a copy locally of each of the latest zip files for Fen Light and whatever external scraper you use. You can install the addons from the zip files if needed.

**Comment by TimboZero** [comment]
Sorry, is there a reason that is shareable or ‘just as a backup’ logic?
Thanks

**Comment by StarBleu1** [comment]
> Sorry, is there a reason that is shareable or ‘just as a backup’ logic? Thanks

Most likely workaround for the  latest realdebrid anti piracy measures.

**Comment by TimboZero** [comment]
Ok thank you TP, keep up the excellent work as well all love it.

**Comment by Chilly167** [comment]
@Tikipeter can you add Torbox to the list of repos we can add inside of fenlight since RD is down, seen a lot of users migrate there and speaking to the admins you would need to integrate torbox auth in like rd or other premium services ?

**Comment by Tikipeter** [comment]
> Sorry, is there a reason that is shareable or ‘just as a backup’ logic? Thanks

I'm taking some time to think things through. So nothing shareable.

> Most likely workaround for the latest realdebrid anti piracy measures.

Nothing to do with that. 

> @Tikipeter can you add Torbox to the list of repos we can add inside of fenlight since RD is down, seen a lot of users migrate there and speaking to the admins you would need to integrate torbox auth in like rd or other premium services ?

Not likely.

**Comment by TimboZero** [comment]
> > Sorry, is there a reason that is shareable or ‘just as a backup’ logic? Thanks
> 
> I'm taking some time to think things through. So nothing shareable.
> 
Noted, thank you mate. Take care :)

**Comment by Tikipeter** [comment]
Latest update is live. It does NOT address any issues related to Real Debrid. It's just releasing the changes made up to this point.

Remember to keep a local copy of releases moving forward.

**Comment by TwilightMercy** [comment]
https://github.com/TheBeastLT/torrentio-scraper/issues/305

Theoretically, possible solution (World wide Fen Light users that successfully able to download an "uncached" torrent from sources list (gray colored) - the torrent's hash will be added to cached hashes DB. But requires a server for Kodi clients to communicate with.

**Comment by dabutch3r** [comment]
Thank you for all you have been over the years. Hats off to you and your work.
