### ISSUE TITLE
Fen light error: check logs

### ISSUE THREAD

**Issue by classicclown** [Tikipeter/tikipeter.github.io#179]
<img width="1440" alt="Screenshot 2024-11-22 at 13 19 47" src="https://github.com/user-attachments/assets/2c47f941-ff36-4f86-8010-4f24a65dd6f2">
Hi Team,
I installed FenLight on Kodi on my mac but I am unable to open it. As soon as I try open fen light I get an error telling me to check logs. I hope I'm submitting this correctly so here is the link to kodi logs:
https://paste.kodi.tv/okatihaqed.kodi

I attached a screenshot as well.

Thanks!

**Comment by Raydonman** [comment]
Same problem on my fire cube, Kodi 21.1. Selecting anything shows available results and the shows no results. Attempting to update gives the error shown above.

**Comment by Tikipeter** [comment]
You're using Kodi 19.

Fen Light is not compatible with Kodi 19.

Use a different addon.
