### ISSUE TITLE
FEN updated for old time's sake. Will support RD.

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#182]
I just updated my old friend FEN for the final time by request.

Version `3.5.01` will have the Real Debrid fixes and also disabling of the update manager.

This means there is no longer a reason to delete the addon if you're sentimental and are still using it.

**Comment by anguisviridis** [comment]
I really appreciate your work - thank you very much!

**Comment by soopacrucial** [comment]
Silly question: where can I find/save a zip file of the final version of FEN like the FENLIGHT one in https://tikipeter.github.io/packages please?

**Comment by Tikipeter** [comment]
The zips are here, under the code tab.

**Comment by soopacrucial** [comment]
That's awesome, thanks, got them now. I'm not at home so was worried I was going to miss my chance! FEN forever club! :)
