### ISSUE TITLE
When resolve fails on first result it skips over the second result and tries the third

### ISSUE THREAD

**Issue by bbviking** [Tikipeter/tikipeter.github.io#183]
In resources\lib\modules\sources.py in the play_file function there does appear to be a slight issue in this line:

`items_next = results[source_index+1:source_index+trailing_index]`

It adds one to the source_index presumably to ensure that the first source is not included in subsequent resolve attempts. But a few lines earlier the first source is removed in the line

`results.remove(source)`

Meaning that the source_index now represents the index of the next source it should attempt. So I was hoping if possible, that line could be changed to the below before FEN Light is fully discontinued:

`items_next = results[source_index:source_index+trailing_index]`

Apologies if I'm misunderstanding how this function is intending to work, I'm not super familar with the ins and outs of FEN Light's code but I just noticed this issue when I was attempting to play something and removing the +1 fixed it for me.

**Comment by Tikipeter** [comment]
Sure thing. Thanks for that.
