### ISSUE TITLE
Login attempt by someone from Germany while using Fenlight+ All Debrid

### ISSUE THREAD

**Issue by shanestonk** [Tikipeter/tikipeter.github.io#185]
Recently im getting the email from All Debrid while using kodi+ fenlight+ cocoscrapper. With stremio im not getting this email attempt login from germany.

![image](https://github.com/user-attachments/assets/ccea40c0-a597-4990-a52f-3723a01c6dc1)

**Comment by Tikipeter** [comment]
I'd be inclined to Block it if it isn't you.
