### ISSUE TITLE
[2.0.03] Another quick update to fix a couple of issues

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#186]
Needed to fix a couple of more issues for a few people with the last update.

The fixes...
- Fixed Reviews in Extras Menu. Clear IMDb cache and restart Kodi to refresh new data.

`2.0.03` is now uploaded and is only available by installing from zip. You can do this using the `tikipeter.github.io/packages` source you have made in Kodi's File Manager. The same process as when you first installed Fen Light.

Anyone not on `2.0.01` or `2.0.02` will be able to update through the addon itself. But `2.0.01` removed that capability, so use the file manager source.

The fixes...
- Fixed Reviews in Extras Menu. Clear IMDb cache and restart Kodi to refresh new data.

**Comment by Tikipeter** [comment]
I'll reset the 48 hours.

That's 2 days people. Grab the zips you want.

**Comment by Tikipeter** [comment]
It happened again. `2.0.03` live.

**Comment by sasagr** [comment]
![IMG_0032](https://github.com/user-attachments/assets/f4df0e12-5d5d-4c96-b753-dd9763c11e1b)

when I click on the 2.0.03 zip link

**Comment by sasagr** [comment]
Ok now. Thanks for everything mate!

**Comment by Tikipeter** [comment]
Did you add `/packages`?

**Comment by sasagr** [comment]
> Did you add `/packages`?

Yes. When I was clicking on the zip file I was getting the 404 message for some reason but now it is ok![image](https://github.com/user-attachments/assets/ff200284-0f64-477a-96ac-57904c68f185)

**Comment by bbviking** [comment]
> > Did you add `/packages`?
> 
> Yes. When I was clicking on the zip file I was getting the 404 message for some reason but now it is ok![image](https://github.com/user-attachments/assets/ff200284-0f64-477a-96ac-57904c68f185)

It was briefly deleted looking at the commit history before being reuploaded. You probably attempted to download it after it had been deleted.

**Comment by gfedc28** [comment]
Hello Tikipeter, I just wanted to inquire if there's any possibility for a similar update to the original Fen to restore the ability to browse packs.  Either way I want to thank you for everything and I wish you well.

**Comment by gfedc28** [comment]
Hello Tikipeter. I just wanted to inquire if there's any possibility of a similar update for the original Fen that would restore the ability to browse packs? Either way thank you for everything and I wish you well.

**Comment by minicoz** [comment]
@gfedc28 no fen will not be updated anymore. This is the Get this latest package of Fen Light or loose it forever.

**Comment by minicoz** [comment]
@Tikipeter do you have any guides/advice on how to develop a Fen Light fork and add a Torbox integration? I'm interested in maybe adding it on just in case RD gets completely nuked. 

Torbox is located in South Africe while Real Debrid is in France so less copyright issues. 

Right now im just downloading the 2.0.03 zip, then opening up the files in an IDE and trying to develop a new Torbox_API. Do you have any advice on how to test locally? Are there any steps to zipping up the code and setting up a release? I have never developed on Kodi before so just curious.

**Comment by gfedc28** [comment]
@minicoz Are you certain?  He just updated the original Fen two days ago and I'm not asking for a new feature I'm simply inquiring about a fix for an old feature that no longer functions, the same fix that was just pushed to Fen Light.

**Comment by YungZanji** [comment]
Thanks for the update, everything seems to be working for Real Debrid. However All Debrid Seems to have issues showing results its all coming up as greyed out even though it is cached on AllDebrid.  I believe anther user was having the same issue any advice on how to fix it. I tried reverting to 1.0.94 But that didn't fix it. Thanks

**Comment by TwilightMercy** [comment]
> Thanks for the update, everything seems to be working for Real Debrid. However All Debrid Seems to have issues showing results its all coming up as greyed out even though it is cached on AllDebrid. I believe another user was having the same issue any advice on how to fix it. I tried reverting to 1.0.94 But that didn't fix it. Thanks

This is global issue. they blocked their "instant"-alike API cache check like Real Debrid.

**Comment by TwilightMercy** [comment]
> Hello @Tikipeter. I just wanted to inquire if there's any possibility of a similar update for the original Fen that would restore the ability to browse packs? Either way thank you for everything and I wish you well.


[plugin.video.fen-3.5.02.zip](https://github.com/user-attachments/files/17910123/plugin.video.fen-3.5.02.zip)

![image](https://github.com/user-attachments/assets/bee826b5-b68d-452e-8495-377fb6464599)

**Comment by Tikipeter** [comment]
Geez, I can't thank you enough Twilight.

I might have a look at the reviews in the Extras menu ad get them sorted as well for this release.

**Comment by Tikipeter** [comment]
Review and Parental Guide fixed as well.

**Comment by YungZanji** [comment]
> > Thanks for the update, everything seems to be working for Real Debrid. However All Debrid Seems to have issues showing results its all coming up as greyed out even though it is cached on AllDebrid. I believe another user was having the same issue any advice on how to fix it. I tried reverting to 1.0.94 But that didn't fix it. Thanks
> 
> This is a global issue. They blocked their Instant availability API, similar to Real Debrid.
> 
> And after them - [DebridLink](https://debrid-link.com/api_doc/v2/introduction) ![image](https://private-user-images.githubusercontent.com/29895680/389728919-5ecd9314-fd4f-4f74-8186-1248a0b9ed1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDIzOTQsIm5iZiI6MTczMjYwMjA5NCwicGF0aCI6Ii8yOTg5NTY4MC8zODk3Mjg5MTktNWVjZDkzMTQtZmQ0Zi00Zjc0LTgxODYtMTI0OGEwYjllZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA2MjEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZWFkYjI5NmI3OGYyZGQ1MWRjMzhmNDhjNzM4OTY0MDA4N2U3OWNiOGRhMjcyZDg0YmI0OTVlODkzNDE0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.61u4xlIvrqzl8TUrCU8tO1UuKxHuTN2LKGNqUqoX1Pc)

Did they announce this for All Debrid as well? Where can I follow along?

**Comment by gfedc28** [comment]
@TwilightMercy @Tikipeter Wow you guys are on it, thank you for 3.5.02!
