### ISSUE TITLE
Trakt Recommended Movies/TV Shows got broken in 1.0.9.4 onwards

### ISSUE THREAD

**Issue by bbviking** [Tikipeter/tikipeter.github.io#187]
It looks like some part of the 1.0.9.4 update broke the recommened movies/tv shows pages. I haven't yet been able to investigate it myself, but I'm hoping it's a one line fix.

I have tried reauthenticating and clearing trakt cache, but unfortunately that didn't seem to fix the issue. 

It would be nice to have it fixed before fen light is truly finished, but it's not the end of the world if you want to leave it as is.

**Comment by Tikipeter** [comment]
It's working for me.

**Comment by bbviking** [comment]
Ahhh you're right. You confirming it worked for you made me realise what it is. 

I added Recommended Movies/TV Shows as a custom menu item on Movies/TV Shows. Recreating the custom menu items has them working now, I forgot that I had added them myself and they weren't always there.

Sorry about that.
