### ISSUE TITLE
News for 27/11/2024

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#189]
Hi guys.
Seeing as so many variables are still moving and continue to hang up in the air, it appears my plans have, briefly, been somewhat upended.

My retirement in under a day needs to be put on hold. The plan is until the end of this week. That should give enough time to see where things have settled and what the final state of Fen Light will be.

Again, due to the current situation, updates are coming thick and fast with both Fen/Light and Umbrella. I don't think this is really avoidable, so I have re-enabled the Update Manager in Fen Light on the next update (2.0.04 NOW LIVE). In doing this, I decided to keep it enabled for when I retire, and I have added settings for you to enter a github username and a github repo address. These settings are for if someone wishes to do some development of Fen Light and you want to receive their updates. You can enter their username and the name of the repo and Fen Light will look for updates in that new location. The dev will need to structure their repo so as it matches the code within updater.py. AD is also fixed.

Fen will also receive an update (3.5.02 NOW LIVE). This update includes fixes to pack browsing/downloading and a sequential playback fix previously only applied to Fen Light. You guys need to thank TWILIGHTMERCY for porting these changes over. I also added the fixes for Parental Guide and Reviews for Fen's Extras menu. AD is also fixed.

A list of the changes...

FEN LIGHT:
- AD fix.
- Reinstate Upload Manager, but I have disabled the Rollback Feature.
- Added settings General->Manage Addon Updates... "Github Username" & "Github Repo Address". In these, you can enter the username and repo address of another dev who may wish to push a Fen Light release. Devs will need to check the code within updater.py and make sure their repo is structured correctly. Basically repo_name/packages/CONTENT.

FEN:
- Fixes taken from Fen Light 2.0.02: Big thanks to Twilight for porting these fixes.
- Fix for browsing/downloading pack results through RD.
- Quick fix to correct sequential playback.
- Fix Parental Guide and Reviews in Fen Extras window.
- AD fix.

Since the Update Manager has been re-enabled in Fen Light, there is not going to be a reason to post an Information Issue like this for every update moving forward, unless specifically necessary. There will likely be 2 or 3 updates in the coming days, and then I can retire. :)

EDIT: I forgot.... because I'll be keeping the Update Manager enabled, I will not be able to completely delete this Github account. It opens users up to being susceptible to an imposter opening a Github account with my name, and pushing an update that could be dangerous.

So the repo can be deleted, but not the entire github account.

**Comment by Bangtedd** [comment]
How to update on fen? Trying zip install doesn't work
Thanks

**Comment by Tikipeter** [comment]
I just tested and the zip install is working fine.

**Comment by Bangtedd** [comment]
I Might doing it wrong, but it install fen light, not the other fen

**Comment by Tikipeter** [comment]
Or try Fen Light, you might like it better.

**Comment by Bangtedd** [comment]
Got it, will try fen light on this one, thank you for your support!
10/10 for fast customer service.

**Comment by Omarscomin** [comment]
Thank you @Tikipeter & @Twilightmercy😊

**Comment by jahepi-mx** [comment]
Thank you, Tikipeter and TwilightMercy! You guys rock, keep it up.

**Comment by Tikipeter** [comment]
RD, PM, AD, EN.

Not sure what others could be added. DL resides in France and has crippled their API just like the other French services.

**Comment by simonsmith** [comment]
Appreciate your efforts on this @Tikipeter!

I am still using the original Fen and saw with interest that your updates were ported to it. 

Can I install `plugin.video.fen-3.5.02.zip` directly from here? I note that https://tikipeter.github.io/packages/ only exposes `plugin.video.fenlight-2.0.04.zip` via the `index.html` and so that is all that is shown to me in the Kodi UI when adding a source and installing from zip

Thanks

**Comment by keensta** [comment]
> RD, PM, AD, EN.
> 
> Not sure what others could be added. DL resides in France and has crippled their API just like the other French services.

Sorry maybe I've misunderstood the whole RD and AD problem I assumed with everything happening there lifespans as potentially services that addons like Fen lite and similar use were/are coming to a potential end. 
I thought with there crackdown potentially films and TV shows will disappear and no longer cache again. 

Leaving only two services.

**Comment by mosestyle** [comment]
Love you!

Hopefully Torbox or other Debrid services will be added due to all this RD, AD drama.

Other than that, did I mention that we all love you?🤪

**Comment by iptvnoob** [comment]
> > RD, PM, AD, EN.
> > Not sure what others could be added. DL resides in France and has crippled their API just like the other French services.
> 
> Sorry maybe I've misunderstood the whole RD and AD problem I assumed with everything happening there lifespans as potentially services that addons like Fen lite and similar use were/are coming to a potential end. I thought with there crackdown potentially films and TV shows will disappear and no longer cache again.
> 
> Leaving only two services.

TB, Offcloud

**Comment by iptvnoob** [comment]
TB, Offcloud going to sign up for those

**Comment by TwilightMercy** [comment]
It is my honor.
Thank you very much, applied official Fen 3.5.02 fixes in my fork.

**Comment by YungZanji** [comment]
Thank you Tikipeter and TwilightMercy Amazing Work!!

**Comment by worphworph** [comment]
3.5.02 crashing when installing from zip, same as 3.5.01 and 3.2.30. Only 3.2.29 is possible to install from zip but only auto update to 3.5.01. Unfortunately 3.5.01 has disabled auto update function. Installing from repo showing only fanlight what I'm not interested. Any help?

**Comment by buds** [comment]
Thanks for all the great work over the years. Many dont appreciate what they had until it it's gone.

**Comment by Polgara01** [comment]
> RD, PM, AD, EN.
> 
> Not sure what others could be added. DL resides in France and has crippled their API just like the other French services.

EasyDebrid, and to a lesser extent, Offcloud as a backup.  Kodifitzwell has integrated both into POV - some of his code may be usable for FL.  It appears that ED, while newer, has some kind of partnership with PM and has what has been described as a 'huge' cache.  $40 for a year.  I'll grab it if FL is going to support it, otherwise I'm sticking with PM and EN for the time being.

**Comment by worphworph** [comment]
Thank you for great add-ons. Any chance to add TB support to FEN? Pov doesn't have same functionality as yours

**Comment by zosoleary** [comment]
In the tips and tricks section, there is still a "NEW!!!!" tag on one of the categories just in case you want to remove it to keep the add-on evergreen. Thanks for all your work!
