### ISSUE TITLE
Add Trakt List to menus in Fen Light

### ISSUE THREAD

**Issue by scamper-afk** [Tikipeter/tikipeter.github.io#193]
Is there a way to add my Trakt Lists to the TV Show menu, and the Movies menu, in Fen Light? 

I am aware that I can make lists into Widgets in the Kodi Home Screen using "Add to Favourites". But this isn't what I want to do. 

I'd like to have my own custom lists within the Fen Light Menus. So where the line items "Trending", "Popular", "Most Watched", "Genres", etc all exist. I want to add my own custom lists to exist between those line items in the menus. 

I hope I'm being clear enough to understand what I'm trying to ask. Is this something that is possible to do within Fen Light, or Fen?

**Comment by Tikipeter** [comment]
Go to the menu you want to add something to,  bring up the context menu, selections Content" and navigate to what you want to add.

Whilst you're there, see the other options as well I.e. Move, Remove etc
