### ISSUE TITLE
Situation Update 05/12/2024

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#194]
Hi all.

Unfortunately, I got called back to work a week early whilst still on holidays, so the going has been slow.

The plan for the final release is to have added Offcloud, Easydebrid and TorBox. The first 2 have been done, and TorBox is coming along nicely, but slowly. This is even with nicking Fitwell's code. I simply haven't got a lot of time, and Light is different enough from old Fen that it certainly isn't a copy/paste job.

I'm hoping to have it finished by early next week, followed by a couple of days of testing and then a final release.

Maybe stick around a few days and make sure there are no major errors with the new debrid services. So hopefully by the end of next week things can wrap up here and I can remove the repository from this github. Fingers crossed.

**Comment by mosestyle** [comment]
Honestly thank you for everything!!!🙏🙏🫶

**Comment by fsmeets84** [comment]
If any testing is needed, I'm sure willing to help with all three services.

**Comment by axeltechtips** [comment]
If you need testing with Torbox, I'm available. I've got a pro plan that I've been using. Thanks for everything.

**Comment by Blockr22** [comment]
Dude, you’re amazing. Thanks for all the hard work.

**Comment by ob89** [comment]
> Hi all.
> 
> Unfortunately, I got called back to work a week early whilst still on holidays, so the going has been slow.
> 
> The plan for the final release is to have added Offcloud, Easydebrid and TorBox. The first 2 have been done, and TorBox is coming along nicely, but slowly. This is even with nicking Fitwell's code. I simply haven't got a lot of time, and Light is different enough from old Fen that it certainly isn't a copy/paste job.
> 
> I'm hoping to have it finished by early next week, followed by a couple of days of testing and then a final release.
> 
> Maybe stick around a few days and make sure there are no major errors with the new debrid services. So hopefully by the end of next week things can wrap up here and I can remove the repository from this github. Fingers crossed.

I have opened an issue about the sequential playback.
Without torrentio Fen light fail to play several times especially on old and popular movies with a lot of unchaced links.
It try around 6-7 times jumping between resoultion and file sizes and going out and than you need to scrape again.
It really easy to check on the movie Samurai Princess because out of 40 files only one is cahced.
Thank you for all these years and I am hoping you can fix it for us Real Debrid users.
When torrentio is down it is really hard to find a working link.
Would really appreciate if you can look into that before deleting this github page.
English is not my first language I hope I have made myself clear.

**Comment by axeltechtips** [comment]
> > Hi all.
> > Unfortunately, I got called back to work a week early whilst still on holidays, so the going has been slow.
> > The plan for the final release is to have added Offcloud, Easydebrid and TorBox. The first 2 have been done, and TorBox is coming along nicely, but slowly. This is even with nicking Fitwell's code. I simply haven't got a lot of time, and Light is different enough from old Fen that it certainly isn't a copy/paste job.
> > I'm hoping to have it finished by early next week, followed by a couple of days of testing and then a final release.
> > Maybe stick around a few days and make sure there are no major errors with the new debrid services. So hopefully by the end of next week things can wrap up here and I can remove the repository from this github. Fingers crossed.
> 
> I have opened an issue about the sequential playback. Without torrentio Fen light fail to play several times especially on old and popular movies with a lot of unchaced links. It try around 6-7 times jumping between resoultion and file sizes and going out and than you need to scrape again. It really easy to check on the movie Samurai Princess because out of 40 files only one is cahced. Thank you for all these years and I am hoping you can fix it for us Real Debrid users. When torrentio is down it is really hard to find a working link. Would really appreciate if you can look into that before deleting this github page. English is not my first language I hope I have made myself clear.

He's probably already adding a fix to that as I see it's been closed.

**Comment by TimboZero** [comment]
> > Hi all.
> > Unfortunately, I got called back to work a week early whilst still on holidays, so the going has been slow.
> > The plan for the final release is to have added Offcloud, Easydebrid and TorBox. The first 2 have been done, and TorBox is coming along nicely, but slowly. This is even with nicking Fitwell's code. I simply haven't got a lot of time, and Light is different enough from old Fen that it certainly isn't a copy/paste job.
> > I'm hoping to have it finished by early next week, followed by a couple of days of testing and then a final release.
> > Maybe stick around a few days and make sure there are no major errors with the new debrid services. So hopefully by the end of next week things can wrap up here and I can remove the repository from this github. Fingers crossed.
> 
> I have opened an issue about the sequential playback. Without torrentio Fen light fail to play several times especially on old and popular movies with a lot of uncached links. It try around 6-7 times jumping between resoultion and file sizes and going out and than you need to scrape again. It really easy to check on the movie Samurai Princess because out of 40 files only one is cached. Thank you for all these years and I am hoping you can fix it for us Real Debrid users. When torrentio is down it is really hard to find a working link. Would really appreciate if you can look into that before deleting this github page. English is not my first language I hope I have made myself clear.

Real debrid works that way. Is, there is. I way to check if the file is cached or not anymore.

**Comment by rizreflects** [comment]
> > > Hi all.
> > > Unfortunately, I got called back to work a week early whilst still on holidays, so the going has been slow.
> > > The plan for the final release is to have added Offcloud, Easydebrid and TorBox. The first 2 have been done, and TorBox is coming along nicely, but slowly. This is even with nicking Fitwell's code. I simply haven't got a lot of time, and Light is different enough from old Fen that it certainly isn't a copy/paste job.
> > > I'm hoping to have it finished by early next week, followed by a couple of days of testing and then a final release.
> > > Maybe stick around a few days and make sure there are no major errors with the new debrid services. So hopefully by the end of next week things can wrap up here and I can remove the repository from this github. Fingers crossed.
> > 
> > I have opened an issue about the sequential playback. Without torrentio Fen light fail to play several times especially on old and popular movies with a lot of uncached links. It try around 6-7 times jumping between resoultion and file sizes and going out and than you need to scrape again. It really easy to check on the movie Samurai Princess because out of 40 files only one is cached. Thank you for all these years and I am hoping you can fix it for us Real Debrid users. When torrentio is down it is really hard to find a working link. Would really appreciate if you can look into that before deleting this github page. English is not my first language I hope I have made myself clear.
> 
> Real debrid works that way now, there is no way to check if the file is cached or not anymore.

I think he may be on to something though, as I've been having problems with autoplay myself. The difference in my case however, is that I also use premiumize alongside real debrid. Yesterday I was trying to watch the original 'Star Wars A New Hope'. My sorting is as follows:

-Dolby Vision & HDR both sorted to top of autoplay in that order.
-AI Enhanced filter excluded.

The results kept cycling through until no results were found. I tried this 3 times, and on the third time a real debrid result was selected, however it was an AI enhanced result which should have been excluded. Upon source selecting, I saw many premiumize links in 4k HDR which fen seemed to have missed completely. They all played perfectly fine aswell. 

I can't explain why the premiumize links weren't selected automatically. And I'm fairly certain that the AI enhanced filter is not functioning correctly, as I've seen it automatically select those links even though it should have been excluded on numerous occasions. 

With that being said, although it's not as perfect as it once was, I'm more happy with it. It still functions.

**Comment by hcgiub001** [comment]
Got excited you might consider staying when I checked if this has been deleted
