### ISSUE TITLE
Fen Light Updated to 2.0.05

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#199]
Hi all.

I have just pushed an update for Fen Light which includes support for Off Cloud, Easy Debrid and TorBox.

Big thanks to Kodifitzwell, who's code I pilfered for this update. Changed for Fen Light of course.

Also thanks to DaleAlanC, who kindly lent me his TorBox account so as I could edit the code for that as needed.

You have the weekend to give these a test and let me know here any major issues. I will then fix those issues and release a final update. After that, this repository will be closed.

**Comment by DaleAlan** [comment]
Woohooo Amazing work as usual Peter. Not sure if it’s a wonky setting I’ve got in my Torbox but can’t seem to get it to load anything. Just pops up a check Fenlight Error log with a python error when I click on a movie or show episode.

Error Type <class ‘UnboundLocalError’>
Error Contents:Local variable ‘oc_highlight’ referenced before assignment.
UnboundLocalError: local variable ‘oc_highlight’ referenced before assignment.

I’ll have a wangle about with it though as I think it’s something on my end I’ll have screwed up or haven’t enabled.

Have a good ‘un and huge thanks for all you do.

**Comment by rmkjr** [comment]
> Woohooo Amazing work as usual Peter. Not sure if it’s a wonky setting I’ve got in my Torbox but can’t seem to get it to load anything. Just pops up a check Fenlight Error log with a python error when I click on a movie or show episode.
> 
> Error Type <class ‘UnboundLocalError’> Error Contents:Local variable ‘oc_highlight’ referenced before assignment. UnboundLocalError: local variable ‘oc_highlight’ referenced before assignment.
> 
> I’ll have a wangle about with it though as I think it’s something on my end I’ll have screwed up or haven’t enabled.
> 
> Have a good ‘un and huge thanks for all you do.

Whoops, missed your comment before submitting an issue for this.

@Tikipeter, there's a full log and what setting seems to be linked to it happening in mine.

**Comment by DaleAlan** [comment]
> > Woohooo Amazing work as usual Peter. Not sure if it’s a wonky setting I’ve got in my Torbox but can’t seem to get it to load anything. Just pops up a check Fenlight Error log with a python error when I click on a movie or show episode.
> > Error Type <class ‘UnboundLocalError’> Error Contents:Local variable ‘oc_highlight’ referenced before assignment. UnboundLocalError: local variable ‘oc_highlight’ referenced before assignment.
> > I’ll have a wangle about with it though as I think it’s something on my end I’ll have screwed up or haven’t enabled.
> > Have a good ‘un and huge thanks for all you do.
> 
> Whoops, missed your comment before submitting an issue for this.
> 
> @Tikipeter, there's a full log and what setting seems to be linked to it happening in #200 .

S’all good. I was busy copying the log to send across so saves me fighting the laptop. Think it may be a tmdb python\scraper issue after a bit off googling but if I try and fix it I’ll probably blow the laptop up so best left to the professionals 😀
https://github.com/xbmc/metadata.themoviedb.org.python/issues/108

**Comment by Tikipeter** [comment]
It was a small oversight. Set it to "Provider" or "Single Color" and it will work for now. Already fixed for next update.

**Comment by DaleAlan** [comment]
> It was a small oversight. Set it to "Provider" or "Single Color" and it will work for now. Already fixed for next update.

Brilliant. Can’t find another bug to keep you around forever but I’m not giving up yet big fella 🤣

**Comment by Blockr22** [comment]
There isn’t torbox option to set color when highlight results based on set to provider.

**Comment by Tikipeter** [comment]
@rmkjr are your single episode lists working correctly now i.e. no remaining episode count when the show is unwatched?

**Comment by RevontuletCXVII** [comment]
Crazy that the way results are coloured can break playback... Fixed the issue on RD as well.

**Comment by rmkjr** [comment]
> @rmkjr are your single episode lists working correctly now i.e. no remaining episode count when the show is unwatched?

Not sure I’ve noticed that before.  Did I comment on it somewhere, totally forgot if I had 😄 but always happy to test out where I can.

As far as I can tell that seems solid.  I have “Provide Unwatched Episodes Info” off.  In my Trakt Calendar, only single episode list I could think of that would have unwatched shows, both in addon and on Nimbus widgets, appear to be remainder count free.

**Comment by Tikipeter** [comment]
Yeah I got completely mixed up on who had opened an issue here on github.

**Comment by rmkjr** [comment]
All good!  Great work between both you and Fitzwell on the Torbox piece!  Just got to give it a go.  Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat.  Much appreciate the add to one of my most used pieces of software 😁

**Comment by Blockr22** [comment]
@rmkjr ohh so it’s a torbox issue ?
My kodi is crashing if i seek or stop playback

**Comment by DaleAlan** [comment]
> All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁

There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.

https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG

**Comment by rmkjr** [comment]
Yeah, seems to be longer pauses, and most seeks (not sure if all or just ones that go outside the current buffer).  Their storage server endpoint seems to just give up.  I'm guessing it will stabilize as they scale. Wamy said on the discord the storage endpoints are still being poked.  Once playback starts, outside of Trakt scrobbling, addons like Fen Light are pretty much out of the chain and Kodi is doing the work.

I'll see stuff like this after a long pause or seek, which to me looks like the storage server giving up:

    2024-12-13 20:41:44.762 T:11783 warning <general>: CFileCache::Process - <https://storage.torbox.app/dld/[REDACT]> source read returned 0! Will retry
    2024-12-13 20:41:46.762 T:11783 warning <general>: CCurlFile::CReadState::FillBuffer - (0xc42261c8) Reconnect, (re)try 1
    2024-12-13 20:44:17.968 T:11817    info <general>: CAEStreamParser::TrySyncAC3 - E-AC3 stream detected (6 channels, 48000Hz)
    2024-12-13 20:44:17.969 T:11817    info <general>: CActiveAEStream::AddData - messy timestamps, increasing interval for measuring average error to 6000 ms
    2024-12-13 20:44:19.931 T:11817    info <general>: CAEStreamParser::TrySyncAC3 - E-AC3 stream detected (6 channels, 48000Hz)
    2024-12-13 20:47:25.939 T:11817    info <general>: CVideoPlayerAudio::Process - stream stalled
    2024-12-13 20:47:34.490 T:11816   error <general>: CAMLCodec::GetPicture: time elapsed since last frame: 5922ms (11:Resource temporarily unavailable)

**Comment by rmkjr** [comment]
> > All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁
> 
> There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.
> 
> https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG

That seemed to help Fitzwell get over some of his early real bad streams ending issues.  I've had that in as well from the start because of Easynews, but I think at this point it's down to them finishing and fixing up their deployment.

**Comment by DaleAlan** [comment]
> > > All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁
> > 
> > 
> > There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.
> > https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG
> 
> That seemed to help Fitzwell get over some of his early real bad streams ending issues. I've had that in as well from the start because of Easynews, but I think at this point it's down to Torbox finishing and fixing up their deployment.

Fingers crossed. Tried it with the file removed and it just crashes out as soon as it starts a file. Bit erratic though as it sometimes plays fine but at others needs a full task kill so I’ll just leave the bugger in. Everything seems to be working spot on and they’ve said they’re still in the process of balancing their servers and such so here’s hoping.

**Comment by rizreflects** [comment]
Hey Peter, 

I've noticed a bug which has been there for some time. The AI enhanced filters do not seem to work when excluded. Upon source select I still see many links tagged with the AI enhanced label. There has also been a number of occasions where an AI enhanced result was selected when using autoplay, even though I have it excluded. 

That's the only noticeable bug I've come across recently.

**Comment by mosestyle** [comment]
> > > All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁
> > 
> > 
> > There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.
> > https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG
> 
> That seemed to help Fitzwell get over some of his early real bad streams ending issues. I've had that in as well from the start because of Easynews, but I think at this point it's down to Torbox finishing and fixing up their deployment.

Apparently the Dev in Torbox can't fix the issue (atm) since he can't reproduce the issue no matter what he do 🤔😞😞

**Comment by rmkjr** [comment]
> > > > All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁
> > > 
> > > 
> > > There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.
> > > https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG
> > 
> > 
> > That seemed to help Fitzwell get over some of his early real bad streams ending issues. I've had that in as well from the start because of Easynews, but I think at this point it's down to Torbox finishing and fixing up their deployment.
> 
> Apparently the Dev in Torbox can't fix the issue (atm) since he can't reproduce the issue no matter what he do 🤔😞😞

Feel like an idiot lol, I just realized I had moved my advancedsettings.xml to advancedsettings.xml_BAK when I thought Torbox enabled HTTP2 on their nginx.  Going to put that back and see if it helps any.  [This](https://github.com/xbmc/xbmc/issues/19838) makes me think this is more of an HTTP2 implementation issue in curl than anything else.

**Comment by DaleAlan** [comment]
> > > > > All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁
> > > > 
> > > > 
> > > > There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.
> > > > https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG
> > > 
> > > 
> > > That seemed to help Fitzwell get over some of his early real bad streams ending issues. I've had that in as well from the start because of Easynews, but I think at this point it's down to Torbox finishing and fixing up their deployment.
> > 
> > 
> > Apparently the Dev in Torbox can't fix the issue (atm) since he can't reproduce the issue no matter what he do 🤔😞😞
> 
> Feel like an idiot lol, I just realized I had moved my advancedsettings.xml to advancedsettings.xml_BAK when I thought Torbox enabled HTTP2 on their nginx. Going to put that back and see if it helps any. [This](https://github.com/xbmc/xbmc/issues/19838) makes me think this is more of an HTTP2 implementation issue in curl than anything else.
> 
> Edit: Yep, that totally fixed. Can't believe I didn't catch me taking that out. Just a bad HTTP2 implementation in libcurl, best to leave it disabled.

Go and stand in the corner until you’ve learnt your lesson 🤣 yeah amazing how a small .xml fixes the bloody thing. Not sure how they can’t replicate the issue as it happens near enough consistently with the file taken back out. Oh well it’s no biggie leaving it in.

**Comment by Tikipeter** [comment]
>Hey Peter,
I've noticed a bug which has been there for some time. The AI enhanced filters do not seem to work when excluded. Upon source select I still see many links tagged with the AI enhanced label. There has also been a number of occasions where an AI enhanced result was selected when using autoplay, even though I have it excluded.
That's the only noticeable bug I've come across recently.

Have you got a recent example? I'm having a hard time finding results that are enhanced.

**Comment by mosestyle** [comment]
> > > > > All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁
> > > > 
> > > > 
> > > > There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.
> > > > https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG
> > > 
> > > 
> > > That seemed to help Fitzwell get over some of his early real bad streams ending issues. I've had that in as well from the start because of Easynews, but I think at this point it's down to Torbox finishing and fixing up their deployment.
> > 
> > 
> > Apparently the Dev in Torbox can't fix the issue (atm) since he can't reproduce the issue no matter what he do 🤔😞😞
> 
> Feel like an idiot lol, I just realized I had moved my advancedsettings.xml to advancedsettings.xml_BAK when I thought Torbox enabled HTTP2 on their nginx. Going to put that back and see if it helps any. [This](https://github.com/xbmc/xbmc/issues/19838) makes me think this is more of an HTTP2 implementation issue in curl than anything else.
> 
> Edit: Yep, that totally fixed. Can't believe I didn't catch me taking that out. Just a bad HTTP2 implementation in libcurl, best to leave it disabled.

What did you wrote in the advancedsettings.xml to fix the issue? 😮😮

**Comment by DaleAlan** [comment]
> > > > > > All good! Great work between both you and Fitzwell on the Torbox piece! Just got to give it a go. Outside of their storage server returning 0s when coming back from pauses and seeks and freaking out Kodi's curl and buffer, all your stuff seems to be working a treat. Much appreciate the add to one of my most used pieces of software 😁
> > > > > 
> > > > > 
> > > > > There’s a fix which requires an advancedsettings.xml put into your userdata folder. Torbox claims they’ve fixed the issue but they haven’t, works spot on with the file in but as soon as you take it out it breaks Kodi again as soon as you seek or even after a second or two of playback.
> > > > > https://www.reddit.com/r/TorBoxApp/s/Q3ZaiX5TxG
> > > > 
> > > > 
> > > > That seemed to help Fitzwell get over some of his early real bad streams ending issues. I've had that in as well from the start because of Easynews, but I think at this point it's down to Torbox finishing and fixing up their deployment.
> > > 
> > > 
> > > Apparently the Dev in Torbox can't fix the issue (atm) since he can't reproduce the issue no matter what he do 🤔😞😞
> > 
> > 
> > Feel like an idiot lol, I just realized I had moved my advancedsettings.xml to advancedsettings.xml_BAK when I thought Torbox enabled HTTP2 on their nginx. Going to put that back and see if it helps any. [This](https://github.com/xbmc/xbmc/issues/19838) makes me think this is more of an HTTP2 implementation issue in curl than anything else.
> > Edit: Yep, that totally fixed. Can't believe I didn't catch me taking that out. Just a bad HTTP2 implementation in libcurl, best to leave it disabled.
> 
> What did you wrote in the advancedsettings.xml to fix the issue? 😮😮

<advancedsettings version="1.0">
<network>

<disablehttp2>true</disablehttp2>
</network>
</advancedsettings>


Save it as advancedsettings.xml and drop it into your userdata folder if it doesn’t have one their by default.

**Comment by rmkjr** [comment]
<advancedsettings>
        <network>
            <disablehttp2>true</disablehttp2>
        </network>
    </advancedsettings>

**Comment by mosestyle** [comment]
> ```
> <advancedsettings>
>     <network>
>         <disablehttp2>true</disablehttp2>
>     </network>
> </advancedsettings>
> ```

Cheers mate, thank you!🙏

**Comment by pashosh** [comment]
there is a problem in the latest realease in linux and android tv (i don't know if it's also on windows).
there is an error message before the scraping for results.
in reddit:
https://www.reddit.com/r/Addons4Kodi/comments/1hetivu/fen_light_error_after_latest_update/
people have found that if you change the results color to a `single color` or set the colors by the `provider` , the problem is fixed.
so the problem occures only when the results colors are categorized by video quality.

**Comment by baptistebisson** [comment]
Hi. I've updated the package but my widget seems to have changed. 
The first one was my ongoing shows and now it's trending.
Any idea why ? It's a bit tedious to set it back like before

**Comment by Ano-byte** [comment]
Hey @Tikipeter , long time listener first time caller :).
Thanks a bunch for adding support for additional hosters to FenLite. 
Do you think regular FEN could get the same love?
