### ISSUE TITLE
Small Fen Light Window Issue

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/tikipeter.github.io#2]
Hi,

Small and random picture adjustment issue I've noticed:

**Fen Light --> Tools --> Database & Cache Maintenance --> Clear All Cache (Excluding Favorites)**

(Fen light logo)
![WhatsApp Image 2024-01-03 at 23 16 08_99e2cfe3](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/cb9efa69-d41d-4b5e-9cb7-c35ddfa9d72d)

Happy new year!

**Comment by Tikipeter** [comment]
Thanks.

I'll have a look into adjusting that when I get the chance.
