### ISSUE TITLE
Fixing mixed content guidance

### ISSUE THREAD

**Issue by ivarbrandt** [Tikipeter/tikipeter.github.io#208]
Hey man! Hope all is well.

I wanted to ask for your guidance before you leave in one last thing I want to fix in Fen/Fen Light.

Trakt lists that have mixed content don't work for episodes in Fen or Fen Light. That is that if a Trakt list has movies it will show them, but if it has a tvshow and/or individual episodes it shows nothing.

I know that in POV, this is working correctly. The content type is set to episodes list and I can see everything that is in the Trakt list.

The list I'm using for reference is this one: https://trakt.tv/users/wildestsdreamss/lists/one-chicago-watch-order?hide=watched&sort=rank,asc

I'd feel bad asking you to fix this when you're about to retire. Plus I feel like it's a bigger job overall. So my question is, what part of the code would I need to look at in order to fix this in Fen/Fen Light?

**Comment by Tikipeter** [comment]
I purposely haven't supported season and episode items in mixed Trakt lists because it then comes down to what media type do I assign for the container. I figured with movies and tvshows they usually support the same views, so the correct container assignment isn't so important.

But since it's you asking...

**Comment by kodifitzwell** [comment]
I use a dictionary to keep track of the number of items for each, then set the content to max items.

    process_dict = {'movies': 0, 'tvshows': 0, 'seasons': 0, 'episodes': 0}
    ...
    content, total = max(process_dict.items(), key=lambda k: k[1])
    ...
    kodi_utils.set_content(__handle__, content)

**Comment by Tikipeter** [comment]
Yeah I went in the same direction.

Nobody wants seasons supported, right? Can we just do episodes?

**Comment by kodifitzwell** [comment]
I included seasons because I like this list.

[TV & Movie New Releases](https://trakt.tv/lists/23287216)

the listitem opens to the correct season.

https://imgur.com/a/5JgrCgq

**Comment by ivarbrandt** [comment]
I want seasons supported as they are included in some mixed lists. For example:

[Marvel Cinematic Universe](https://trakt.tv/users/donxy/lists/marvel-cinematic-universe?sort=rank,asc)

**Comment by Tikipeter** [comment]
OK.

**Comment by ivarbrandt** [comment]
Thanks Peter.

Happy Holidays to you and your loved ones my guy.
