### ISSUE TITLE
Addon KIT

### ISSUE THREAD

**Issue by Vesuvio19** [Tikipeter/tikipeter.github.io#209]
Hi, I hope you're well.
I hope I'm not in the wrong place but I wanted to point out that the addon KIT of Aliunde repository,  doesn't work.
Once real debrid is set up, when you search ther's no results while with other addons it works correctly.
It is possible to solve this problem, the addon is very well made and I would like to use it.
Thank you and sorry for my bad english :)

**Comment by Tikipeter** [comment]
You are in the wrong place in afraid.

**Comment by Vesuvio19** [comment]
Thanks you

Il gio 19 dic 2024, 13:18 Tikipeter ***@***.***> ha scritto:
