### ISSUE TITLE
remember previous successful resolves error

### ISSUE THREAD

**Issue by vella9** [Tikipeter/tikipeter.github.io#21]
Hello, I got an error when trying to enable "playback>remember previous successful resolves" as per log.

[https://paste.kodi.tv/adiwezivit.kodi]()

Hope the above is enough
thank you

**Comment by Tikipeter** [comment]
That setting has been removed.

I don't know what version of Fen Light you are on as you didn't post a full log, but update to the latest version.

**Comment by Tikipeter** [comment]
The feature is gone, but I've forgotten to remove the setting.

**Comment by vella9** [comment]
Oh, ok. that makes sense then. Is it something that might be reconsidered going forward? or anything similar maybe?

I was looking at a way to "reuse" the same source if I wanted to continue watching a movie/show.

If not no worries and thank you for your work!

**Comment by Omarscomin** [comment]
> Oh, ok. that makes sense then. Is it something that might be reconsidered going forward? or anything similar maybe?
> 
> I was looking at a way to "reuse" the same source if I wanted to continue watching a movie/show.

https://www.reddit.com/r/Addons4Kodi/s/xA3ZeTCcrV

**Comment by vella9** [comment]
thank you for this @Omarscomin . Will check it out

**Comment by Tikipeter** [comment]
I couldn't work out why it wasn't working correctly for some (most?) people when there was nothing wrong with the code.

It was a breaking bug for those that had it, so I decided to remove it. It was a useful little feature though, so I may revisit it.

Omarscomin's link is the best current way of achieving the same thing, with the caveat that each item will be added to your cloud, or rather, not removed from your cloud after resolving.
