### ISSUE TITLE
Torbox Usenet items get found in cloud, but not scraped for playback

### ISSUE THREAD

**Issue by ZEPLUMBER1** [Tikipeter/tikipeter.github.io#210]
Thanks for updating the add-on again! 

That would be the last request

Basically, usenet items are found under ''my services'', but when scraping for a movie they are not found by the add-on even though they are present in TB Cloud

TIA but feel free to ignore if you want to pull the plug.

**Comment by Tikipeter** [comment]
I'll have a look,  but I thought the Usenet results are named alphanumeric jarbles. Which would make scraping them impossible the way we do it.

**Comment by ZEPLUMBER1** [comment]
The files are named correctly the vast majority of the time, of course there are exceptions

https://postimg.cc/gallery/4G4hPpz

They are also picked by ''my services'' the same way in the add-on, but unfortunately Torbox is a bit slow right now and the add-on won't connect (not an issue from the add-on)

I don't know if the account you have access to is pro or not, but I could give you an API key (pro but not dev) if you want to use it and test. Let me know if you need it

Thanks again for all  you do.
