### ISSUE TITLE
Movies and TV Shows > Years and Decades displays up to 2030

### ISSUE THREAD

**Issue by Better-Red** [Tikipeter/tikipeter.github.io#211]
Hi,

Thank you for all you've done.

I've just noticed that FEN Lite > Movies and TV Shows > Years and Decades displays up to 2030, obviously with no content from 2025 onwards.  The sections were definitely correct (2024 / 2020's) at some point recently, although I cannot remember which version of FEN Lite I last looked.  I cross checked with both FEN and POV and again, they are correct (2024 / 2020's).

Hopefully I've caught you before your well earned retirement.  Is this something that can be rectified, or can you point me at what I need to change?

Thanks again.

**Comment by Tikipeter** [comment]
That's so I can retire.

**Comment by Better-Red** [comment]
Of course, ha ha. I'll have a play with the meta_lists.py and keep adding years in.
