### ISSUE TITLE
[Possible Bug] Autoplay not functioning correctly

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/tikipeter.github.io#212]
Hey Peter,

I've come across quite a big issue recently, I'm not sure if it's a bug or something to do with my setup. For the past couple of weeks, if I play an older movie with 1080p links but no 4k, autoplay will completely skip the 1080 links and only play 720p or less. It will generally skip the 720p source and play SD. When going back and source selecting, I see numerous 1080p links, and playing one works correctly. Would you mind testing this if it's not too much of a problem? Cypher (2002) and Tracks (2013) are 2 examples of the type of movie I'm describing. That being said, this seems to be happening with any 1080p movie.

**Comment by bbviking** [comment]
I attempted to recreate the issue and I didn't run into it myself. Out of interest what's your results sorting criteria?

And is 1080p included in your 'limit auto play quality' options under playback?

**Comment by rizreflects** [comment]
> I attempted to recreate the issue and I didn't run into it myself. Out of interest what's your results sorting criteria?
> 
> And is 1080p included in your 'limit auto play quality' options under playback?

Thank you for testing this out. Hmm.. I don't know why it's happening to me, I never changed any settings recently. Here's a video of the problem.: https://streamable.com/7letdj

I tried it with a random 1080p movie and it reoccured.

![20241220_001421.jpg](https://github.com/user-attachments/assets/6eb79be5-a444-41f1-a99f-e724a599745d)

I have all the formats selected when it comes to autoplay quality. My results aren't filtered by size either. If it's not happening to you it must be something to do with my setup. I'll go ahead and close this issue in that case. Sorry about that @Tikipeter

**Comment by rizreflects** [comment]
> I attempted to recreate the issue and I didn't run into it myself. Out of interest what's your results sorting criteria?
> 
> And is 1080p included in your 'limit auto play quality' options under playback?

![20241220_002247.jpg](https://github.com/user-attachments/assets/5366c135-9836-47cd-88e0-f00d02aa356f)

![20241220_002234.jpg](https://github.com/user-attachments/assets/8b8114e3-c3d5-4b78-bfb0-90da0bf125df)

Here's my results sorting criteria. Would you mind testing it out and seeing if causes a problem for you?

**Comment by bbviking** [comment]
It appears to be your 'Custom Autoplay Sort to Top' setting when it includes HDR.

Looking at the filenames of the sources it attempts to play, I don't think it's a coincidence that their name contains 'HDR' as part of 'HDRIP'.

What's interesting is that FEN appear to be correctly not tagging the source as HDR, but somehow the autoplay sorting thinks that it is HDR. I assume different logic is being used for detecting if the source is HDR.

I think you should reopen this issue. I'll try and give it a look tomorrow if tikipeter doesn't

**Comment by bbviking** [comment]
This looks to work for me, on sources.py first include this at the top:

```
import re
```

Then replace this line:

```
preference_results = [i for i in results if any(x in i['extraInfo'] for x in preferences)]
```

with this

```
preference_results = [
	i for i in results
	if any(re.search(rf'(\b|[^a-zA-Z0-9]){x}(\b|[^a-zA-Z0-9])', i['extraInfo']) for x in preferences)
]
```

it should do a better job at matching the extrainfo on the given sources (making sure to ignore symbols because some of them have bold tags around them)

**Comment by rizreflects** [comment]
@bbviking Wow nice one. You did one hell of a job testing. Thanks a lot for finding the cause, I've been scratching my head with this one.

**Comment by bbviking** [comment]
> @bbviking Wow nice one. You did one hell of a job testing. Thanks a lot for finding the cause, I've been scratching my head with this one. 

No worries. Side note but I'm pretty sure I recognise your username, thank you for your Trakt lists. I've found your 'trending now' lists very helpful for a long time now🙏

**Comment by rizreflects** [comment]
@bbviking that's great to hear. I've spent way too many hours on those lists. I've retired like Peter now lol.

**Comment by rizreflects** [comment]
Doesn't look like this was fixed in the latest version unfortunately. Still getting HD Rips when autoplaying with HDR sorted to top. Please fix this one last thing @Tikipeter 😭😭 I miss autoplay.

**Comment by rizreflects** [comment]
In a moment of desperation I attempted to give your fix go myself @bbviking and am pleased to say it was much easier than I had anticipated! The problems completely solved. Just want to thank you one more time for this. You did me a solid.
