### ISSUE TITLE
Remove the resolve attempt limit

### ISSUE THREAD

**Issue by bbviking** [Tikipeter/tikipeter.github.io#213]
There is currently a limit placed on the amount of sources that will be used for resolve retries. I was wondering if it would be possible to remove this please? 

With how FEN Light will no longer check the cache status of real debrid/all debrid links when scraping, it could mean that for more niche content it will fail to play if the first 8 links it tries aren't cached.

It would be a small change to the play_file function inside sources.py from this:
				
```
trailing_index = 7 - len(items_prev)
items_next = results[source_index:source_index+trailing_index]
```

To just this:

```
items_next = results[source_index:]
```

**Comment by ob89** [comment]
> There is currently a limit placed on the amount of sources that will be used for resolve retries. I was wondering if it would be possible to remove this please?
> 
> With how FEN Light will no longer check the cache status of real debrid/all debrid links when scraping, it could mean that for more niche content it will fail to play if the first 8 links it tries aren't cached.
> 
> It would be a small change to the play_file function inside sources.py from this:
> 
> ```
> trailing_index = 7 - len(items_prev)
> items_next = results[source_index:source_index+trailing_index]
> ```
> 
> To just this:
> 
> ```
> items_next = results[source_index:]
> ```

Hi bbviking,

Can you please look into my issue?
https://github.com/Tikipeter/tikipeter.github.io/issues/190

I have tried to ask from tikipeter several times but he ignored me.
I would really appreciate if you can take a look when you have the time.

Thank you bbviking
