### ISSUE TITLE
What is the difference between Fen and Fen light

### ISSUE THREAD

**Issue by Maxxx233** [Tikipeter/tikipeter.github.io#23]
Hello, I use Google Chromecast and its not fast and i was wondering if fen light is faster or something

**Comment by Tikipeter** [comment]
Possibly.

**Comment by Maxxx233** [comment]
but what is the difference like is there some options missing?

**Comment by Omarscomin** [comment]
> Hello, I use Google Chromecast and its not fast and i was wondering if fen light is faster or something 

You've spent more time and effort posting this as a GitHub issue than it would've taken for you to just try FEN Light and see the differences for yourself.

**Comment by Tikipeter** [comment]
I don't remember.

**Comment by xyzfre** [comment]
> can you tell me what these are?

You should install it and do the comparison yourself to see which one accommodate you better Simple
