### ISSUE TITLE
When resuming a Episode or Movie with a progress point

### ISSUE THREAD

**Issue by xyzfre** [Tikipeter/tikipeter.github.io#25]
This is been happening for quite some time no biggie ,When resuming a Episode or Movie with a progress point audio comes in first for a quick one or two seconds, and then playback starts,with OG Fen when resuming a progress point, it starts right away I remember a while back when you implemented this in Fen but it was a long time ago ,,thank you @Tikipeter for your AMAZING work

**Comment by Tikipeter** [comment]
I'll look into whether this is fixable or not.

It might be something we have to put up with.

**Comment by xyzfre** [comment]
> I'll look into whether this is fixable or not.
> 
> 
> 
> It might be something we have to put up with.

Thank you @Tikipeter would be GREAT if this could be fixed.😎OG Fen spoiled me lol

**Comment by xyzfre** [comment]
Hey @Tikipeter hope all is well, was wondering have you made some changes regarding this issue? I noticed today when playing a movie with a progress point it's working perfect🤞🏼🤞🏼, episodes also improve  a bit. I have been using Fenlight more often now then Fen. I've been using it for almost 5 years OG Fen. The only changes I've done on my end is update to 21.0 Omega.

**Comment by Tikipeter** [comment]
It's been a chaotic week but I don't think I'd done anything. I really had no idea what I could do that would help.

I use a combination of Kodi informing it has started playback and Kodi informing that the video player window is active to decide when to close the resolving window. As such, if either of those 2 checks are coming through a little later than they should, then you will see a slight delay with the closing of the resolving window.

I'll have a look now if I can decrease the time between checks, but we're talking milliseconds here so it likely won't make any difference.

**Comment by xyzfre** [comment]
Thank you @Tikipeter highly appreciated💯 for taking your time to look into this minor issue.

**Comment by xyzfre** [comment]
Thank you @Tikipeter highly appreciated💯 for taking your time to look into this minor issue.Looking forward to the update I think 50ms might help🤞🏼🤞🏼
