### ISSUE TITLE
Monitor for successful playback

### ISSUE THREAD

**Issue by Maxxx233** [Tikipeter/tikipeter.github.io#26]
In Fen light after scraping it goes straight into the video but with Fen when this option is disabled first it exits the scraping screen and after like 1 or 2 seconds the video comes on. Can you make it an option to not do that?

**Comment by Maxxx233** [comment]
I am asking about Fen. When the Monitor for successful playback is turned on it goes straight from scraping to video but with it being disabled it exits out and there after 1 or 2 seconds is the loading animation and then the video starts playing

**Comment by Tikipeter** [comment]
Fen is retired.

**Comment by Maxxx233** [comment]
Its sad i liekd it more. Well then can you add fanart .tv to fen light?

**Comment by Maxxx233** [comment]
1
