### ISSUE TITLE
Fen light result sorting / autoplay

### ISSUE THREAD

**Issue by Maxxx233** [Tikipeter/tikipeter.github.io#28]
I know there are some options but is there an option to sort: Highest quality and lowest size? Because when I try to watch Braking Bad the first result is 4k 27 GB and it's unplayable but when I rescrape and choose a source I can pick one with a lower size and it works perfectly fine. There was an option to sort it like I described in fen.

**Comment by Tikipeter** [comment]
No option to sort by ascending/descending file size in Fen Light.

You need to filter rather than sort.

Either set your internet line speed in settings, or set a maximum file size in settings.

That will remove results that you cannot play due to excessive size.

**Comment by Maxxx233** [comment]
Okay thank you
