### ISSUE TITLE
Reminder of the "Rollback" feature...

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/tikipeter.github.io#29]
Hello all. I hope you are all well and happy.

The latest update of Fen Light has some re-writing of how the watched data is processed for all media.

These changes will affect EVERY menu that has media, be it Movies, TV Shows, Seasons or Episodes. If there are any bugs within the implementation, it could render Fen Light practically useless.

As such, I thought it would be a good idea to highlight the fact that there is a "rollback" feature in the Tools section of Fen Light. Here you can easily install an older version of the addon if the latest update is causing issues. Be sure to report the issue here first with a log file of course.

This will enable you to continue using the addon without interuption. Simply watch here for when the issues are fixed and then update; again through the Tools menu.

It's not that I'm anticipating issues, it's just that a friendly reminder of the rollback feature is a good idea.

**Comment by Omarscomin** [comment]
I noticed that in-progress TV shows were out of order, but I rolled back before grabbing a log because I didn't want to bug ya. I'll get you a log as soon as I can. 

Thank you for the clear communication, per usual!😊

**Comment by Tikipeter** [comment]
Thanks Omarscomin, no log needed for that.

I think I have it fixed.

**Comment by TwilightMercy** [comment]
Thank you, you're the best.

**Comment by Omarscomin** [comment]
> Thanks Omarscomin, no log needed for that.
> 
> I think I have it fixed.

Thank you, @Tikipeter! Just wanted to communicate that the issue is still present in version 1.0.44. The changelog implied that it may have been fixed, so I just wanted to let you know😊

**Comment by jorgitoxp** [comment]
@Tikipeter i was one of the users that posted on Reddit.  When I updated to .44 my next episode section displayed a bunch of other episodes/series I’ve already finish watching and I’m all caught up with.  I reverted back to .43 and the issue is resolved.  Tell me what I can submit or do to help you troubleshoot.  I reverted back but I can update again and provide anything you need from me.  Thanks for everything you do.

**Comment by jorgitoxp** [comment]
I’m also noticing an issue which I see in .43.  I have a movie which fentastic widget shows is 59% watched.  When I select it, and I pick my same source, before I would get an options to start from scratch or resume from my last point.  Now I don’t get any options.  It just starts the movie from the beginning.  Even though fen light recognizes I’ve already watched half the movie.

**Comment by Tikipeter** [comment]
> Thank you, @Tikipeter! Just wanted to communicate that the issue is still present in version 1.0.44. The changelog implied that it may have been fixed, so I just wanted to let you know😊

Have you marked anything as watched since testing the new update.

If not, mark something as watched and see if that fixes the issue.

Otherwise, let me know which sort order you have set. I would assume Latest Watched.


> When I updated to .44 my next episode section displayed a bunch of other episodes/series I’ve already finish watching and I’m all caught up with. I reverted back to .43 and the issue is resolved.

Do they show with a watched checkmark when in the next episode section?

**Comment by jorgitoxp** [comment]
> Do they show with a watched checkmark when in the next episode section?

@Tikipeter so i went ahead and updated again to .44.  Issue is gone now, my next episodes only shows what i currently have pending.  Not sure why when i reverted back to .43 and now updated again to .44 it resolved the issue.  

Only issue I now have is related to in progress movies starting from the beginning.  It's not giving me the option to resume from where i left off.  Before i would get an option to either start from beginning or continue watching from where i had left off.

I have a movie that shows as 59% watched, but i do not get any options and it just starts from 0 every single time.

**Comment by Tikipeter** [comment]
>Issue is gone now, my next episodes only shows what i currently have pending. Not sure why when i reverted back to .43 and now updated again to .44 it resolved the issue.

Glad to hear. There are issues though that I will need to resolve.

>Only issue I now have is related to in progress movies starting from the beginning.

I've found the bug for this, and it will be fixed next update.

I appreciate you reporting back.

**Comment by jorgitoxp** [comment]
> I've found the bug for this, and it will be fixed next update.
> 
> I appreciate you reporting back.

No need to thank me, thank you for all the hard work and for always sharing your amazing work with us.

**Comment by Tikipeter** [comment]
I'll be pushing `1.0.45` soon which will hopefully fix all the issues.

@Omarscomin if your list is not sorting correctly, select Tools->Database & Cache Maintenance->Clear Lists Cache.

**Comment by jorgitoxp** [comment]
@Tikipeter just tried .45.  My in progress movie started from the point I left it off.  So is working.  Question is, should I have received a prompt asking if I wanted to resume or start from beginning?

**Comment by Tikipeter** [comment]
Try out `1.0.45` and see if it's better.

If sorting is the issue, and not Next Episodes, then clear the LISTS cache in Tools->Database & Cache Maintenance.

>Question is, should I have received a prompt asking if I wanted to resume or start from beginning?

Depends what your setting is for Settings->Playback->Automatically Resume Playback. Set it to "NEVER" to test.

**Comment by jorgitoxp** [comment]
@Tikipeter .45 fixed the issue.  I was not getting the promo asking to resume or start from beginning because a setting I had.  I updated the setting and now I was asked if i wanted to resume or start from beginning.  Working perfectly now for in progress.

**Comment by Tikipeter** [comment]
Yep. We're talking over ourselves but came to the same conclusion. :)

**Comment by jorgitoxp** [comment]
> Try out `1.0.45` and see if it's better.
> 
> If sorting is the issue, and not Next Episodes, then clear the LISTS cache in Tools->Database & Cache Maintenance.
> 
> > Question is, should I have received a prompt asking if I wanted to resume or start from beginning?
> 
> Depends what your setting is for Settings->Playback->Automatically Resume Playback. Set it to "NEVER" to test.

lol I deleted my original message after I remembered that setting.  It’s working as designed.  Thank you so much.

**Comment by Omarscomin** [comment]
All is well on version 1.0.45! Thank you, Peter🫶🏻

**Comment by Tikipeter** [comment]
Thanks for reporting back Omarscomin.
