### ISSUE TITLE
[Question] Fen - Subtitles from OpenSubtitles.org

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/tikipeter.github.io#3]
Hi Tikipeter, how are you?

I assume you're familiar with the topic, but letting you know that OpenSubtitles.org old API is now officially deprecated (Since 01-01-2024):
https://forum.opensubtitles.org/viewtopic.php?t=17930
https://trac.opensubtitles.org/projects/opensubtitles

Well, it is still up and running, but returns valid subtitles only for VIP users (paid).
For non-VIP - it allows the subtitles search, but returns a static subtitle of:
![image](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/8b03a0ea-8d1e-487b-b76e-acb2a316bc53)

That is at least for all of different subtitles addons I've checked, and I was about to notify you about that (since it is available in Fen's code and settings):
![image](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/4a6867ac-546b-49bc-bb93-5050b340ee14)

But I was surprised to see that it still works through Fen, both search and download - and the subtitles is correct:

![image](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/bae97fb5-5c5d-4185-bfff-eb39191a292b)

![image](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/cd79d309-a051-44e2-80c4-2eaafc84c831)

I was wondering how it still works : ) and if you plan to keep this feature in Fen, or remove it due to OpenSubtitles is migrating to new REST API (which new requires user authentication with API keys)

Thanks!

**Comment by Tikipeter** [comment]
I may as well keep it whilst it's still working.

I figured it would be broken and I'd have to get rid of it soon enough. I've just had limited time lately to do much of anything.

**Comment by TwilightMercy** [comment]
I deep dived into it, and figured out that there 2 ways to use the old OpenSubtitles API:

1. XML-RPC Method - stopped working for everyone except VIP members. 
https://api.opensubtitles.org/xml-rpc

2. REST method - (used in Fen) - still working - I assume because you are using a free dedicated registered user agent for Fen? (Fen v1.0)
https://rest.opensubtitles.org/

For now it seems it will continue to work (until OpenSubtitles.org will REALLY get deprecated and only OpenSubtitles.com new REST API will stay online)
