### ISSUE TITLE
Fen/Fenlight category icons are not loading

### ISSUE THREAD

**Issue by devNaresh** [Tikipeter/tikipeter.github.io#31]
I am using Kodi on Android TV with latest kodi android version v21 (omega) and I noticed that FEN/FenLight categories icons are not loading. Here is the log with errors.
https://paste.kodi.tv/alimakehad

Here is the screenshot
![20240416_231514](https://github.com/Tikipeter/tikipeter.github.io/assets/6941048/e8f89793-a223-4766-909d-b453736ebe99)

**Comment by Tikipeter** [comment]
The images are served by imgur.

You seem to be having a network issue with imgur.

You are getting 429 and 22 errors.

**Comment by devNaresh** [comment]
Yes, at first I also thought it's a network issue and tried with another network but issue persist. I also have POV addon installed which is fork of FEN, there I am getting icons. This issue is not there in KODI windows because I am getting icons on kodi installed on my laptop in same network.

**Comment by devNaresh** [comment]
I did some more testing. Looks like issue with Android TV only maybe `imgur` is blocking API calls from android TV. It could be the user agent issue. Is it possible to add icons on package itself because earlier it was working work me, from last two weeks only I am getting this issue.
