### ISSUE TITLE
In Progress movies not updating the list

### ISSUE THREAD

**Issue by edjalmobf** [Tikipeter/tikipeter.github.io#32]
Hi!
So I'm having a issue with In Progress movies.
Let's say I have 3 movies in progress: movie A, movie B and movie C (in this order).
If I press play in movie C and watch it a little it will not be in first position at the list, will be in same order. The same will happen to movie B or movie Z.
Hope I'm clear.
Regards!
Fen Light 1.0.46

**Comment by Tikipeter** [comment]
Nothing I can do about that I'm afraid.

So far as I have seen, Trakt does not give fresh information when an already in progress item is updated with fresh in progress information.

It always returns the timsestamp of the ORIGINAL progress data, not the updated one.

**Comment by edjalmobf** [comment]
Right.
But how this In Progress works if user not connect with trakt account? There's no workaround?

**Comment by Tikipeter** [comment]
Are you not connected to a Trakt account?

**Comment by edjalmobf** [comment]
Yes, I'm connected to trakt account, I'm just trying find a workaround with you for when connected to trakt account (since you said that works in descent order when not connected). Title option doesn't work, because is it use like alphabetical order). 
It is possible to add a like third option like "fen progress"? If it possible when selecting this option it'll ignore trakt progress (and order) and use fen (as not connected to trakt) progress instead.

**Comment by Tikipeter** [comment]
You can use Fen Indicators instead of Trakt, yes.

It's in the General Tab under watched indicators.

**Comment by Tikipeter** [comment]
To be clear, the In Progress section WILL show Trakt progress in order of last watched in general.

The issue arises when you already have a resume point, and then you watch a little more and make another resume point. The timestamp supplied by Trakt when that is the case is the timestamp from the original resume point.

Apart from that issue, the Inn Progress menu will show movies according to last watched f you have it set that way.

**Comment by ryankeast** [comment]
> You can use Fen Indicators instead of Trakt, yes.
> 
> It's in the General Tab under watched indicators.

When I switch to using Fen light for watch indicators, my fen light widgets disappear oddly. When I switch back to Trakt they reappear again. Odd.

**Comment by Tikipeter** [comment]
It's not odd. They likely have no watched info. Any widgets related to watched info (In Progress, Watched etc) would be empty if you haven't used Fen Light indicators to mark anything as watched.

The options of Fen Light indicators or Trakt indicators are separate, Fen Light indicators are for people who don't have, or don't want to use, a Trakt account. They will keep their own watched and in progress history separate to Trakt.

**Comment by edjalmobf** [comment]
Yeah, but use fen watched indicator don't change the position of last watched.

> The issue arises when you already have a resume point, and then you watch a little more and make another resume point. The timestamp supplied by Trakt when that is the case is the timestamp from the original resume point.
I think the solution is to not connect the trakt account in fen light and just use the trakt add-on that Kodi have. I have to test that

**Comment by Tikipeter** [comment]
That is not a good solution.
