### ISSUE TITLE
Trakt TMDB Query

### ISSUE THREAD

**Issue by ryankeast** [Tikipeter/tikipeter.github.io#34]
So I am looking back into switching back to FenLight from Fen (still a bug that I can't select UK certification and the Special Seasons on view :-) but I can live with that ). 

What is the Trakt Client ID and Client Secret Id used for by Fen Light and also what is the pros of adding your own TMDB API key as opposed to the default one?

Many Thanks

**Comment by xyzfre** [comment]
Having your own TMDB API helps the addon ,think about how many people are using Fenlight that's how many request that one API gets a day.Not sure about the Trakt Client/Secret

**Comment by ryankeast** [comment]
Makes total logical sense now you say that. I may have to explore that. Many thanks for the explanation.

**Comment by Tikipeter** [comment]
The Trakt Client ID and Client Secret are values given by Trakt when you register an "app" with them. They are to be used with that app.

As such, much like the TMDb API that xyzfre has explained above, every install of Fen Light uses the same values for the client ID and client secret. Users can input their own values if they have them. They would get them by registering an "app" with Trakt.

These settings really hold no value currently, but will in the future, They are mainly so users don't NEED to rely on my keys being active, or someone else "forking" the addon with new keys, to continue using it into the future.

**Comment by ryankeast** [comment]
Thanks. I'll explore the Trakt option at somepoint. Appreciate the reply.
