### ISSUE TITLE
Integration with Up Next addon

### ISSUE THREAD

**Issue by vella9** [Tikipeter/tikipeter.github.io#39]
Dear @Tikipeter, 

I would like to ask if it would be possible to "integrate"/make compatible, fenlight with Up Next addon. I was [discussing](https://github.com/MoojMidge/service.upnext/issues/33) with the author and it seems that currently, this is incompatible somehow. 

I know that you already have "autoplay next episode" available built-in, however I am using a custom skin and I would like to keep the same "style" for the popup window.

Would this be possible please?

Thank you!

**Comment by Tikipeter** [comment]
Seems you got an answer from MoojMidge....

>If the plugin doesn't do what it should be doing to play a video, there is not much other plugins can do to integrate with it in a standard way.

Sounds like my addon doesn't "do what it should be doing to play a video". So the "Up Next" hack is not compatible.

**Comment by vella9** [comment]
> Seems you got an answer from MoojMidge....
> 
> >If the plugin doesn't do what it should be doing to play a video, there is not much other plugins can do to integrate with it in a standard way.
> 
> Sounds like my addon doesn't "do what it should be doing to play a video". So the "Up Next" hack is not compatible.

Fenlight is perfectly fine in my opinion, it's lightning fast for starters and videos play flawlessly. I have no complaints at all. Awesome job @Tikipeter.

I do not know the technicalities nor the efforts involved,  but it would be really nice to be able to integrate your addon with Up Next. It would improve the overall experience and compatibility. However, it is up to you.

Thank you for you time!

**Comment by vella9** [comment]
Hi @Tikipeter, sorry to disturb you again, I found this [link](https://github.com/im85288/service.upnext/wiki/Integration) if you are considering the integration. Thank you 🙏
