### ISSUE TITLE
Ability to call Extras with alternate menu due to slow down on skin

### ISSUE THREAD

**Issue by ChimmyJunga** [Tikipeter/tikipeter.github.io#41]
I am currently using Fen Light with the Arctic Fuse skin. When I replace the information window with extras using the option in the settings, it becomes extremely laggy because it tries to load the Arctic Fuse information window first. I’m not sure if this is really your problem, but perhaps it would be possible to change it or just add the extra window to another less essential action, like the picture info window. Then, you could add a tip telling people to use key map edit to add the action to a button. I have no idea if it works like that, of course.

Also, would it be possible to add the ‘Add to Trakt’ list directly to the first context menu window? My wife gets a bit confused with all the menus she has to navigate. All good if not.

Thanks for all the hard work

**Comment by Tikipeter** [comment]
Starting next update you can use `RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key_extras_menu_choice)` as the command to open the Extras dialog.

Also, `RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key_options_menu_choice)` to open the Options dialog.

**Comment by hcgiub001** [comment]
I love this. Could I please request having more commands.
Kodi has a long button action. So I'm thinking of using long Enter key for skipping extras and then skipping having to pick source. I still like that behaviour but imagine we can use the long enter to skip all that if we felt like it.
I don't even have to use long button, just a button that directly skips waiting and loads the movie instantly would be awesome. Thanks for your consideration. Even without it , Fen is just amazing!
