### ISSUE TITLE
Feature request. possibly allow to organise personal list in random order.

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#46]
First thanks for an amazing addon and your work over years. If possible could you please consider adding an option that allows us to organise our lists

right now it organise by title
we are allowed the following ways to organise
-rank
-updated date
-title
-likes
-comments
-items
-random

I would love if you can allow us to organise using random.
Thanks for your consideration and hope everything is well.

**Comment by Tikipeter** [comment]
You are going to need to explain yourself better.

What addon are you using?

What "lists" are you talking about?

From where are those lists sourced?

**Comment by hcgiub001** [comment]
oh sorry I wasn't clear. I'm using trakt
I've created personal lists in trakt and added my trakt account
then go on to
My Lists  -->  Trakt: My Lists 

Fen (not Fenlight) organises them using title. I'm not sure if it's even possible to organise them in any other way.
But when I change the list to "Random"

![Screenshot (13)](https://github.com/Tikipeter/tikipeter.github.io/assets/171574389/8c8b53ee-0e8f-4684-bd27-d011776c0cad)

trakt has "?sort=random,asc"
at the end of the url

I want to use FenLight, will be migrating over soon. so even if you can and willing to try on Fenlight, that would be awesome.
Thanks for quick reply

**Comment by Tikipeter** [comment]
Fen is retired so there aren't ever going to be any feature additions to that addon.

Fen Light has a couple of ways you could achieve randomness with your personal lists. If you read the 2 Tips (in the Tools menu) pinned to the top within the addon that are related to randomness, you can at least achieve a situation where a menu item will produce the contents of a random list from your personal lists.

**Comment by hcgiub001** [comment]
thanks for the reply. I made a shortcut folder for "Trakt My Lists" at root. I used context menu and wasn't able to find the option to make it random.
Although it selects a list by random, which is cool and I might make use of. It still doesn't give me the functionality I was hoping for.
It's too restrictive because I'm forced to open a list and I don't know the name of the list. Like maybe one day I feel like Action type movies. I have many lists with action theme so if I had a random list of lists I could keep scrolling until I find the theme I wanted. Also I have lists with over a 1000 items, this will take time to load, then if I didn't like that list I would have go back and refresh the list? then get a new random list, again I won't know what I picked.

I understand you'd have to add this into setting if you wanted and it would take time and maybe not many would use it. Is thir anyway I can change on my own end just to give me the random list? Maybe I can add "?sort=random,asc" somewhere in Fen code for myself? If not then It's okay. Still the best addon out their! you can just close the issue if it's not possible. thanks

**Comment by Arthur1967** [comment]
I was going to tell him that, but I thought I'd let you

**Comment by Arthur1967** [comment]
Fenlight works perfect just switch to that

**Comment by hcgiub001** [comment]
> Fenlight works perfect just switch to that

fenlight is way better. The only reason why I said Fen was because I tried installing it on kodi v20 on my Odroid Corelec. I still use that so I can use a skin I like. and for some reason fenlight wasn't installing. I don't think I tried hard enough or remember what happened so I stuck with Fen which worked. I was meaning to see if I can install fenlight again but Fen was working good so I left it. Once I try again and if It's not installing I will let Tikipeter know.

**Comment by hcgiub001** [comment]
I have a suggestion. At the top of a list can we have a toggle option. This way we can easily toggle lists in many ways?

**Comment by Tikipeter** [comment]
Settings->Content->Content->"Shuffle Order of Personal/Liked Trakt Lists"

**Comment by hcgiub001** [comment]
> Settings->Content->Content->"Shuffle Order of Personal/Liked Trakt Lists"

this is pretty awesome and fast. Thank you so much. 
There are 2 behaviours that I've noticed that can be improved.

1/ Lists are shuffled when entering the 
i) My Lists --> Trakt My Lists 
ii) select a list then return back to lists of list

behaviour 1/ ii) means if I'm browsing through lists of list and entering one list and coming back to my big list, I have a chance of seeing the list I already seen. Also at a glance I can see what new lists I will look at , then when I enter a list and come back I missed a list that I wanted to explore (if that makes sense)

can you not shuffle the list on 1/ ii) and only have the list shuffle on 1/ i) please?

one other suggestion which makes sense, if I exit "Trakt My Lists" and then click on it again. The lists are shuffled which is awesome and the last list I was on is highlighted. But It's not right at the top. it remembers the amount of lists I went through and puts me down their. This doesn't work since what if you went through 9 out of 10 lists. then exit Trakt lists and re enter. you only have one option of lists you can search this way.

So If I may , I'd like to suggest if we exit Trakt My lists, and re enter. The list that is highlighted should be at the top.

Sorry for asking to many things. If you can look at just one thing I would love if you can look at my point 1/

honestly thanks so much it's close to being awesome!

**Comment by hcgiub001** [comment]
Thank you so much for the update, working perfectly now!
