### ISSUE TITLE
Fen Light episode matching regex

### ISSUE THREAD

**Issue by ghost** [Tikipeter/tikipeter.github.io#48]
A few updates ago, the additional episode regex check that I posted on Reddit was added into Fen Light as string7.

I have come across a mismatch caused by it. The file `.biraru.chis.new.address.-.001.dvd.576p.10-bit.x264.ac3.690d22ee.mkv`, which is episode 1, matched my search for episode 10 because of the 10-bit part. 

The fixed regex is `(^(?=.*\.e?0*<<E>>\.)(?:(?!((?:s|season)[.-]?\d+[.-x]?(?:ep?|episode)[.-]?\d+)|\d+x\d+).)*$)`. This simply removes hyphens as an acceptable character before and after the number, and I don't think there's any real instance of hyphens being used that way.

**Comment by Tikipeter** [comment]
Thanks ghost. I'll look into this.
