### ISSUE TITLE
[Improvement] FEN "In Progress" Movies Sorting

### ISSUE THREAD

**Issue by ilMike42** [Tikipeter/tikipeter.github.io#5]
Hey!

I installed FEN Light today and I found out that the "In Progress" Movies section is sorted alphabetically. I think that the most natural way is, instead, sorted by last watch. 

Is there a chance to make the setting customizable?

Thanks in advantage.

**Comment by Tikipeter** [comment]
Huh?
"Recently Watched" is the same as "Last Watched" 
Just use that setting.

**Comment by ilMike42** [comment]
I think there is a misunderstanding. In FEN light, in the Movies section, there is a "In Progress" subsection, with the started but not finishedd movies. Now, this section is sorted alphabetically, but I think that the most natural sort for the section could be using the "added date" sorting. I was wondering if could be possible to add a setting or a different version of that section, using that sorting

**Comment by Tikipeter** [comment]
The setting is already there.

Did you not look first?

**Comment by ilMike42** [comment]
I swear I searched in tools and settings, but somehow I missed that in the navigation tab.

Thank you for your work, and sorry to have bothered you opening the issue.
