### ISSUE TITLE
YouTube trailer loading slower on first click on extras screen compared to clicking second time on extras screen

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#50]
Hey Tikipeter.

Actions I take:

Add-ons - Fen Light - My Lists - Trakt My Lists - Comedy - (x323) - Little Man

Extra list loads up

press trailer button.

I have spinning animation for 3 seconds or so then no spinning animation, one more quick one that last a fraction of a second the YouTube video loads

then I exited the trailer

went lower down to recommended and found another movie (white chicks) - clicked it

this time when I clicked the trailer, it was a fraction of a second with spinning animation, then nothing then fraction of a second spinning animation and trailer loaded.

I did more testing and it doesn't matter if I pick the tailer of the movie from my list first or if I click on my movie (from my trakt list) and pick a recommended movie and pick that trailer first, the first trailer  I pick from going into extras screen is a massive slow down to load a YouTube trailer.

I added a log here
https://paste.kodi.tv/oricasedix

windows 11 23j2 (kernal: Windows NT 10.0.22631.3737)

I used fentastic skin but same issue happens with estuary skin too.

I actually did a reinstall of kodi and I didn't feel the trailers where slow to load  before but definitely notice them now (first load). Not sure if you anything can be done, but worth letting you know. Thanks for reading this

**Comment by Tikipeter** [comment]
I have zero input into the coding of the youtube addon.

**Comment by hcgiub001** [comment]
I understand, but wanted to ask if you are aware that the first trailer you click. their is like a 4 second delay compared to picking a trailer a second time, while not closing Extras menu (and picking one from recommended or any other list)?

**Comment by Tikipeter** [comment]
No. I was not aware.

**Comment by hcgiub001** [comment]
yeah I'm bad at explaining things. Have extras enabled, then click on a movie. click on trailer and you will have a 4 second where it's doing something then it plays a trailer. BUT once the trailer is finished or you exit the trailer and you don't exit extras menu but go further down and select other movies that are given in recommended or other options and then click trailers in those movies, it's no delay whatsoever. so I haven't exited Extras menu. 

Once I exit extras menu and pick another movie from my list. I get the delay again. 

The delay on first movie isn't to do with the movie I picked. it's any first movie I pick once I'm in the extras menu, so I can pick a movie and find a movie from recommended section and pick trailer, if this was the first time I picked trailer while in extras, you'll have a 4 second delay

**Comment by hcgiub001** [comment]
I'm not sure if anything could be done about  the trailers from YouTube but I REALLY LOVE the videos option in extras. 
Any chance you can a command that plays the first video at highest quality?
That would be super amazing! I will keymap that to the right button on my remote, since I don't use right button once I'm in my lists. Also the video trailers in fen are instant.
wow that would make searching for movies such a nice experience. easy one click trailers. 
That would make Fenlight even more awesome!

**Comment by Tikipeter** [comment]
I undetstood what you were saying.

But I have no control over how long it takes to start playing a video from YouTube.

**Comment by hcgiub001** [comment]
I'm not sure if it was on my end. I had a new update for Fenlight and it's instant now. I think I had to complete youtube wizard. now it's perfect. can I ask a big favour. I like having extras menu and pick my source, but some times if I'm lazy I'd like to map a key to pick the first source for me. If it's not possible all good. I pretty much only use Fenlight and Fentastic and it's bloody awesome!
