### ISSUE TITLE
Feature Request. open the Extras Menu with movies that belong to a collection

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#51]
Please disregard if you aren't accepting any feature request.

Some movies belong to a collection, these can be obvious if they have a number indicating the movie in the collection
but some don't.

Here is an example
![Screenshot (20)](https://github.com/Tikipeter/tikipeter.github.io/assets/171574389/0402eadd-3def-4911-a6a2-e7b8436e6045)

For those who don't load up extras will have no idea their is a movie before it or a movie after it in a collection.
So I propose to have a setting.
If a movie belongs to a collection
The extras menu is loaded and shows like
![Screenshot (21)](https://github.com/Tikipeter/tikipeter.github.io/assets/171574389/ee15d2ba-f3d5-4d53-a22c-3f55370fd511)

(normally to get to this screen I click extras then I click up)
This way users are notified their are other movies in the collection. they can go to the first in the collection if they haven't already viewed or once they finish the movie they are on they can see if their is a movie after in the collection.

Seems very intuitive and already links in with how you have setup Fenlight.
If you can think of another way to alert users on to the fact their is a collection, you don't have to go with this method.
Thanks for your consideration

**Comment by hcgiub001** [comment]
here is another example that I would not have had a clue that it belonged to a collection
![Screenshot (22)](https://github.com/Tikipeter/tikipeter.github.io/assets/171574389/b1d1e147-9dd9-405f-a830-311b28bb5ecf)
this has 11 in the collection and the movie I clicked on was 9th but their is no way to know it's part of a collection except if you actively search on each movie. If I had a setting that automatically loaded the extras and had focus at the collections part, this would really add to the experience
![Screenshot (23)](https://github.com/Tikipeter/tikipeter.github.io/assets/171574389/684dd11f-aedc-4300-8bb2-8a70413200d1)

**Comment by Tikipeter** [comment]
Next update will have "Browse Movie Set" in the context menu of any movie that is part of a set. Select that context menu item, and the movies belonging to the same set will be shown.

If the movie is not part of a set, then the context menu item will not be available.

**Comment by hcgiub001** [comment]
I appreciate you willing to add this, but the issue is some movies you won't even know if it is part of a set. If someone is interested in a movie and clicked on the movie to load source select screen, could we not just go straight into a screen that shows all movies.

have  an option in setting
-load the collection if a movie is part of a collection 

this way if I have a list, I can navigate the list without having to keep bringing up context menu and also I can focus on the collection.

I've asked the dev of FENtastic to give an indication if a movie belongs to a collection . so if a movie is 2nd out of 5 movies in the collection. we have 2/5 C
somewhere. I have a feeling this feature will be standard for those wanting to browse collections inside movies and make it very simple. most people don't bother with context menu items. please will you re consider? instant loading of a collection will be awesome and sometimes surprise people.

**Comment by hcgiub001** [comment]
Hey Tikipeter, I like your new feature. I just want to show some movies are not clear that they are part of a collection and you might have not known like this collection
![Screenshot (34)](https://github.com/user-attachments/assets/b94039c7-0fc2-414d-a5d8-585fe2f12308)
![Screenshot (35)](https://github.com/user-attachments/assets/4c0bce7c-c54d-4851-ac60-1b4b777bad7c)
and to click on "browse movie set" you have to click 4 buttons to it.
before I mapped       RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key_extras_menu_choice)
to left key and then pressed down to get to collections. so I wouldn't use to context menu to get to 

Please could we have a settings option that "automatically browse movie set".
people use trakt liked lists or go on lists they are not familiar with, so they might not be aware that it's part of a set, it would be awesome if we could start the set from the beginning and have the pleasure in watching all the set like a mini show, it's lamost perfect how you done it and fast. just this setting in FenLight would be so helpful.

**Comment by hcgiub001** [comment]
Just from my Trakt list I checked and many movies are part of a set like here
![Screenshot (40)](https://github.com/user-attachments/assets/e7218556-2fc1-4e95-b914-eda6835ab782)
![Screenshot (39)](https://github.com/user-attachments/assets/1b9887da-76dd-427c-a29d-6aa749dec34e)
![Screenshot (41)](https://github.com/user-attachments/assets/3f5e027a-e5f5-42d2-b636-fdfba722023a)
That's 3 sets in a row but you would have to press context menu on each movie to find out if it's part of a collection then press back if it's not. You could have loaded extras menu already to accomplish that. Just the ability to have it automatically would really benefit and add to watching movies and sets. Without it being automatic, it doesn't add anything extra that we had before
