### ISSUE TITLE
Feature Request: Allow Sorting of Extras content

### ISSUE THREAD

**Issue by ggefen** [Tikipeter/tikipeter.github.io#53]
Hello Tiki,

As the the title states, it would be great to have an option for sorting the Extras content. For example, I’d like to have Cast show at the top without having to disable Plot. I would also like the Videos section to show after Cast.  Sorting would help resolve this.

Thank you for considering this.

**Comment by Tikipeter** [comment]
This would be a TONNE of work.

I simply don't have it in me at this point in time. I'm only spending maybe 2-3 hours a week on Fen Light at the moment.

I have almost no interest in the addon.

I don't even use it myself.

**Comment by hcgiub001** [comment]
It's crazy you don't use it and still spend 3 hours a week. No one will blame you if you want to retire. you've done lots already and you should look after yourself and your loved ones, plus put your health first.

**Comment by ggefen** [comment]
Hey tiki,

I totally respect your answer. What do you use for your own media consumption?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
