### ISSUE TITLE
Feature request : Hide Unaired Watchlist media

### ISSUE THREAD

**Issue by nascar999** [Tikipeter/tikipeter.github.io#55]
Would it be possible to add an option to hide unreleased Movies / Shows in Trakt Watchlists? I believe it used to be an option under Content in Fen, but have not found this feature in Fen Lite. Hiding unaired on Trakt.tv did not seem to translate to Fen Lite. 

![image](https://github.com/user-attachments/assets/8e8f7599-7908-4515-9879-36695f50fdb8)

Thank you so much for your consideration and with the addition of the random sorting within the Trakt lists, this is great!

**Comment by xyzfre** [comment]
@Tikipeter Put so much work into Fen till this day still works flawlessly OG Fen❤️💯❤️
