### ISSUE TITLE
Fen Lite 1.0.60 has locked my configuration

### ISSUE THREAD

**Issue by randorec** [Tikipeter/tikipeter.github.io#57]
Auto updated to Fen Lite 1.0.60. Received error message that the upgrade was not applied. Now showing 1.0.59 and my configuration page is locked.

**Comment by Tikipeter** [comment]
What configuration page?

If so the update failed, just do it manually through the Tools menu.

I'm assuming you've at least restarted the device to troubleshoot beforehand of course.

**Comment by randorec** [comment]
Yes, I did restart. I  was referring to Information -> Configure from the Addons screen and context menu on the front page. Configure is greyed out. If this is normal behavior and I didn't notice, then nevermind.

---------- Original Message ----------

**Comment by Tikipeter** [comment]
Normal behavior.

Fen Light uses (and always has used) it's own custom settings window.

It is accessed through Tools within the addon

**Comment by randorec** [comment]
Thank you. Apologies for the false alarm. The update also completed. Was the change in icon necessary? I view entertainment to get away from divisive politics. I don't need a reminder on my home screen.

---------- Original Message ----------

**Comment by Tikipeter** [comment]
After what just happened to him; yes, it was necessary.

There should be nothing "divisive" about that. Unless you wanted what happened to be successful I suppose.

The "hat" will be gone next update.

Either wait until then or uninstall the addon.

**Comment by randorec** [comment]
Look, just because someone doesn't want to be confronted with a particular political ideology on their entertainment platform doesn't mean that they want harm to come to anyone. Your logic is as flawed as the person who took the shot.

---------- Original Message ----------

**Comment by Tikipeter** [comment]
It's not possible for me to care any less about what your, or anyone else's opinion, is on this.

If you can't put up with a hat on an icon until the next update, uninstall the addon.

Keep arguing with me about this, you'll be banned. I don't want to hear any of it.

End of discussion.

**Comment by randorec** [comment]
To be clear, my last message was a response to your implication towards me regarding the shooting, which was an insult. If you hadn't done that, I wouldn't have responded. Ultimately I don't care about the red hat, your political affiliation or whatever. I simply asked a question. Do whatever you like in response to this message.

---------- Original Message ----------

**Comment by Tikipeter** [comment]
> Ultimately I don't care about the red hat

Really? You did 2 messages earlier.

The "you" in "Unless you wanted...." was not used as in you personally. It was used generally when forming a hypothesis of why someone might find supporting someone who had survived what he did "divisive".

The whole thing disgusts me, as does the reactions to it. Humanity at it's worst.

**Comment by xyzfre** [comment]
To be honest I love the icon hat you should keep it up there it looks great😁,, thank you @Tikipeter for all your amazing work true (LEGEND)
