### ISSUE TITLE
Feature request: setting a property for all movie items

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#59]
@ivarbrandt (FENtastic | Nimbus skin creator) thinks "Browse Movie Set" option is cool

> Yes I tried it earlier today, very cool indeed."

right now a user might not be aware the movie is part of a collection so I've asked if he'll consider having some indicator that users will be aware the movie is part of a collection, he's willing to consider but told me

 > We still won't know whether or not a movie is part of a set until we get to the context menu. This could be fixed by setting a property for all movie items and then I can use that to display a small image that tells you it belongs to a set.

Would you consider adding this so Nimbus could add an indicator to make users be aware a movie belongs to a set so they can take full advantage of Fenlight feature?
I also think it would be cool if we had something like this

![final form](https://github.com/user-attachments/assets/58b89179-4082-423b-8714-b412c7d51b6b)

ivarbrandt said their isn't enough space for the icon but likes it so might make use of it, but the image below has the icon in blue, this represents their is a movie in the collection the user hasn't seen (you might not be aware if you have seen all the collection or if a new movie in the collection has come out), the icon in white means all movies in the collection have been seen.
2.4 represents the movie is 2nd from a collection of 4.

Is it possible Fenlight can pass this information to Nimbus so it can have this function?

If you'll consider this can you also have a path to "browser Movie Set",
(like you did with extras menu    RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key_extras_menu_choice)) 
 Nimbus is a cool skin, if you press down on a movie you have a poster view of all movies in the list but I'd like to have a feature that when I long press down, it automatically loads into collections.
and then ask ivarbrandt to add this command as part of Nimbus skin.

So now users will be able to see if a movie is part of a collection, the order of the movie and the size of the collection, further more they'll be able so see if their is a movie in the collection they haven't seen so it invites them to explore and a very intuitive and easy access to collections menu by long pressing down, which ties in well with the icon (a folder below another folder which comes into view, so pressing down brings collections menu into view)

Fenlight + Nimbus would be awesome and a paradigm shift in how a movie is considered an element of the list or a list inside a list (or a set).

Thanks for your consideration and hope you guys can make an awesome feature possible. :D

**Comment by Tikipeter** [comment]
Almost none of what you want is really possible I'm afraid.

It is easy to add a listitem property to alert when the movie is part of a collection, but the other information (movies in collection and number of movies in collection) is not possible with the information provided by TMDb at this point. There needs to be another call to TMDb to get the details of the collection.

So, you could have an icon display that lets you know that the movie is part of a collection, but it would not have any of the other details.

I can set a listitem propoerty `belongs_to_collection` for movies, that can be used by a skin.

Ivarbrandt can also use 
```
data['belongs_to_collection'] = 'true' if next((i for i in json_data.get("keywords", []) if i['name'] == 'belongs-to-collection'), None) else 'false'
```

using MDbList to get the value. Unfortunately, again, this only provides information to say the movie is part of a collection, not the number of movies in the collection or what those movies are.

**Comment by Tikipeter** [comment]
I'm also not 100% confident that the keyword `belongs-to-collection` can always be relied upon to be set for each movie that is part of a collection, meaning checking for the listitem property first would be the best way to go. Then fallback to the info MDbList is providing.

**Comment by hcgiub001** [comment]
thanks for working on this, even if we can get a little icon that shows it's part of a list would be awesome, the rest was icing on the cake, I'll check with Ivarbrandt to see if that is possible now. Thanks Tikipeter

**Comment by Tikipeter** [comment]
1.0.62 is setting the correct listitem property for any skin that wants to use it.

**Comment by ivarbrandt** [comment]
Sickkk dude. I'll look into implementing MDbList info for collections. I might just check for the listitem property though and just leave it at that, especially if that's where you're getting the data from to set the property.

Now the hardest part, where to put that icon lol

**Comment by hcgiub001** [comment]
Thanks Tikipeter, looking forward to see ivarbrandt comes out with :D

**Comment by ivarbrandt** [comment]
After testing out an implementation of this feature, I realized that I don’t like the way that it looks in Nimbus. It makes the artwork look tacky and cluttered, and that takes away from the functionality and appeal of the feature. I won’t be implementing this into the skin.

That being said, Peter, I would really like it if you kept the Browse Movie Set functionality because it’s 🔥.

Thanks for your efforts man. Appreciate ya always.

**Comment by hcgiub001** [comment]
> After testing out an implementation of this feature, I realized that I don’t like the way that it looks in Nimbus. It makes the artwork look tacky and cluttered, and that takes away from the functionality and appeal of the feature. I won’t be implementing this into the skin.
> 
> That being said, Peter, I would really like it if you kept the Browse Movie Set functionality because it’s 🔥.
> 
> Thanks for your efforts man. Appreciate ya always.

was worth a try lol. thanks for trying it out and yeah I understand your philosophy on Nimbus.
and thanks Tikipeter for this functionality, maybe one day it would be adopted. and yeah I love the browse move set.

**Comment by Tikipeter** [comment]
>After testing out an implementation of this feature, I realized that I don’t like the way that it looks in Nimbus. It makes the artwork look tacky and cluttered, and that takes away from the functionality and appeal of the feature. I won’t be implementing this into the skin.

Was always going to be hard to fit it in and make it look good.

>Appreciate ya always.

Right back at ya. :)

**Comment by hcgiub001** [comment]
not sure if you are aware Tikipeter but this was added to Nimbus
![Screenshot (292)](https://github.com/user-attachments/assets/317d2485-b780-48fa-bc28-21e6ab2735cb)

I've seen one person really liking this and wanted it in other addons to, so it seems it was worth the effort. Just thought I'll let you know. thanks
