### ISSUE TITLE
Re-Auth Trakt Pop Up won't go away 

### ISSUE THREAD

**Issue by gratefulshag** [Tikipeter/tikipeter.github.io#6]
Hi. For the past week or so I haven't been able to clear the "Re Authenticate Trakt Access" notification, it pops every 10-15 minutes or so. I have de-authed and re-authed multiple times, I have also uninstalled and reinstalled Fen with no luck. Everything else works fine, lists, calendar, etc. The notification just won't stop popping up. Any help would be appreciated. Logs posted below. Thanks! 

https://paste.kodi.tv/mumigasipo

**Comment by Tikipeter** [comment]
Are you sure that's a message from Fen?
