### ISSUE TITLE
Resuming play

### ISSUE THREAD

**Issue by matthius7** [Tikipeter/tikipeter.github.io#60]
Using Fen lite and Arctic fuse. If I go to start a show it scrapes cloud first as by my settings finds a scrape . Plays perfectly. Going back later to resume and try and play it fails. I've found a work around. Long press on the show > options> clear scrapers cache. Then click on show and it rescrapes and resumes my progress perfectly. Hope your doing well Peter missed you on Reddit. Using latest version of Fen lite on Chromecast 4k and stable omega 21

**Comment by hcgiub001** [comment]
recreate the error then go into 
Tools - Changelog & Log Utils - Upload kodi Log to Pastebin.

makes the developer life easy if they can see in code what's happening

**Comment by matthius7** [comment]
> recreate the error then go into Tools - Changelog & Log Utils - Upload kodi Log to Pastebin.
> 
> makes the developer life easy if they can see in code what's happening

Done. Thank you for this. Learning daily

**Comment by hcgiub001** [comment]
> > recreate the error then go into Tools - Changelog & Log Utils - Upload kodi Log to Pastebin.
> > makes the developer life easy if they can see in code what's happening
> 
> Done. Thank you for this. Learning daily

no worries but when it's uploaded, you'll get a url, please post the url here, the url shows the logs of the error :)

**Comment by matthius7** [comment]
https://paste.kodi.tv/yexubecoma

**Comment by matthius7** [comment]
And may I add that it's mainly happening in my "next episodes " widget.

**Comment by Tikipeter** [comment]
What do you have "Automatcally resume playback" set to? Be careful to check the correct media type (movies or episodes).

**Comment by Tikipeter** [comment]
I've tried every combination of Autoplay and autoresume coming back to a pre-scrape result from the RD Cloud, and unfortunately resuming has worked every time.

**Comment by matthius7** [comment]
> I've tried every combination of Autoplay and autoresume coming back to a pre-scrape result from the RD Cloud, and unfortunately resuming has worked every time.

Ok . Thank you for checking it out. Means it's something in my setup. Been wanting to do a fresh start anyway for a while.  This qualifies as a good enough reason. And I love to tinker.

**Comment by matthius7** [comment]
> I've tried every combination of Autoplay and autoresume coming back to a pre-scrape result from the RD Cloud, and unfortunately resuming has worked every time.

https://www.dropbox.com/scl/fi/5h7p17cngdfdesint5djo/VID20240723102713.mp4?rlkey=u34so7w4ie6coezxeu52gje15&dl=0

I wonder if it's because I have check Rd cloud . Or check before full search. ?

**Comment by matthius7** [comment]
Ok Im almost positive I've figured it out. On Arctic Fuse I made all my widgets with Fen lite. Next episodes,in progress episodes and in progress. After I made these widgets in TV shows I created a submenu widget. Popular,most collected ,airing today genres so on and so forth. But first I deleted many categories here to make the submenu stacked widget faster smoother. Including next episodes ,progress episodes. I've restored all these categories under TV shows and everything is working as it should. Not happening at all now.

**Comment by Tikipeter** [comment]
I suppose we can chalk it up to Kodi being weird, but that's about it.

Nothing to do with what widgets you have/don't have, or the contents of said widgets, will have anything at all to do with whether resuming playback works correctly or not.

In saying that, I'm glad it's working again. :)

**Comment by matthius7** [comment]
> I suppose we can chalk it up to Kodi being weird, but that's about it.
> 
> Nothing to do with what widgets you have/don't have, or the contents of said widgets, will have anything at all to do with whether resuming playback works correctly or not.
> 
> In saying that, I'm glad it's working again. :)

Started happening again. Set up Fen in the same fashion instead of fen lite and it's doing the same :(

**Comment by Tikipeter** [comment]
>Set up Fen in the same fashion instead of fen lite and it's doing the same

>Fen still works fine

I'm afraid it's nothing to do with either addon. There's something funky with your setup.

`Running on Google Chromecast with Android TV 12.0.0 API level 31`

Oh, that doesn't give much of a chance for things to work how they're supposed to. This is a terrible device to run Kodi on. I'd be running Stremio on that hardware.

**Comment by hcgiub001** [comment]
It's well worth getting the right hardware to run Kodi, I recommend this thread to see what might work for you
https://forum.kodi.tv/showthread.php?tid=376035
everything should work better plus you should find things snappier.
I paid like £90 for my Odroid N2+, over 2 years ago, been solid and worth every penny. damn thing still not gone under that value after all this time.

**Comment by matthius7** [comment]
> > Set up Fen in the same fashion instead of fen lite and it's doing the same
> 
> > Fen still works fine
> 
> I'm afraid it's nothing to do with either addon. There's something funky with your setup.
> 
> `Running on Google Chromecast with Android TV 12.0.0 API level 31`
> 
> Oh, that doesn't give much of a chance for things to work how they're supposed to. This is a terrible device to run Kodi on. I'd be running Stremio on that hardware.

In the process of getting another streaming box. I feel like with the removal of magnetDl in CoCo scrapers this might possibly have caused the issue for me as I had it selected as a torrent since I've had Kodi setup. I dunno. It was removed last update . Can see in changelog of Coco scrapers. Any settings or changes I could make in that area that you know that might help. ?

**Comment by matthius7** [comment]
All prior issues are resolved after Coco scrapers updated to v1.0.23 and magnetdl was added back !! Fantastic. Thank you guys and here I was about to perform a fresh start and wipe away a year and a half worth of data to try and fix.
