### ISSUE TITLE
[Feature Request] Add option to Hide fenlight + Rd "Scrape" and make it into logo. Umbrella + Rd can make scrapping into just a logo progression.

### ISSUE THREAD

**Issue by shanestonk** [Tikipeter/tikipeter.github.io#61]
![image](https://github.com/user-attachments/assets/6f46b19b-bf3b-414e-84c0-e9e5464cad91)

**Comment by Tikipeter** [comment]
The image posted seems to have very little to do with your request. That image looks like an old version of Fen.

Either way, I have zero interest in offering a "logo progression" instead of a scrape dialog.

Me not knowing what the hell a "logo progression" is doesn't help either.

**Comment by shanestonk** [comment]
> The image posted seems to have very little to do with your request. That image looks like an old version of Fen.
> 
> 
> 
> Either way, I have zero interest in offering a "logo progression" instead of a scrape dialog.
> 
> 
> 
> Me not knowing what the hell a "logo progression" is doesn't help either.

here the thing i would like request an option to hide it.

![image](https://github.com/user-attachments/assets/b2743a53-94b4-4d91-b0ff-42b1d595cc42)

![image](https://github.com/user-attachments/assets/2617625c-3082-4189-aad5-75ad434c6a81)

**Comment by matthius7** [comment]
Why would you want to hide this info. This is valuable info as to what's going on. Format,size,audio. Only stays a quick min anyway.

**Comment by shanestonk** [comment]
> Why would you want to hide this info. This is valuable info as to what's going on. Format,size,audio. Only stays a quick min anyway. 

My tv when someone who not it savy come to my house and see this they feel like it look cheap. if we can hide the dialog info it can look more polish streaming app. something like netflix or streamio. In my country if we put this at public and the dialog show eg torrent link if there a government IT department official see ot they can confiscate the box and issue court summon. They hate torrent so much even though it just real debrid link. i wish if they an option to hide it so if user want it they can enable the dialog and if got user dont want it can disable the dialog info.

**Comment by matthius7** [comment]
Do away with Kodi and the add-ons and get Netflix,HBO Max to hide this info then. Maintaing these add-ons are typically done for proper functioning and not so much the aesthetic appeal. Or keep your TV off if you have people at your house that could cause issues with your setup. I'm guessing.

**Comment by ivarbrandt** [comment]
> My tv when someone who not IT savy come to my house and see this they feel like it look cheap. if we can hide the dialog info it can look more polish streaming app. something like netflix or streamio. In my country if we put this at public and the dialog show eg torrent link if there a government IT department official see ot they can confiscate the box and issue court summon. They hate torrent so much even though it just real debrid link. i wish if they an option to hide it so if user want it they can enable the dialog and if got user dont want it can disable the dialog info.

I have so many questions but I'm gonna refrain from asking.

**Comment by Tikipeter** [comment]
Sounds like you'd be better off using Umbrella.

**Comment by Tikipeter** [comment]
It also sounds like you're getting "Kodi Boxes" ready to sell, and are trying to keep out of trouble whilst doing it.

**Comment by xyzfre** [comment]
> It also sounds like you're getting "Kodi Boxes" ready to sell, and are trying to keep out of trouble whilst doing it.

I was definitely thinking the samething earlier.💭
