### ISSUE TITLE
feature request: "open list outside extras"

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#64]
this is a continuation of the feature you made "open movie collections instead when available"
the feature request is to have a toggle in settings that when enabled opens any list outside an extra so for example
![Screenshot (116)](https://github.com/user-attachments/assets/1a88595e-4a37-4348-ad29-313dbc07bf61)
here you have "more from year", "more from genres"
if I click on an item that belongs to "more from year"
I would like the whole list to be displayed normal outside extras. then when I press back, I go back to the extras page
if I browse through the list (outside extras) , wherever I am when I go back it should still highlight the item I was on

so I can enter the list outside extras on one movie but come back and it's highlighted to another movie.

reason why this would be a good feature.
it's much easier to search outside extras. skins like Nimbus allow for automatic trailers, and other fancy artwork while browsing through a list.

if a movie is part of a collection in a list then we have access to your latest feature "open movie collections instead when available"

I've really liked finding new movies from actors but I find the extras menu to restrictive and I can't browse as nicely as outside extras and seeing you implement the new feature It hit me, why don't we have any list in normal view.
now extras is more of an intermediary that links everything but opening the lists you can use skin features not available inside extras panel.

thanks for your consideration 
(this if implemented will be a toggle for users to choose to have on)

**Comment by hcgiub001** [comment]
this feature would mean you can even get rid of "browse recommended" from context menu. Just like you removed the browse collection set from context menu
it's all integrated in extra menu, which makes more sense than being inside context menu, also some people are not aware on how to bring up context menu on small remotes. (I only recently found out it's long press return)

**Comment by Tikipeter** [comment]
Not possible to go into a custom window like Extras and then into a Kodi window, and then back into a custom window etc.

That would be a nightmare, and almost impossible to implement. Kodi simply doesn't give us the tools to do something like that.
