### ISSUE TITLE
Bug: "Open Movie Collections when available" trailer exit, selects movie I entered collections with

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#65]
I'm using FENtastic. 
I've mapped this to one of my keyboard keys (right) to open trailer
      <right>RunScript(script.fentastic.helper, mode=play_trailer)</right>

Once I enter a collection set (outside extras menu) and load a trailer, after it stops it will highlight the movie that I entered the collections screen. I can load any trailer from the collection but after it finishes it will highlight just that one.
Hope this could be fixed

Thanks

**Comment by hcgiub001** [comment]
just checked Nimbus, if you go on skin settings, trailer and set a key to load trailers, then when I activate that key in collections page and exit, the selection will be on the movie that I entered the collections page with

**Comment by hcgiub001** [comment]
another behaviour that isn't as expected is if in Nimbus skin, you have automatic trailers and go into collections page, the trailer will load and won't change selection but if I press left or right to highlight another movie, the automatic trailer won't be triggered

**Comment by Tikipeter** [comment]
I'll remove the auto focus of the movie used to enter the collection folder.

It's not possible to have it work properly in all circumstances.
