### ISSUE TITLE
Feature Request: Add IMDB "More Like This"

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#67]
TMDB recommendations for "The Garfield Movie"
[2024](https://www.imdb.com/title/tt5779228/releaseinfo?ref_=tt_ov_rdat)"

![Screenshot (145)](https://github.com/user-attachments/assets/84e8fd20-798a-4872-acd8-fc27e83d06bd)

IMDB recommendations for "The Garfield Movie" (aka More Like This)
<img width="1280" alt="new 1" src="https://github.com/user-attachments/assets/57e691ae-b7b0-4f65-8d2a-05b9a6bb67fe">

Gets worse when we look at foreign content (And better for IMDB)

here is the recommendation for this movie
![Screenshot (156)](https://github.com/user-attachments/assets/6d03fa64-9452-439f-9cda-3d313ef58b45)

![Screenshot (157)](https://github.com/user-attachments/assets/d3c3d152-bbd4-4106-be5c-a00106b00a02)

seems like some random movies, don't understand the theme to the movies
 and this is what IMDB shows for the same movie

<img width="1280" alt="nest 666" src="https://github.com/user-attachments/assets/928be6a5-9630-4c42-8411-1c6c0f3278c6">

I've come across some foreign movies that don't even have recommendations in TMDB

this happens everytime. even for hollywood movies the recommendations are so bad.
I've seen this for a decade, nothing comes close to the algorithm and data that IMDB are using, and no ones come close in a decade of trying. considering foreign movies is a no go with TMBD recommendations.

Recommendations are important experience in finding new content, most people seen the same old content.
I had this issue about 3 years ago and asked the dev of Diamond Info_MOD (https://github.com/henryjfry/repository.thenewdiamond)
to see if he can add IMDB, he so the value and was able to add it.

<img width="1280" alt="next next" src="https://github.com/user-attachments/assets/0b8ca8a9-a574-464d-af9f-fd94ab2d9f44">

I've been using Diamond Info_MOD but to get to recommendations is so many clicks and so much waiting, plus once I click on a movie  I lose the information screen and have to start over.

So I was hoping you could some how implement the IMDB recommendations into your awesome FENlight (which is the only addon I use). not sure how your extra screen works, it's so damn fast, but if you could work your magic to scrape the imdb recommendations fast then wow that would be awesome.

I really hope you would consider this, right now I don't use recommendations, it doesn't provide much value.

(P.s. not sure if you used Super Favourites back in the day but it used iRecommend which I asked the dev to include which again scraped IMDB recommendations)

Thanks for your consideration

**Comment by Tikipeter** [comment]
I cannot see the IMDb recommendations within the Diamond Info window, but logging them in the code I can see that there are always 13 results from the query. Does that match with what you see?

**Comment by hcgiub001** [comment]
yes IMDB seems to give a maximum of 12. Diamond information for some reason repeats the first entry.

[The Garfield Movie (2024) - IMDb](https://www.imdb.com/title/tt5779228/)
https://www.imdb.com/title/tt5779228/

[Martial Universe 1: Immortal Stone of Nirvana (2020) - IMDb](https://www.imdb.com/title/tt13773206/)
https://www.imdb.com/title/tt13773206/

those 12 are way better than the random ones TMDB drop in

**Comment by hcgiub001** [comment]
I have the setting in Extended nfo-diamond_MO not the diamond info_MOD
here are my settings
![Screenshot (161)](https://github.com/user-attachments/assets/9305f9b0-f3a2-4f06-8d4a-92ad3db9e286)

I go into FENlight and over a movie press context menu and Diamond Info, then I have access to all the information
![Screenshot (162)](https://github.com/user-attachments/assets/0bae311c-3918-4a5a-9009-6277600d0bd1)

**Comment by Tikipeter** [comment]
Are the results labeled "Recommended By TMDB (9)" in your above screenshot actually the IMDb results?

**Comment by hcgiub001** [comment]
yes, that's a bug, no matter what you change to it will say TMDB.
he's missing 3 movies, mad max 1, mad max 2 and fallout, I'm not sure why

https://www.imdb.com/title/tt12037194/

and from tmdb
https://www.themoviedb.org/movie/786892-furiosa-a-mad-max-saga

it matches with DiamondInfoMod when I changed to TMDB only
![Screenshot (164)](https://github.com/user-attachments/assets/3bbe0ae9-7f2e-4da1-8114-dd22752e68fa)

The code is working mostly as it should. again not sure why those 3 movies where not listed in DIM

**Comment by hcgiub001** [comment]
I checked with this movie and cross referenced with IMDB, they match, the first entry is repeated, IMDB has 3 set's of 4, you click a little arrow to get to next set of 4

<img width="1280" alt="new 31" src="https://github.com/user-attachments/assets/f451a18b-87b5-42f7-b04d-6b722b38c69f">

<img width="1280" alt="last654" src="https://github.com/user-attachments/assets/e41c0de3-9e49-4d51-857a-8d498269d5e0">

**Comment by hcgiub001** [comment]
I just checked with this movie and it's matching, they also in the same order. again first entry is repeated

<img width="1280" alt="new 31" src="https://github.com/user-attachments/assets/8baa0b8e-b229-40d2-ab18-cc26aa265fdb">

<img width="1280" alt="last768" src="https://github.com/user-attachments/assets/314c7d79-7635-47b3-8337-dfd5bc9ac4a8">

**Comment by Tikipeter** [comment]
I've got it working.

There are 2 issues though:

1. I have already seen movies within the recommendations for TV Shows. As an example, Futurama has 3 movies included in the recommendations. I have no way to tell if the imdb_id is for a movie or tvshow, so those 3 results would be dropped as the subject media is a tvshow and vice verca.
2. It is slower than TMDb recommendations, because of the fact IMDb (webpage) is a lot slower to respond than TMDb's API, and also because I would need a call to TMDB for each of the 13 results to get details enough to use. The only thing returned from IMDB is the 13 IMDb id's e.g. ['tt908974', 'tt39847362'......etc]. In the case of movies, that results in 13 calls to TMDB to get each item's details. In the case of TV Shows, it results in 26 calls as there is no mechanism to immediately get TV Show data using an IMDB id. With movies there is.

Even so, those things can be threaded for speed, and since each list within Extras is also threaded, it doesn't slow the display of the Extras window at all.

Just be aware that if you get less than 13 results, then it is likely a movie was included in a TV Show recommendation or a TV Show was included in a Movie recommendation.

**Comment by hcgiub001** [comment]
this is awesome! I really cannot wait and yes I knew full well it would be way slower than TMDB since you can't beat API.
how would you implement this? use something similar to DimondInfoMod? I personally won't be using TMDB results. they just are inferior and most of the time not worth the bother.
Could we also have in context menu to call these results?
thanks so much for working on this! what are your thoughts on the recommendations compared to TMDB?
will wait when you finish

**Comment by Tikipeter** [comment]
It will be within the Extras menu, directly after Recommended (remember you can enable/disable items in the Extras menu).

It will also be available to assign as one of the button functions in the Extras menu.

It will also be a context menu option on Movies and TV Shows.

**Comment by hcgiub001** [comment]
love it lots! if it's possible please can you have a RunPlugin command so users can map it to a key if they want.
I use right key to load trailer and left key to load reccommended, and I can load extras with long press If I want to. that would be the icing on the cake!

**Comment by Tikipeter** [comment]
OK. Done for next update.

The commands for custom keys will change from next update though. So I can keep an eye on what's going on with them I made a new module for them.

EXTRAS DIALOG: `RunPlugin(plugin://plugin.video.fenlight/mode=custom_key.extras_menu)`

OPTIONS DIALOG: `RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key.options_menu)`

MORE LIKE THIS: `RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key.more_like_this)`

I don't think you use the Options command, but you'll need to change the Extras command after this next update.

**Comment by hcgiub001** [comment]
OMG I love this yes! Tikipeter can I ask one more command please? can we have a command that goes straight into SOURCE SELECT? 
Now that I have access to EXTRAS, I want to set Fenlight to play automatically but use long press for SOURCE SELECT on files that I want to change source. This is almost perfect! damn can't wait to try this out!

**Comment by hcgiub001** [comment]
this is awesome! works and wow it's fast!
I've mapped 
RunPlugin(plugin://plugin.video.fenlight/mode=custom_key.extras_menu)
to the right key
and it won't load
https://paste.kodi.tv/ecebukurag
