### ISSUE TITLE
does Fenlight not show extras for shows?

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#69]
does Fenlight not show extras for individual episodes such as cast?
on reddit someone is asking how to get extras in Umbrella, I've shown them Diamond Info_MOD but said
they could try Fenlight. 
Diamond Info_MOD shows extra menu with cast and everything for individual episodes but I trying it on Fenlight gives none
I thought it might be my setup but any show I try is the same.

**Comment by Tikipeter** [comment]
No episode specific info, no.

**Comment by hcgiub001** [comment]
thanks was just wondering on my end.
