### ISSUE TITLE
Enhancement request: click "In Trakt List" over movies/shows

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#70]
Someone wanted to know how to get EXTRA's in Umbrella but is used to Umbrella so wants to stick with it

I showed them Diamond Info_MOD and they are happy
https://www.reddit.com/r/Addons4Kodi/comments/1eh4u25/umbrella_i_button_for_info_doesnt_show_list_of/

but I started playing around with TheMovieDb Helper, I had no intention of using it but one feature I was kind of awes stuck by

any movie has this "In Trakt List", It gives you LOTS of lists the movie is inside. This is honestly awesome, especially for some obscure movie. I wanted to know how it's doing it? is it something fancy they are doing with TRAKT API so I had a look in trakt and it's right their at the bottom in each movie

![Screenshot (176)](https://github.com/user-attachments/assets/3b63fb55-279a-4db4-be7b-5e54b54ccab7)

people are going to love "MORE LIKE THIS", this is another way to find other content and I think it would be awesome if Fenlight had this. 
You've done allot recently, don't want you to get bored of this so if you like you could keep this in "TO DO LIST" if you liked the idea.

one thing I can't find on TheMovieDb Helper, is when you come across a list you like
(this is a "In Trakt List" for guardians-of-the-galaxy-2014)

![Screenshot (177)](https://github.com/user-attachments/assets/36d53d12-3cca-41f3-85df-8b759c2fe4ec)
it doesn't allow you to like it so now it's part of our lists 

![Screenshot (178)](https://github.com/user-attachments/assets/6aa271ed-982b-40c6-a2da-65309e3793c2)
but once you are inside the list it does allow you to add to collection 

![Screenshot (179)](https://github.com/user-attachments/assets/a033165f-c416-4a85-80e0-59618b283cec)

(EDIT: just realised adding to collection is just for the movie and not the list, so you don't have the list added to your own account which would be awesome)

one of the best ways to build your list collection
I was thinking you could integrate this in extras and have it in context menu to, way to good of a feature not to have :D

**Comment by hcgiub001** [comment]
Just for that one movie alone it has 80 thousand lists associated with it LOL. each movie will have so many lists. It's basically a different way to find recommended movies

**Comment by Tikipeter** [comment]
I'll include it as a context menu item for Movies and TV Shows. And include it in Extras. And include it as a button function option in Extras. 100 lists max returned.

**Comment by hcgiub001** [comment]
hell yeah! :D

**Comment by hcgiub001** [comment]
This is quite an enhancement and new way to explore, I wanted to make sure we take full advantage.
upon looking into what options we have in these lists I saw this
![Screenshot (218)](https://github.com/user-attachments/assets/890070da-852e-41a1-820d-7efad5a29caf)

if you can have an interface that allows us to sort the lists (of list) from all those option , that would be pretty epic
so we have
-popularity
-likes(30 days)
-likes(all time)
-comments
-items
-added
-update

I find added list interesting. since you have more chance you find newer movies so I probably make use of that

I was thinking if you add it in extra you could leave the first as a button that opens into something like this

![Screenshot (219)](https://github.com/user-attachments/assets/b04689fc-5b7e-4daa-bafb-da2647c9b36e)

this is from dramacool addon
https://github.com/groggyegg/groggyegg.github.io

which uses filters from this
https://asianc.sh/category/korean-movies

each time you pick a filter it changes colour
![Screenshot (220)](https://github.com/user-attachments/assets/e091d1ab-dcc8-41d0-9800-9d6f0145c925)

the filter seems to be dynamic on the site, not the same as what trakt is using where it's a refresh of the page so not sure how that would work.

another reason why I like the filter  box option is because I wanted to later ask if we can also filter each list with the options that are available (like below)

<img width="1280" alt="save4545" src="https://github.com/user-attachments/assets/c6116750-b676-48f9-a76e-6af97074e024">

we have types, genre and rank and the url shows what we are filtering
(e.g.https://trakt.tv/users/camipatria/lists/oled-eyegasm?genres=action&display=movie&sort=released,asc)

all these features added really make this a revolutionary search tool. it's similar to people discovering Real-Debrid for the first time. Now people don't need to bother creating their own lists. we can just like lists and have them ourselves.

themoviedb helper addon actually has this kind of feature for the lists but slightly different and not as inclusive as I would like

here is a walkthrough
(In Trakt Lists for Wonder woman)
![Screenshot (227)](https://github.com/user-attachments/assets/8c04e7d6-f2f1-4aeb-9523-cb00f8680bf1)

bring up context menu
![Screenshot (228)](https://github.com/user-attachments/assets/0e472bfb-a3a5-43c5-b131-4e38d178e25f)

click Browse sorted list
![Screenshot (229)](https://github.com/user-attachments/assets/6aa2e326-4af4-463e-a145-d4f5b22dc4e9)
![Screenshot (230)](https://github.com/user-attachments/assets/58cdf8de-ddd1-4248-a56f-90097c12c8b2)

so before you load the list you have preconfigured options to choose from, but it's still not as flexible as having a filter box like dramacool uses and we can have multi-variable filter options

I'm not sure what approach you'll take but please consider this feature could really be revolutionary so doing it right would be awesome. we've always had the ability to watch any movie but never the ability to search for new movies this easily using other peoples lists. it would be awesome! 

take your time implementing this. no rush

**Comment by hcgiub001** [comment]
so the filter box looks something like
<img width="1280" alt="yeswegot their" src="https://github.com/user-attachments/assets/9ccc6102-1853-4e25-aa04-1c16e44dc5e5">

and I can pick another filter at the same time
<img width="1280" alt="last one one" src="https://github.com/user-attachments/assets/9b8192fc-b46d-43c2-ade1-5d879899e355">

clicking on release date will cycle through

Release Date ↓ (blue) 
Release Date ↑ (blue)
Release Date    (white)

same with other in that list. (descending and ascending..)

so we have full control over what trakt site allows us.

**Comment by Tikipeter** [comment]
There's the Discover feature which is good enough for discovering things. I don't like dealing with Trakt when I don't have to.

**Comment by hcgiub001** [comment]
:( I probably went overboard asking for so much, please reconsider just adding the stuff you had some interest, it doesn't have to be now or so complicated.

**Comment by hcgiub001** [comment]
Thanks for adding the trakt list! works awesome! great job!

**Comment by hcgiub001** [comment]
I thought you wasn't going to add the feature which is why I asked to re consider, I don't care about the other stuff, the main stuff is awesome. also you added the option to like a list! this is awesome. really this is kind of revolutionary for people. now they can add lists so easily
