### ISSUE TITLE
[BUG]? movie not showing correct "more like this"

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#71]
Movie Detained (2024)
(https://www.imdb.com/title/tt8178762/)
this is what Fenlight is showing
![Screenshot (195)](https://github.com/user-attachments/assets/7c48ed45-2c32-4c1f-8c96-2685813abdc1)

this is what IMDB is showing
<img width="1280" alt="next 12345" src="https://github.com/user-attachments/assets/e4beba33-a03c-4725-9ad9-ef17efe53421">

I checked what Dimond Info is showing and it matches
<img width="1280" alt="next next 1234" src="https://github.com/user-attachments/assets/9cfb6b7b-418c-4d14-9a2d-34f17451c439">

**Comment by hcgiub001** [comment]
those incorrect movies it picked doesn't have ratings either

**Comment by Tikipeter** [comment]
You get a the Extras custom button working?

**Comment by hcgiub001** [comment]
> You get a the Extras custom button working?

no, I mentioned this on the previous thread
https://github.com/Tikipeter/tikipeter.github.io/issues/67

**Comment by hcgiub001** [comment]
I got a log
[kodi.log](https://github.com/user-attachments/files/16488238/kodi.log)

**Comment by hcgiub001** [comment]
Don't think anything is showing in logs I mapped this key
      <right>RunPlugin(plugin://plugin.video.fenlight/mode=custom_key.extras_menu)</right>
and nothing happens when I press it
the options and more like this commands work

**Comment by Tikipeter** [comment]
I'll double check the command when I get home from work.

**Comment by Tikipeter** [comment]
I'll not be much help here.

I get the correct entries for that movie.

And `RunPlugin(plugin://plugin.video.fenlight/mode=custom_key.extras_menu)` is the correct path for custom Extras. And it also works for me.

**Comment by hcgiub001** [comment]
let me double check

**Comment by hcgiub001** [comment]
strange extra doesn't work on mine. 
can you try this movie I did some more testing on my end and this movie was also not giving exact like imdb

consumed 2024
https://www.imdb.com/title/tt13374480/

this is what Fenlight is showing
![Screenshot (204)](https://github.com/user-attachments/assets/c41b6817-7070-4568-ab14-af8eab8b2321)

imdb is showing
<img width="1280" alt="yesyesyes1234" src="https://github.com/user-attachments/assets/c5f3beb3-909e-406b-9b28-9db52c133310">

and diamond info
<img width="1280" alt="next next 1234" src="https://github.com/user-attachments/assets/b1787157-6051-43d3-b1fe-515767adab9f">

they differ by two movies, 
imdb doesn't have 
the greatest surf  and detained.

I will try to do a fresh install of kodi later to see if the context menu can be fixed

**Comment by hcgiub001** [comment]
[kodi.log](https://github.com/user-attachments/files/16489052/kodi.log)
 this log picked up me pressing the key I set (F6) and shows what command I put in

maybe the rest can shed some light on why I'm having issues?

**Comment by hcgiub001** [comment]
> 2024-08-04 23:07:01.661 T:19856   debug <general>: CInputManager::HandleKey: f6 (0xf095) pressed, window 10025, action is RunPlugin(plugin://plugin.video.fenlight/mode=custom_key.extras_menu)

**Comment by hcgiub001** [comment]
I did notice my scripts (left and right) stopped working when I changed from my modded FENtastic to Nimbus today too. maybe it's something wonky on my end. ever since I modded FENtastic, I get fentastic error lots

**Comment by hcgiub001** [comment]
changed to Estuary and still won't show up but it shows when I press enter

**Comment by hcgiub001** [comment]
> I'll not be much help here.
> 
> I get the correct entries for that movie.
> 
> And `RunPlugin(plugin://plugin.video.fenlight/mode=custom_key.extras_menu)` is the correct path for custom Extras. And it also works for me.

the path was missing a question mark before mode

> RunPlugin(plugin://plugin.video.fenlight/?mode=custom_key.extras_menu)

Pretty happy about that now :D

**Comment by hcgiub001** [comment]
I "Clear All Cache (Excluding Favourites)"
both movies I tested have the correct "More Like This"

The issue is why it happened in the first place? could it be anything to do with cache?
I also use a VPN at times and I probably have been testing more movies than you so I could have come across some bug before you, I will keep monitoring if I get another issue with this but for now it seems all good.
