### ISSUE TITLE
[BUG] clicking side menu in Fenlight on "Add-on settins" has "This add-on can't be configured"

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#74]
![Screenshot (201)](https://github.com/user-attachments/assets/94c343a8-fb34-40f6-b7a8-96c527dfdf01)

someone asking on reddit
https://www.reddit.com/r/Addons4Kodi/comments/1ej96ap/comment/lggmn73/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

apparently it's working in FEN and also checked a few addons and they have it point to settings.

**Comment by xyzfre** [comment]
Fenlight has its own dialogue windows separate from Kodi I'm thinking, but I could be wrong.
