### ISSUE TITLE
Fen light error

### ISSUE THREAD

**Issue by matthius7** [Tikipeter/tikipeter.github.io#76]
Log posted. Latest Fen light and latest AF. Keeps kicking up Fen light error. Haven't changed anything in settings. 
https://paste.kodi.tv/tiwozedifi

**Comment by matthius7** [comment]
Seems clearing all my cache in Fl fixed issue.

**Comment by matthius7** [comment]
My apologies

**Comment by Tikipeter** [comment]
Never even saw this before you closed it. :)

> database disk image is malformed

Next time it happens, try Check for Corrupt Databases in the same menu first. It may be able to fix the issue.

**Comment by matthius7** [comment]
> Never even saw this before you closed it. :)
> 
> > database disk image is malformed
> 
> Next time it happens, try Check for Corrupt Databases in the same menu first. It may be able to fix the issue.

This makes sense as I started something in Fen light and it stalled/timed out like it was stuck, so I force closed Kodi. Upon reopening it started with the error.
