### ISSUE TITLE
2 series not to be found

### ISSUE THREAD

**Issue by djdirty60** [Tikipeter/tikipeter.github.io#77]
Good day Peter,

There is something crazy going on, at least 2 series have disappeared with me without a trace. From the collection, they are still in me Trakt and if I look for them in fen then they are not found there either.

See image 
![image](https://github.com/user-attachments/assets/2e8514af-a306-4270-a5df-87a87db49fa7)
![image](https://github.com/user-attachments/assets/7383d85c-51fd-4d53-868d-3f794507a515)
![image](https://github.com/user-attachments/assets/aca0427b-a9fb-4b88-8cd2-38cfbe8dd6a7)
![image](https://github.com/user-attachments/assets/384ef3ee-920f-4e5b-b0ae-890f01a0eb0a)
![IMG_1140](https://github.com/user-attachments/assets/58c38d74-d133-4bcc-af3e-44e3d8ee33aa)
![IMG_1139](https://github.com/user-attachments/assets/b8749de5-685e-41ab-9f1c-4f2803291140)
![image](https://github.com/user-attachments/assets/c3ea882c-d9dd-481f-a069-53760a25af61)
![image](https://github.com/user-attachments/assets/aecf3a0a-2839-435b-8d6d-79e78d1b75b6)

**Comment by Tikipeter** [comment]
Strange. You must have some kind of filter on in Kodi.

**Comment by djdirty60** [comment]
> Strange. You must have some kind of filter on in Kodi.

Problem is solved out of nowhere, they are back

**Comment by Jcloak** [comment]
This issue just happened to me today as well with the same exact show (Lord of the Rings). I didn't have any filters that would make it disappear. I manually marked the last episode of Season 1 as watched again and cleared the cache and that made it re-appear. The weird thing is it wouldn't show up in any lists at all until I did that.
