### ISSUE TITLE
[BUG] some titles don't have "Extras" option in context menu

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#78]
I've noticed some movies have "Extras" option in context menu and others don't
 
here is two movies that don't have extras in context menu (Eastern Condors 1987, Warriors Two 1978)
![Screenshot (213)](https://github.com/user-attachments/assets/cd5e707b-6033-47f9-ae13-670b58c21158)
![Screenshot (215)](https://github.com/user-attachments/assets/f050f95d-f7ac-42a7-9d39-93b93edecb3b)

and one that does
![Screenshot (217)](https://github.com/user-attachments/assets/b86ef5bf-cab5-4b54-a775-0fe99f1fe908)

seems like a bug since all movies allow us to enter extras menu

**Comment by hcgiub001** [comment]
low priority though so yeah thought I'll mention it

**Comment by Tikipeter** [comment]
You have open Collections or Extras set when selecting movies ("Both"). If the default action for the media will be opening Extras, then the Extras context menu item will not appear, rather the Playback context menu item will appear.

**Comment by hcgiub001** [comment]
thanks makes sense
