### ISSUE TITLE
[Feature Requested] split scraping sources into "fancy" and "simple"

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#79]
I've heard you've been asked this request many times and you've denied it every time.
another popped up
https://www.reddit.com/r/Addons4Kodi/comments/1ema7fo/fen_light_hide_scraper_source/

I organised a poll to see what users think, quite a few wanted it but I deleted it after a member alerted me about your decision so in respect to that I didn't pursue.

But I played around with the xml for scraping and found something that I think is worth adding.

https://streamable.com/6gu1fc

I took out all elements except the slider section and placed it closer to the top.

one thing I noticed is, it saves probably 50% of time. since you don't have animation to open the screen, and you don't pull up poster. it's almost instantaneous. part of me thinks you don't even need another screen to show scraping, it's so fast, but maybe because I have fast internet. 

I will respect your decision , it's not a big deal to me, but I prefer the speed I get from this, the scarping doesn't really serve much purpose , the final screen gives us what we need. Also it does seem lots love Fenlight but find this behaviour the only thing they don't like about it. you don't have to have that element as I did but it does fit in with your scraping screen to just strip it to the slider.

having two options, one for fancy and one for simple?

**Comment by hcgiub001** [comment]
why stop at their why not have the ability to not show the scarping screen at all, here is an example 
https://streamable.com/cx4j53

the kodi click is an indication that we've pressed something. the scraping is less than a second, for those that have decent hardware and decent internet speeds, showing the scraper is not relevant, it's more messy with showing to many screens to fast.
so I propose you have 3 layers
Full. Partial, None
either chose the scraping screen you have now, chose a small indicator (or use the square slider thing) or chose none

I mean your addon is called Fen"light" LOL

lots of users would be happy too

**Comment by hcgiub001** [comment]
here is a difference in speed with having the scraping screen and without

https://streamable.com/l3c9vz
https://streamable.com/n61zh8

to make it fair I cleared all cache. the difference is probably twice as fast, fast enough that we don't even need a scraping window.
on my build I was playing around with extras menu to. I deleted the fade animation and my extras load instantly. the fanart takes a tenth of a second but it's okay. I prefer snappiness

**Comment by TwilightMercy** [comment]
> here is a difference in speed with having the scraping screen and without
> 
> 
> 
> https://streamable.com/l3c9vz
> 
> https://streamable.com/n61zh8
> 
> 
> 
> to make it fair I cleared all cache. the difference is probably twice as fast, fast enough that we don't even need a scraping window.
> 
> on my build I was playing around with extras menu to. I deleted the fade animation and my extras load instantly. the fanart takes a tenth of a second but it's okay. I prefer snappiness 
> 
> 

Can you share Partial/None XMLs files for testing the changes?
