### ISSUE TITLE
Errors when installing from zip

### ISSUE THREAD

**Issue by Skabneck** [Tikipeter/tikipeter.github.io#8]
Installing FEN on kodi. 
Raspberry Pi - Raspbian os 

Logs:
https://paste.kodi.tv/utozuguhup

**Comment by Skabneck** [comment]
Kodi 19.4 is what I am running and is what is installed when I run:

sudo apt-get install kodi

**Comment by Tikipeter** [comment]
You need to be using Kodi 20+.
