### ISSUE TITLE
[Feature Request] add Original Language in Extras Menu

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#83]
Now with Trakt Lists, we'll come across a list with movies from different nations. 
with the poster alone it's not clear which is the original language.
Users might be looking to watch in a specific language so could we please have the "Original Language" tag from TMDB added somewhere in Extras Menu

<img width="1280" alt="Screenshot (253)" src="https://github.com/user-attachments/assets/d75b4c24-f2c9-409d-8e7b-05ad5ec764b3">

like this movie, seems to be from Asia but it's Finnish

![Screenshot (254)](https://github.com/user-attachments/assets/d2b6e6b4-cffc-4f53-b2b3-6fcb8500e75a)

thanks for your consideration

**Comment by Tikipeter** [comment]
I've done this for next update.

Meta cache will need to be cleared to see it in the Extras window.

**Comment by hcgiub001** [comment]
Awesome thanks!
