### ISSUE TITLE
[Feature Request] TV Premieres sort order by Release Date

### ISSUE THREAD

**Issue by rich333000** [Tikipeter/tikipeter.github.io#85]
TV Premieres sort order by Release Date.

The content of the list is pretty good, but the order make it difficult to use, with newer shows showing up on page 2.

Tried sorting it with Skin Variables but it only sorts page by page so newer shows are still on page 2. Tried making a similar list with the Discover List feature, but new items are not added to the list after the creation date of the list.

Can you please enable or add an option to have the TV Premieres list sorted by Release Date.

**Comment by Tikipeter** [comment]
The list will be terrible if I were to do that. Lots of crappy TV Shows get released every day it seems. For the masses, it needs to stay sorted by popularity.

You can just make a "Discover" list with everything blank except "Sort By": First Aired (desc) and if you want "Released Only": True and that will give you a list of the TV Shows ordered from the latest one released. That list can then be added to the TV Show section of the addon/used as a widget etc.

See Tools->Tips for Use->Discover if you have no idea what I am talking about.

**Comment by rich333000** [comment]
Yes, I tried doing what you suggested before I raised this issue. The problem I have is that my Discover lists are not updating at all, which is now noted in issue #86

**Comment by Tikipeter** [comment]
Oh, I see. Same person. :)

Wait until I get that sorted out and then make the list and it should update each 24 hours.

**Comment by Tikipeter** [comment]
Please keep this open until then.
