### ISSUE TITLE
[Feature Request] Additional options in Discover

### ISSUE THREAD

**Issue by rich333000** [Tikipeter/tikipeter.github.io#86]
Couple ideas that would really increase the power of using the discover lists for widgets and browsing.

1. Option per list to trigger refresh on open. So when new shows or movies come out, the list is refreshed as if newly created when each time it's opened. (Not sure if the list contents are being saved or cached, but new items are not showing up for me after testing a bit). Eg. If I make a comedy movie list now, sort by Release Date, it will quickly become out of date.

2. Option to sort by Random, This could possibly be achieved using the Random Lists section if Discover Lists were added to it like th Trakt lists. This would really open up a lot of options to create lists (and shortcut groups). Eg.  I like the random year lists, but want to exclude before 1960, or much more specific lists than currently in the Random List section.

**Comment by Tikipeter** [comment]
1. In the currently released version, caching for those Discover lists are set to 48 hours. I've lowered that to 24 hours. I'm not willing to do no caching, as we need to look after the APIs that we use.

**Comment by rich333000** [comment]
1. 24hrs (even 48hrs in most cases) would work well, but my lists are not refreshing at all. I've created a few lists and sorted them by date released/aired. None of them have refreshed at all over the past week and are still the same as the date they were created.

**Comment by Tikipeter** [comment]
1. Oh well. Probably something going wrong then. These things happen sometimes.

**Comment by Tikipeter** [comment]
1. I'll make a Discover list and check it tomorrow and see if it gets fresh data after the 24 hours.

**Comment by Tikipeter** [comment]
2. I could implement something to "randomize" a list made using Discover. I could do that by adding a "Random" option in the sort order choices. This is not supported by TMDb of course.

The issue is, since it would be random, the list would become a list of 20 items, with no "Next Page", just like the current random lists.

**Comment by Tikipeter** [comment]
1. Fixed next update.
2. Done for next update.

**Comment by rich333000** [comment]
Cool, this is going to be great! This really is the best add-on for
browsing and discovering new stuff. Thanks!

Just had another idea haha. Would it be possible to have a reload/refresh
button at the end of all the random lists? Idk, just an idea.
