### ISSUE TITLE
[BUG] Iron man 1 doesn't show up as a collection

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#87]
so Iron man 1 won't open into a collection set, it doesn't even show it in Extras Menu
but iron man 2 and 3 do
also the other bug where if you exist a collection than the focus is on the movie in the collection that appears higher up is present and this time exiting from either going into iron man 2 or iron man 3 focuses on iron man 2.

those 2 movies don't see it as part of the collection but when you entre their collection , iron man 1 is present

here is a video

**Comment by Tikipeter** [comment]
TMDb isn't including it in the Iron Man collection at the moment for some reason.....
