### ISSUE TITLE
Letterboxd similar (All, Themes, Nanogenres)

### ISSUE THREAD

**Issue by hcgiub001** [Tikipeter/tikipeter.github.io#88]
Letterboxd has another engine for similar content

At times I've noticed it has better recommendation than IMDB/TMDB

It has an API too not sure if you can make use of it

Someone complained that IMDB doesn't have a similar movie to another 
https://www.reddit.com/r/Addons4Kodi/comments/1ej96ap/comment/lgefu8c/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

and letterboxd has that as first movie in it's "All similar" as the first one.
https://letterboxd.com/film/the-ministry-of-ungentlemanly-warfare/similar/

also letterboxd similar stuff is powered by nanocrowd and has this things called "nanogenres"
like so
https://letterboxd.com/film/the-ministry-of-ungentlemanly-warfare/nanogenres/
![Screenshot (391)](https://github.com/user-attachments/assets/5855bd2d-5b90-43f5-9cb2-847d104bd5d4)
 
if we are able to get this data , wow this would be insane.
even if you wanted, not sure where you would fit all this data or how much you'll take, even just having the "All" from similars would be pretty insane

here is their API
https://api-docs.letterboxd.com/

it does have similar like here
![Screenshot (392)](https://github.com/user-attachments/assets/03b7a03e-7d0d-4c53-a512-3b93c0698045)

could we please have this added? way more useful than "more form genres" and "more from years"

(the similar "All" section is from least similar to most similar, you have to click on similar and go all the way down)

the nanogenres is sometimes that useful that I was thinking it having it's own custom window would be pretty insane
you can even change how the custom window behaves like make it look more like Nimbus navigation, which would be insane 

thanks for your consideration

**Comment by Tikipeter** [comment]
It seems you need to send them an email to get access, which rules Kodi addons like this out.

In consolation, apparently they rarely reply to the email anyway.

**Comment by hcgiub001** [comment]
that's a shame, seems we can't have access to them? thanks for looking into this though.

**Comment by Tikipeter** [comment]
That's what I got from what I read.

When I have some time I'll check out the API better. Make a call to it and see if it works.

Doesn't sound like I can get access though.

**Comment by hcgiub001** [comment]
I didn't think it would have been so straight forward. It's fine if this can't be implemented. and as always I appreciate what you do and don't expect you to have to respond or take on a request. You do to much as it is.
