### ISSUE TITLE
[Feature Request] A filter to look for preferred terms/tags/strings in the sources for autoplay

### ISSUE THREAD

**Issue by OfficerKD637** [Tikipeter/tikipeter.github.io#89]
Hi Peter!

Hope you're doing well!

I was wondering if it'd be possible to add a filter in the settings to look for specific terms when choosing a source for autoplay (akin to HDR and Dolby Vision filters)

Here's an example to demonstrate:
Several Marvel movies have a Blu-Ray release as well as an online release on Disney+. Although the disc releases have higher visual fidelity, the online ones are often in the IMAX aspect ratio (which IMHO adds a lot to the immersion) 

It'd be awesome if there was a setting to look for certain terms like 'IMAX', 'WEB-DL', etc. in the title of the sources when autoplay is enabled. 
I know there's always an option to manually choose the source, but I thought this feature could add to the convenience of autoplay.

Let me know what you think!

**Comment by Tikipeter** [comment]
This is a bigger job than some of the other current requests, so let me think on it.

**Comment by OfficerKD637** [comment]
Thank you so much for considering it! And I'm sorry for the hefty request.
Currently, if I know a movie has been released in multiple ratios (IMAX, cinemascope, etc.) I manually scrape for sources and then use 'Filter by Title' to skim through the results.

But I do know that adding this over to autoplay isn't so easy because you'd also need to have some sort of a robust fallback mechanism. "What if the scrapers can't find any sources with the specified term?" Or "How would you deal with multiple terms?". I'm sure there are many more technical intricacies and it'd suck to introduce a feature at the expense of breaking any other autoplay functionality. I'll let the coding genius (you) come up with a solution haha.

Thank you for your time!

**Comment by OfficerKD637** [comment]
Hey Peter!

Hope you've been doing well!

The last few updates have been blowing my mind! Thank you so much! I've been trying to study your code and learn how you do what you do but it still seems like magic to me haha. Everything is so organized and the comments help me so much when I'm trying to wrap my head around what a specific line does.

I was wondering how the 'Filter by Title' or 'Filter by Info' exactly works and if it's possible to add the 'Include/Exclude/Prefer' functionality to this? I remember you saying something along the lines of 'parsing the titles' of the movies and trying to avoid false negatives when dealing with the AI issue.

Would it be possible to have something like a 'Preferred terms' section under Results > Sorting & Filtering where one could add things like 'IMAX', 'REMUX', etc. and then we could use operators to determine the order of preference? And if Fen Light can't find any results with those terms it follows the 'Ignore all filters when no results' setting?

You would probably need to separate this into Movies and Episodes as well since a lot of terms are mutually exclusive (eg. 'PACK' only applies to TV Shows and not Movies)

![image](https://github.com/user-attachments/assets/32b0230c-5cd2-496c-8945-2e46084be8ad)

Example: Results with both 'IMAX' and 'REMUX' are preferred first, then just IMAX, then just REMUX, and so on and so forth... 
You'd maybe have to limit the number of terms to something reasonable to avoid the performance getting a hit.

The 'Filter By Info' and 'Filter By Title' are perfect and I hope there is a way to incorporate it into autoplay. I usually only have a couple tags that I like to look for before playing a file, so if I could specify these in the settings and Fen Light would automatically look for them when autoplaying... it'd make everything so awesome! This coupled with the other filtering settings (size, HDR, AI, Audio, etc. ) make hitting the sweet spot with autoplay easy peasy!

I'm really sorry for rambling and I have no idea how much of this is feasible but I would love to hear your thoughts. It's always an amazing opportunity to learn something new from you!

Thank you so much!

**Comment by Tikipeter** [comment]
Done for next update.

Sorry about the extra long delay, I've been waiting for holidays from work to get a little time for these enhancements.

I'll work through them from bottom to top.

**Comment by OfficerKD637** [comment]
Tikiiiii!!! You're the man! Thank you so much!! I love you (platonically, of course)
