### ISSUE TITLE
[Bug] Fen/Fen Light - "SHOW RD_CLOUD ONLY" filter doesn't apply

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/tikipeter.github.io#9]
Hi Tikipeter,

I've noticed an issue in both Fen / Fen Light, in the filter's mini-window on source select window.

Showing example from Fen: (same issue in Fen Light)

1. Fen - Tools - Settings - Provider Accounts: (Search Cloud Storage from RD is enabled)
![image](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/33e4111b-c762-4d98-98fa-c0ba9a8d9d15)

2. RD CLOUD sources are shown:
![image_2024-01-20_15-04-29](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/ad8ed6aa-7d4d-45d3-a4bd-ae86b5096e0b)

3. in the FILTERS window - all filters are working great, except "SHOW RD_CLOUD ONLY" filter - does nothing:
![image](https://github.com/Tikipeter/tikipeter.github.io/assets/29895680/3b9615ea-ffea-49d1-bea6-6b0c014853a1)

Error from log (the error is the same also in Fen Light):
```
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'ValueError'>
                 Error Contents: too many values to unpack (expected 2)
                 Traceback (most recent call last):
                   File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\windows\sources.py", line 106, in onAction
                     if self.get_visibility('Control.HasFocus(%s)' % self.filter_window_id): return self.filter_action(action)
                   File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\windows\sources.py", line 82, in filter_action
                     filter_type, filter_value = chosen_listitem.getProperty('filter_info').split('_')
                 ValueError: too many values to unpack (expected 2)
                 -->End of Python script error report<--
```

**Comment by Tikipeter** [comment]
This should be fixed in Fen.

I think Fen Light it will be in the next update. Can't remember what was included in the last FL update.
