### ISSUE TITLE
Selection Idea for Track Lists Manager

### ISSUE THREAD

**Issue by slippersareon** [Tikipeter/tikipeter.github.io#90]
We currently have:
Track Lists Manager > Add to Trakt List
or...
Track Lists Manager > Remove from Track List

Can we please also have...
Track Lists Manager > Move to Track List

Today I changed my track list category names around and then had to manually remove movies from a track list and then go back in to add to a track list. Having a move to track list could have saved me lots of time having to move so many movies to the new movies category list. 

This is just a suggestion Tiki Peter. Thank you for fen light and your time

**Comment by Tikipeter** [comment]
Can't you just rename your lists on the Trakt website, and save all the trouble of moving items around?

**Comment by slippersareon** [comment]
Hi Tikipeter. I can only create 5 free lists on Trakt. So some of my group lists gave more than 1 genre with a lot of movies in them. I have renamed them as some genres are better suited together. Having an option to just click a movie and then move to another folder would save lots of time.

I'm a huge fan of your addon fenlight and be lost without it. A big thank you for everything.
