### ISSUE TITLE
[Feature Request] UK Certifications 

### ISSUE THREAD

**Issue by rizreflects** [Tikipeter/tikipeter.github.io#92]
Hey Peter, I hope you've been doing well! The Addons4Kodi subbreddit has sure gotten a lot more boring since you've not been around. About a year ago, I asked you whether it was possible to enable UK MPAA certifications in Fen Lite, and at that time you told me it wasn't possible. I was wondering whether this is something you'd be willing to add to Fen Lite as a feature request.

The OG Fen had been working perfectly for me until the last few months. But recently I've been coming across some problems with scraping. Every now and then it refuses to play a new video until I restart kodi. Due to this, I've had to look at other options. I'm aware that POV and Umbrella both offer UK certifications, but if I'm honest, they just don't cut it for me. They both have small nitpicky problems. POV has removed some of your original features like checking chapters to determine when to show the upnext popup in tv shows. And Umbrella lacks which is arguably my favourite thing about Fen, Extras. In all honesty, your Fen addon to me is nothing short of genius. I think its perfect, which is why I'm so reluctant to move on to another addon. Furthermore, I feel as though I'm missing out on all your new innovations, such as this new random list feature you have. Fen has been great and I'd love to try out Fen lite.

Would you consider adding UK Certifications to Fen lite? I completely understand if you don't want to add it because you feel as though it'll slow down the addon, or even if you just choose not to add it. But I thought I'd ask first before using another addon long term. Hopefully you'll consider it. Either way though, I appreciate what you've done with Fen a lot, it's been a blessing these past few years and I'm highly appreciative of your work.

All the best to you my friend!

**Comment by Tikipeter** [comment]
>Every now and then it refuses to play a new video until I restart kodi.

I'll address this first. I don't think changing to Light will make any difference here. I'm having a similar issue using the official Youtube addon. Sometimes Kodi just bugs out, struggles to start the stream, and then plays it juddery with no sound.

Even worse, local files on my home server can do the same, so it isn't even an online streams type thing.

I can add a setting for classifications next update. I've got zero time currently to do much more than jump on here and give a couple of replies, so it may be a week or so away.

As for reddit, leaving there was good for the soul. Just full of horrible people, and you turn into one yourself by just trying to defend yourself constantly.

**Comment by rizreflects** [comment]
This is great news. Thanks a lot. I look forward to seting up fen light finally! And take your time, there's no rush at all.

**Comment by Tikipeter** [comment]
Done for next update.

Settings->Content->Content->Set MPAA Region

Changing the setting will refresh the cache. If that fails, reset the cache manually using Tools->Database & Cache Management->Clear Meta Cache.
