### ISSUE TITLE
[Feature Request] Check subtitles for playnext popup

### ISSUE THREAD

**Issue by luckylukz02** [Tikipeter/tikipeter.github.io#94]
Hi Peter,

I've been using your fenlight addon a lot in recent months. Great work on it! It's given me much enjoyment.

Id like to request a feature which is currently available in Umbrella. I think it would be a great addition to your Fen Light Addon. In Umbrella, it is possible to use the subtitle time to dictate when the next up popup will show. I feel that this combined with chapter info (which you currently have) will make the vast majority of popups work in a timely manner.

It would be like this:

First check chapter info > if no chapter info present then check subtitles finishing time > if no subtitles present then fall back to percentage or set time.

What do you think of this feature? Is it something you'd consider adding? I feel it would be a great behind-the-scenes improvement to Fen Light. Thank you for your time.

**Comment by Tikipeter** [comment]
Out of respect to the work put into this by umbrella_dev, I have enacted a moritorium on adding this feature to Fen Light.

The moratorium expires in March 2025.
