### ISSUE TITLE
In Progress show glitch, Recently watched episodes sorting, Upcoming Progress request.

### ISSUE THREAD

**Issue by VelimirSaban** [Tikipeter/tikipeter.github.io#96]
Hi Peter,

Since Fenlight has a great EXTRAS option, (which is a real game changer for me, really thank you for that) - I want to completely switch from Umbrella to Fenlight, including all my widgets that I currently have configured, but I ran into a few problems.

1. One of the widgets I use is "in-progress tv shows". In it, Fenlight shows me as if the show Abbott Elementary has not been watched to the end, as if one episode has not been watched yet. I researched what could be the problem and came to the conclusion that this could be the reason:

![abbot](https://github.com/user-attachments/assets/c5b0072f-e37f-4cc9-9b92-d0b148560a89)

As you can see, that show doesn't have a second episode of the third season. Two episodes E01 and E02 are combined into one - E01 and since there is no E02, I think that's why the Fen show season is unfinished.

2. The recently watched episodes widget is sorted incorrectly, some episodes I watched a week ago are near the top of that list. It seems as if only the last two watched episodes are always shown correctly, and then after the third place on the list, the wrong sorting starts. I tried clearing the cache and reinstalling the addon, I even installed Fenlight on a completely different device and I got the wrong sort again. Sorting is good on the Trakt page and in other add-ons.

3. There is a list from which a widget can be configured that will display all upcoming series. But I can't find the one called "upcoming progress" which I used in Umbrella. On it, there are all the TV shows which I have watched and are getting a new season soon. I know there is a Trakt Calendar option, but sometimes when a series has multiple episodes that come out on the same day, that list can be quite crowded. 

Thank you very much for the effort you invested in the maintenance and further development of this addon. I'm really grateful.

Vel.

**Comment by Tikipeter** [comment]
1. The code I use to determine total eps/total watched etc relies upon decent data. This is the first time I have seen garbage data coming from TMDb like this. There is no valid reason to present the episodes as 01 and then 03. This needs to be fixed on TMDb.
2. I'll have a look and see if there's something going on. I may need you to post here your trakt.db file from Fen Light's userdata folder.
3. There's no Upcoming Progress in Fen Light. All addons are different.
