### ISSUE TITLE
Issue with LandscapeInfo Image Display in Fentastic (FL v1.0.68)

### ISSUE THREAD

**Issue by Polgara01** [Tikipeter/tikipeter.github.io#99]
Good evening,

After an update and reload, the images in my LandscapeInfo widgets (using Fentastic) are distorted.  

-- Rolling back to 1.0.67 had no effect.

-- Rolling back to 1.0.66 resolved the issue.

-- Tested on 2 separate units.

I am running, and will continue to run, the latest version.  Is this something that you can (or are willing to) fix or should I look for a solution on the skin side?

As a developer, I'm also curious as to what might have changed to cause this, as nothing has changed with the skin.  Did you change the image source (the images appear to be different)?   If so, is providing a toggle/setting for the image source a viable solution?  

Thank you!

**Comment by Tikipeter** [comment]
I changed the image assigned to "thumb" from "landscape" to poster or landscape or fanart (in that order) with the recent update. That aligns with what is more expected from the addon, so a change will need to be made skin side for this.

The image assigned for thumb for episodes should be landscape or fanart, but not for movies, tvshows and seasons.

You will need to change the skin's code yourself, as I believe ivarbrandt is no longer working on Fentastic.

If you give me 5 minutes I can see what the new code should be to handle this.....

**Comment by Tikipeter** [comment]
Replace `IconWallThumbVar` within `Variables.xml` with this.....

```
	<variable name="IconWallThumbVar">
		<value condition="String.IsEqual(listitem.dbtype,genre) + System.AddonIsEnabled(resource.images.moviegenreicons.transparent)">$INFO[ListItem.Label,resource://resource.images.moviegenreicons.transparent/,.png]</value>
		<value condition="String.IsEqual(listitem.dbtype,studio) + System.AddonIsEnabled(resource.images.studios.white)">$INFO[ListItem.Label,resource://resource.images.studios.white/,.png]</value>
		<value condition="[String.IsEqual(ListItem.dbtype,movie) | String.IsEqual(ListItem.dbtype,tvshow)] + !String.IsEmpty(Listitem.Art(landscape))">$INFO[Listitem.Art(landscape)]</value>
		<value condition="[String.IsEqual(ListItem.dbtype,movie) | String.IsEqual(ListItem.dbtype,tvshow)] + !String.IsEmpty(Listitem.Art(fanart))">$INFO[Listitem.Art(fanart)]</value>
		<value condition="!String.IsEmpty(ListItem.Thumb)">$INFO[ListItem.Thumb]</value>
		<value condition="!String.IsEmpty(Listitem.Art(landscape))">$INFO[Listitem.Art(landscape)]</value>
		<value>$INFO[ListItem.Art(fanart)]</value>
		<value>$INFO[ListItem.Icon]</value>
	</variable>
```

Then reload skin or restart Kodi.

**Comment by Polgara01** [comment]
That worked, thank you.

**Comment by Ykhavari** [comment]
I have this same issue but I'm running it on a libreelec on my raspberry pi, how would I go about fixing it? ssh into it?
